- name: '{{ droplets_title }} - create droplets'
  digital_ocean_droplet:
    unique_name: yes
    oauth_token: "{{ droplets_api_token }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    region_id: "{{ item.region_id }}"
    size_id: "{{ droplets_size_id }}"
    image_id: "{{ droplets_image_id }}"
    wait_timeout: "{{ droplets_wait_timeout }}"
    private_networking: "{{ droplets_private_networking | default(omit) }}"
    ipv6: "{{ droplets_ipv6 | default(omit) }}"
    user_data: "{{ droplets_user_data }}"
  with_items:
  - "{{ droplets_list }}"
  loop_control:
    label: "{{ item.name }} - {{ item.state }}"
  register: droplets_details

- name: '{{ droplets_title }} - Define value of droplets_active'
  set_fact: droplets_active="{{ droplets_details.results | map(attribute='data') | selectattr('droplet', 'defined') | map(attribute='droplet') | list }}"

- name: '{{ droplets_title }} - tag each droplet'
  digital_ocean_tag:
    api_token: "{{ droplets_api_token }}"
    resource_id: "{{ item[0].id }}"
    name: "{{ item[1] }}"
    state: present
  with_nested:
  - "{{ droplets_active }}"
  - "{{ droplets_tags }}"
  loop_control:
    label: "droplet: {{ item[0].name }} - tag: {{ item[1] }}"
