- name: create tags
  digital_ocean_tag:
    api_token: "{{ droplets_api_token }}"
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ droplets_tags }}"

- name: create droplets
  digital_ocean:
    unique_name: yes
    api_token: "{{ droplets_api_token }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    region_id: "{{ item.region_id }}"
    command: "droplet"
    size_id: "{{ droplets_info.size_id }}"
    image_id: "{{ droplets_info.image_id }}"
    wait_timeout: "{{ droplets_info.wait_timeout }}"
    private_networking: "{{ droplets_info.private_networking | default(omit) }}"
    ipv6: "{{ droplets_info.ipv6 | default(omit) }}"
    user_data: "{{ droplets_user_data }}"
  with_items:
  - "{{ droplets_list }}"
  loop_control:
    label: "{{ item.name }}"
  register: droplets_details

- name: Define value of droplets_active
  set_fact: droplets_active="{{ droplets_details.results | selectattr('droplet', 'defined') | map(attribute='droplet') | list }}"

- debug: msg="IP of droplet {{ item.name }} is {{ item.ip_address }}"
  with_items: 
  - "{{ droplets_active }}"
  loop_control:
    label: "{{ item.name }}"

- name: tag each droplet
  digital_ocean_tag:
    api_token: "{{ droplets_api_token }}"
    resource_id: "{{ item[0].id }}"
    name: "{{ item[1] }}"
    state: present
  with_nested:
  - "{{ droplets_active }}"
  - "{{ droplets_tags }}"
  loop_control:
    label: "droplet: {{ item[0].name }} - tag: {{ item[1] }}"

- set_fact: 
    droplets_hosts_info: |
      {{ '# ' + lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}

- name: generate the hosts information with the droplets ips
  set_fact: 
    droplets_hosts_info: |
      {{ droplets_hosts_info | default('') }}
      {{ item.name }} ansible_host={{ item.ip_address }} ansible_user={{ droplets_host_user }} ansible_become_pass={{ droplets_host_pass }}
  with_items: 
  - "{{ droplets_active }}"
  loop_control:
    label: "{{ item.name }}"

- name: Update the hosts file with the generated hosts
  blockinfile:
    path: "{{ droplets_hosts_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ droplets_hosts_group }}"
    insertafter: "\\[{{ droplets_hosts_group }}\\]"
    block: "{{ droplets_hosts_info }}"

- name: refresh inventory
  meta: refresh_inventory