### Cloud Node User Data ###

- name: "{{ cloud_node_item_title }} - cloud_node_user_data_title"
  set_fact:
    cloud_node_user_data_title: "{{ cloud_node_item_title }} - user data"
    cloud_node_user_data_node_name: "{{ cloud_node_name }}"
    cloud_node_user_data_node_params: "{{ cloud_node_params }}"
    cloud_node_user_data_credential: "{{ cloud_node_credential }}"
  tags: ["no_print"]

- name: "{{ cloud_node_user_data_title }} - cloud_node_user_data_ssh_key_filename"
  set_fact:
    cloud_node_user_data_ssh_key_filename: "{{ cloud_node_user_data_node_name + '.key' }}"
    cloud_node_user_data_host_ssh_public_keys: []
    cloud_node_user_data_host_ssh_public_keys_path: >-
      {{
        ((cloud_node_user_data_credential.host_ssh_public_keys_path | default('')) != '' )
        | ternary(
          env_dir + '/'
            + cloud_node_user_data_credential.host_ssh_public_keys_path | default(''),
          ''
        )
      }}
  tags: ["no_print"]

- name: "{{ cloud_node_user_data_title }} - cloud_node_user_data_host_ssh_public_keys"
  set_fact:
    cloud_node_user_data_host_ssh_public_keys: >-
      {{ lookup('file', cloud_node_user_data_host_ssh_public_keys_path).splitlines() | list }}
  when: (cloud_node_user_data_host_ssh_public_keys_path | default('')) != ''
  tags: ["no_print"]

- name: "{{ cloud_node_user_data_title }} - cloud_node_user_data_host_vars"
  set_fact:
    cloud_node_user_data_host_vars:
      host_user: "{{ cloud_node_user_data_credential.host_user }}"
      host_pass: "{{ cloud_node_user_data_credential.host_pass }}"
      host_ssh_public_keys: "{{ cloud_node_user_data_host_ssh_public_keys }}"
      credentials: "{{ cloud_node_user_data_credential.user_data | default({}) }}"
      params: "{{ cloud_node_user_data_params.user_data_params | default({}) }}"
    cloud_node_user_data_file: >-
      {{
        ((cloud_node_user_data_params.user_data_file | default('')) != '')
        | ternary(
          env_dir + '/' +
            (cloud_node_user_data_params.user_data_file | default('')),
          ''
        )
      }}
  tags: ["no_print"]

- name: "{{ cloud_node_user_data_title }} - cloud_node_user_data - initial"
  set_fact:
    cloud_node_user_data: ""
  tags: ["no_print"]

- name: "{{ cloud_node_user_data_title }} - cloud_node_user_data - lookup"
  set_fact:
    cloud_node_user_data: >-
      {{
        lookup(
          'template',
          cloud_node_user_data_file,
          template_vars=dict({ 'params': cloud_node_user_data_host_vars })
        ) | trim
      }}
  when: cloud_node_user_data_file != ''
  tags: ["no_print"]
