- name: 'create the directory "{{ long_run_output_path }}" to run "{{ long_run_title }}"'
  become: yes
  file:
    path: "{{ long_run_output_path }}"
    state: directory
    mode: 0744

- set_fact: 
  long_run_register: ''

- name: 'start the execution of "{{ long_run_title }}" -> "{{ long_run_cmd }}"'
  become: yes
  shell: "{{ long_run_cmd }} >> {{ long_run_output_path }}/output.log 2&>1"
  args:
    chdir: "{{ long_run_path }}"
  async: "{{ long_run_timeout | int }}"
  poll: 0
  register: 'long_run_register'

- name: 'Watch "{{ long_run_output_path }}/output.log" until "{{ long_run_title }}" finishes'
  become: yes
  include_role:
    name: 'watch'
  vars:
    watch_file: '{{ long_run_output_path }}/output.log'
    watch_job: 'long_run_register'
    watch_timeout: "{{ long_run_timeout | int }}"
    watch_poll: "{{ long_run_poll | int }}"
