- set_fact:
    long_run_before: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: '[{{ long_run_title }}] - create the directory "{{ long_run_output_path }}" to run'
  become: "{{ long_run_become }}"
  file:
    path: "{{ long_run_output_path }}"
    state: directory
    mode: 0744

- name: '[{{ long_run_title }}] - start the execution of "{{ long_run_cmd }}"'
  become: "{{ long_run_become }}"
  shell: "{{ long_run_cmd }}"
  args:
    chdir: "{{ long_run_path }}"
  async: "{{ long_run_timeout | int }}"
  poll: 0
  register: 'long_run_register'

- debug: 
    msg: "before: {{ long_run_before }}"

- name: '[{{ long_run_title }}] - Watch "{{ long_run_output_path }}/output.log" until finishes'
  become: "{{ long_run_become }}"
  include_role:
    name: 'watch'
  vars:
    watch_title: "{{ long_run_title }}"
    watch_file: '{{ long_run_output_path }}/output.log'
    watch_job: 'long_run_register'
    watch_timeout: "{{ long_run_timeout | int }}"
    watch_poll: "{{ long_run_poll | int }}"

- name: '[{{ long_run_title }}]'
  debug: 
    msg: "before: {{ long_run_before }}"

- name: '[{{ long_run_title }}]'
  debug: 
    msg: "after: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
