- name: Play 01 - Create Cloud Instances
  hosts: main
  tags:
  - init
  - setup
  - cloud
  gather_facts: no  
  tasks:
  - name: Gathering facts
    setup: 

  - include_role: 
      name: "main_vars"
    vars:
      main_vars_env_file: "{{ env_file }}"
      main_vars_platform: "discourse"

  - include_role: 
      name: "main_cloud"
    vars: 
      main_cloud_role: "{{ main_item.role }}"
      main_cloud_vars: "{{ main_item.vars }}"
      main_cloud_extra: "{{ main_item.extra }}"
      main_cloud_dns: "{{ main_vars.dns }}"
    loop: "{{ main_vars.cloud.values() | list }}"
    loop_control:
      loop_var: main_item

###############################################################################

- name: Play 02 - Wait for hosts to be ready
  hosts: discourse
  tags:
  - init
  - setup
  - test
  gather_facts: no
  tasks:
  - include_role: 
      name: "main_vars"
    vars:
      main_vars_env_file: "{{ env_file }}"
      main_vars_platform: "discourse"

  - include_role: 
      name: "host_test"

###############################################################################

- name: Play 03 - Update the DNS records
  hosts: main
  tags:
  - init
  - setup
  - dns
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - include_role: 
      name: "main_vars"
    vars:
      main_vars_env_file: "{{ env_file }}"
      main_vars_platform: "discourse"

  - name: "create the static dns records"
    include_role: 
      name: "main_dns"
    vars: 
      main_dns_title: "create the static dns records - {{ main_item.0.title }}"
      main_dns_task: "{{ main_vars.dns.task }}"
      main_dns_credentials: "{{ main_vars.dns.credentials }}"
      main_dns_zone: "{{ main_vars.dns.zone }}"
      main_dns_type: "{{ main_item.0.type }}"
      main_dns_record: "{{ main_item.1.record }}"
      main_dns_value: "{{ main_item.1.value }}"
    loop: "{{ main_vars.dns.static | subelements('list') }}"
    loop_control:
      loop_var: main_item
      label: "{{ main_item.1.record }}"

###############################################################################

- name: Play 04 - Prepare the hosts
  hosts: discourse
  tags:
  - init
  - prepare
  - prepare-hosts
  gather_facts: no
  tasks:
  - name: Gathering facts
    setup: 

  - include_role: 
      name: "main_vars"
    vars:
      main_vars_env_file: "{{ env_file }}"
      main_vars_platform: "discourse"

  - include_role: 
      name: "discourse"
    vars:
      discourse_title: "discourse - {{ main_item.vars[main_item.role + '_instance_group'] }}"
      discourse_containers: "{{ main_item.vars.containers }}"
      discourse_host_count: "{{ main_item.vars[main_item.role + '_instance_count'] }}"
    loop: "{{ main_vars.cloud.values() | list }}"
    loop_control:
      loop_var: main_item
      label: "{{ main_item.vars[main_item.role + '_instance_group'] }}"

###############################################################################

- name: Play 05 - Build and run
  hosts: discourse
  tags:
  - init
  - build
  - run
  gather_facts: no  
  tasks:
  - name: Gathering facts
    setup: 

  - include_role: 
      name: "main_vars"
    vars:
      main_vars_env_file: "{{ env_file }}"
      main_vars_platform: "discourse"

  - name: '(re)build discourse'
    include_role: 
      name: discourse_run
    vars:
      discourse_run_vars: "{{ main_item.1 }}"
    loop: "{{ main_vars.cloud.values() | subelements('vars.containers') }}"
    loop_control:
      loop_var: main_item
      label: "{{ main_item.1.name }}"

  # - name: '(re)build and (re)start discourse'
  #   include_role: 
  #     name: long_run
  #   vars:
  #     long_run_title: 'discourse - {{ main_item.1.action | default("rebuild") }} {{ main_item.1.name }}'
  #     long_run_become: yes
  #     long_run_output_path: '{{ main_vars.long_run_output_path }}'
  #     long_run_output_file: '{{ main_item.1.name }}.log'
  #     long_run_path: '{{ main_vars.long_run_path }}'
  #     long_run_cmd: './launcher {{ main_item.1.action | default("rebuild") }} {{ main_item.1.name }}'
  #   loop: "{{ main_vars.cloud.values() | subelements('vars.containers') }}"
  #   loop_control:
  #     loop_var: main_item
  #     label: "{{ main_item.1.name }}"

###############################################################################

# - name: Play 08 - Bootstrap the web container
#   hosts: discourse_web
#   tags:
#   - never
#   - build-web
#   - bootstrap-web
#   vars_files: 
#   - "{{ env_file }}"
#   - files/discourse/cloud.yml
#   - files/discourse/settings.yml
#   gather_facts: no  
#   tasks:  
#   - name: Gathering facts
#     setup: 

#   - name: 'bootstrap discourse web container'
#     become: yes
#     include_role: 
#       name: long_run
#     vars:
#       long_run_title: 'bootstrap discourse web container'
#       long_run_become: yes
#       long_run_output_path: '{{ main.env_location }}'
#       long_run_output_file: '{{ main.web_container }}.log'
#       long_run_path: '{{ main.location }}'
#       long_run_cmd: './launcher bootstrap {{ main.web_container }}'

# ###############################################################################

# - name: Play 09 - Restart the web container
#   hosts: discourse_web
#   tags:
#   - never
#   - build-web
#   - restart-web
#   vars_files: 
#   - "{{ env_file }}"
#   - files/discourse/cloud.yml
#   - files/discourse/settings.yml
#   gather_facts: no  
#   tasks:  
#   - name: Gathering facts
#     setup: 

#   - name: 'restart discourse web container'
#     become: yes
#     include_role: 
#       name: long_run
#     vars:
#       long_run_title: 'restart discourse web container - {{ main_item }}'
#       long_run_become: yes
#       long_run_output_path: '{{ main.env_location }}'
#       long_run_output_file: '{{ main.web_container }}.log'
#       long_run_path: '{{ main.location }}'
#       long_run_cmd: './launcher {{ main_item }} {{ main.web_container }}'
#     loop: 
#     - "stop"
#     - "destroy"
#     - "start"
#     loop_control:
#       loop_var: main_item

# ###############################################################################

# - name: Play 10 - Stop Discourse
#   hosts: discourse_web
#   tags:
#   - never
#   - stop
#   vars_files: 
#   - "{{ env_file }}"
#   - files/discourse/cloud.yml
#   - files/discourse/settings.yml
#   gather_facts: no  
#   tasks:  
#   - name: Gathering facts
#     setup: 

#   - name: 'stop discourse containers'
#     become: yes
#     include_role: 
#       name: long_run
#     vars:
#       long_run_title: 'stop discourse containers - {{ main_item }}'
#       long_run_become: yes
#       long_run_output_path: '{{ main.env_location }}'
#       long_run_output_file: '{{ main_item }}.log'
#       long_run_path: '{{ main.location }}'
#       long_run_cmd: './launcher stop {{ main_item }}'
#     loop: "{{ main.containers[::-1] }}"
#     loop_control:
#       loop_var: main_item
