- name: Play 01 - Create droplets and define hosts
  hosts: main
  tags:
  - setup
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
    main_discourse: "{{ main.discourse }}"
    main_host_vars: 
      web:
        host_user: "{{ main.host_user }}"
        host_pass: "{{ main.host_pass }}"
        host_ssh_public_keys: "{{ main.host_ssh_public_keys }}"
    main_aux:  
      web_user_data: "{{ lookup('template', 'templates/setup/user_data.web.j2.sh', template_vars=dict(main_host_vars.web)) | trim }}"
    main_droplet_list:
      - group: "{{ main_discourse.web.group }}"
        main_data: "{{ main_discourse.web }}"
        user_data: "{{ main_aux.web_user_data }}" 

  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - include_role: 
      name: droplets
    vars:
      droplets_hosts_group: "{{ outer_item.group }}"
      droplets_hosts_file: "{{ main.hosts_file }}"
      droplets_api_token: "{{ main.api_token }}"
      droplets_host_user: "{{ main.host_user }}"
      droplets_host_pass: "{{ main.host_pass }}"
      droplets_user_data: "{{ outer_item.user_data }}"
      droplets_info: "{{ outer_item.main_data.info }}"
      droplets_tags: "{{ outer_item.main_data.tags }}"
      droplets_list: "{{ outer_item.main_data.droplets }}"
    with_items:
    - "{{ main_droplet_list }}"
    loop_control:
      loop_var: outer_item
      label: "{{ outer_item.group }}"

###############################################################################

- name: Play 02 - Wait for hosts to be ready
  hosts: host
  tags:
  - setup
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  gather_facts: no
  roles:
  - role: host_test
    vars:
      host_test_log_file: "{{ main.log_file }}"
      host_test_setup_last_line: "{{ main.setup_last_line }}"
      host_test_initial_connection_timeout: "{{ main.initial_connection_timeout }}"
      host_test_setup_finished_timeout: "{{ main.setup_finished_timeout }}"
    
###############################################################################
  
- name: Play 03 - Prepare the configuration file
  hosts: main
  tags:
  - prepare
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: create the directory "{{ main.env_location }}"
    file:
      path: "{{ main.env_location }}"
      state: directory
      mode: 0755

  # - name: configure the discourse app.yml file
  #   template:
  #     src: "templates/discourse/app.yml"
  #     dest: "{{ main.env_location }}/app.yml"
  #     mode: 0700
  #   vars:
  #     hostname: "{{ main.hostname }}"
  #     email: "{{ main.email }}"
  #     smtp_address: "{{ main.smtp_address }}"
  #     smtp_port: "{{ main.smtp_port }}"
  #     smtp_user_name: "{{ main.smtp_user_name }}"
  #     smtp_pass: "{{ main.smtp_pass }}"
  #     ssl_prefix: "{{ main.ssl_prefix }}"
  #     cf_prefix: "{{ main.cf_prefix }}"
  #     ssl_email: "{{ main.ssl_email }}"
  #     cdn_prefix: "{{ main.cdn_prefix }}"
  #     cdn_url: "//{{ main.cdn_host }}"
  #     lang: "{{ main.lang }}"
  #     workers: "{{ main.workers }}"
  #     text_search_config: "{{ main.text_search_config }}"
  #     db_shared_buffers: "{{ main.db_shared_buffers }}"
  #     http_port: "{{ main.http_port }}"
  #     https_port: "{{ main.https_port }}"
  #     host_shared_volume: "{{ main.host_shared_volume }}"
  #     host_log_volume: "{{ main.host_log_volume }}"

  - name: configure the discourse {{ item }}.yml file
    template:
      src: "templates/discourse/{{ item }}.yml"
      dest: "{{ main.env_location }}/{{ item }}.yml"
      mode: 0700
    vars:
      hostname: "{{ main.hostname }}"
      email: "{{ main.email }}"
      smtp_address: "{{ main.smtp_address }}"
      smtp_port: "{{ main.smtp_port }}"
      smtp_user_name: "{{ main.smtp_user_name }}"
      smtp_pass: "{{ main.smtp_pass }}"
      ssl_prefix: "{{ main.ssl_prefix }}"
      cf_prefix: "{{ main.cf_prefix }}"
      ssl_email: "{{ main.ssl_email }}"
      cdn_prefix: "{{ main.cdn_prefix }}"
      cdn_url: "//{{ main.cdn_host }}"
      lang: "{{ main.lang }}"
      workers: "{{ main.workers }}"
      text_search_config: "{{ main.text_search_config }}"
      db_shared_buffers: "{{ main.db_shared_buffers }}"
      http_port: "{{ main.http_port }}"
      https_port: "{{ main.https_port }}"
      host_shared_volume: "/var/discourse/shared/{{ item }}"
      host_log_volume: "/var/discourse/shared/{{ item }}/log/var-log"
      db_pass: "{{ main.db_pass }}"
    loop: "{{ main.containers }}"

###############################################################################

- name: Play 04 - Update the DNS records
  hosts: discourse_web
  tags:
  - prepare
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 
    
  - name: set the discourse hosts vars
    set_fact: 
      main_web_host: "{{ hostvars[groups[main.discourse.web.group][0]] }}"

  - name: update the discourse site DNS A record
    cloudflare_dns:
      zone: "{{ main.hostname }}"
      proxied: "{{ main.discourse.cf_proxied }}"
      type: A
      solo: true
      record: "{{ main.discourse.subdomain }}"
      value: "{{ main_web_host.ansible_host }}"
      account_email: "{{ main.discourse.cloudflare_email }}"
      account_api_token: "{{ main.discourse.cloudflare_token }}"

  - name: update the discourse DNS email records
    cloudflare_dns:
      zone: "{{ main.hostname }}"
      proxied: no
      type: CNAME
      solo: true
      record: "{{ item.host }}"
      value: "{{ item.value }}"
      account_email: "{{ main.discourse.cloudflare_email }}"
      account_api_token: "{{ main.discourse.cloudflare_token }}"
    loop: "{{ main.discourse.smtp_dns }}"
    loop_control:
      label: "{{ item.host }}"

  # - name: update the discourse DNS CDN record
  #   cloudflare_dns:
  #     zone: "{{ main.hostname }}"
  #     proxied: "{{ main.discourse.cdn_proxied }}"
  #     solo: true
  #     type: A
  #     record: "{{ main.discourse.cdn_subdomain }}"
  #     value: "{{ main_web_host.ansible_host }}"
  #     account_email: "{{ main.discourse.cloudflare_email }}"
  #     account_api_token: "{{ main.discourse.cloudflare_token }}"

  # - name: update the discourse DNS CDN record
  #   cloudflare_dns:
  #     zone: "{{ main.hostname }}"
  #     proxied: "{{ main.discourse.cdn_proxied }}"
  #     solo: true
  #     type: CNAME
  #     record: "{{ main.discourse.cdn_subdomain }}"
  #     value: "{{ main.discourse.subdomain }}.{{ main.hostname }}"
  #     account_email: "{{ main.discourse.cloudflare_email }}"
  #     account_api_token: "{{ main.discourse.cloudflare_token }}"

###############################################################################

- name: Play 05 - Prepare the host
  hosts: discourse_web
  tags:
  - prepare
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: prepare the discourse environment
    include_role:
      name: discourse
    vars:
      discourse_env_location: "{{ main.env_location }}"
      discourse_setup_location: "files/discourse"
      discourse_repo: "{{ main.repo }}"
      discourse_location: "{{ main.location }}"
      discourse_user: "{{ main.user }}"
      discourse_group: "{{ main.group }}"
      discourse_items: 
    loop: "{{ main.containers }}"

###############################################################################

- name: Play 06 - Prepare machine
  hosts: discourse_web
  tags:
  - never
  - initial
  - bootstrap
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: create the directory "{{ main.env_location }}"
    file:
      path: "{{ main.env_location }}"
      state: directory
      mode: 0755

  - name: prepare the machine
    become: yes
    shell: "./discourse-custom-setup > {{ main.env_location }}/output.log"
    args:
      chdir: "{{ main.location }}"

###############################################################################

- name: Play 07 - Build and run
  hosts: discourse_web
  tags:
  - never
  - initial
  - build
  - run
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: create the directory "{{ main.env_location }}"
    file:
      path: "{{ main.env_location }}"
      state: directory
      mode: 0755

  - name: set the shell inner command var
    set_fact: 
      inner_cmd_list: []

  - name: set the shell inner command var
    set_fact: 
      inner_cmd_list: "{{ inner_cmd_list + ['./launcher rebuild ' + {{ item }}] }}"
    loop: "{{ main.containers }}"

  - name: set the shell command var
    set_fact: 
      main_cmd: |
        { "{{ inner_cmd_list | join('; ')}}" } > "{{ main.env_location }}/output.log" 2&>1 

  - debug:
      msg: 'main_cmd="{{ main_cmd }}"'

  - name: (re)build and (re)start discourse
    become: yes
    shell: "{{ main_cmd }}"
    args:
      chdir: "{{ main.location }}"
    async: 3600
    poll: 0
    register: 'setup'

  - name: 'Watch {{ main.env_location }}/output.log until the rebuild finishes.'
    become: yes
    include_role:
      name: 'watch'
    vars:
      watch_file: '{{ main.env_location }}/output.log'
      watch_job: 'setup'
      watch_timeout: 3600
      watch_poll: 5

###############################################################################

- name: Play 08 - Bootstrap the web container
  hosts: discourse_web
  tags:
  - never
  - build-web
  - bootstrap-web
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: create the directory "{{ main.env_location }}"
    file:
      path: "{{ main.env_location }}"
      state: directory
      mode: 0755

  - name: bootstrap discourse web container
    become: yes
    shell: "./launcher bootstrap {{ main.web_container }} > {{ main.env_location }}/output.log 2&>1"
    args:
      chdir: "{{ main.location }}"
    async: 3600
    poll: 0
    register: 'setup'

  - name: 'Watch {{ main.env_location }}/output.log until the web bootstrap finishes'
    become: yes
    include_role:
      name: 'watch'
    vars:
      watch_file: '{{ main.env_location }}/output.log'
      watch_job: 'setup'
      watch_timeout: 3600
      watch_poll: 5

###############################################################################

- name: Play 09 - Start the web container
  hosts: discourse_web
  tags:
  - never
  - build-web
  - start-web
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: create the directory "{{ main.env_location }}"
    file:
      path: "{{ main.env_location }}"
      state: directory
      mode: 0755

  - name: start discourse web container
    become: yes
    shell: "./launcher start {{ main.web_container }} > {{ main.env_location }}/output.log 2&>1"
    args:
      chdir: "{{ main.location }}"
    async: 3600
    poll: 0
    register: 'setup'

  - name: 'Watch {{ main.env_location }}/output.log until the web start finishes'
    become: yes
    include_role:
      name: 'watch'
    vars:
      watch_file: '{{ main.env_location }}/output.log'
      watch_job: 'setup'
      watch_timeout: 3600
      watch_poll: 5

###############################################################################

- name: Play 10 - Stop Discourse
  hosts: discourse_web
  tags:
  - never
  - stop
  vars_files: 
  - /home/main/env/env.yml
  vars:
    main: "{{ env.discourse }}"
  gather_facts: no  
  tasks:  
  - name: Gathering facts
    setup: 

  - name: stop discourse
    become: yes
    command: "./launcher stop app"
    args:
      chdir: "{{ main.location }}"
