- name: Play 01 - Define variables
  hosts: main
  tags:
    - setup
  vars_files: 
    - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
    main_host_vars: 
      host_user: "{{ main.host_user }}"
      host_pass: "{{ main.host_pass }}"
      host_ssh_public_key: "{{ main.host_ssh_public_key }}"
    main_aux:  
      web_user_data: "{{ lookup('template', 'data/user_data.web.j2', template_vars=dict(main_host_vars)) | trim }}"
      db_user_data: "{{ lookup('template', 'data/user_data.db.j2', template_vars=dict(main_host_vars)) | trim }}"
    main_droplet_info_list: []  

  pre_tasks:
  - name: define main droplet info list
    set_fact: 
      main_droplet_info_list[{{item.0}}]:
        hosts_group: "{{ item.1.group }}"
        hosts_file: "{{ main.hosts_file }}"
        api_token: "{{ main.api_token }}"
        host_user: "{{ main.host_user }}"
        host_pass: "{{ main.host_pass }}"
        droplet_info:
          image_id: "{{ main.web_droplet_info.image_id }}"
          size_id: "{{ main.web_droplet_info.size_id }}"
          private_networking: "{{ main.web_droplet_info.private_networking }}"
          ipv6: "{{ main.web_droplet_info.ipv6 }}"
          wait_timeout: "{{ main.web_droplet_info.wait_timeout }}"
          user_data: "{{ item.1.user_data }}"
        do_tags: "{{ main.web_tags }}"
        droplets: "{{ main.web_droplets }}"
    with_indexed_items:
    - { group: "db_master", user_data: "{{ main_aux.db_user_data }}" }
    - { group: "db_replica", user_data: "{{ main_aux.db_user_data }}" }
    - { group: "web", user_data: "{{ main_aux.web_user_data }}" }
    loop_control:
      label: "{{ item.1.group }}"

  roles:  
  - role: droplets
    vars:
      droplets_hosts_file: "{{ item.hosts_file }}"
      droplets_api_token: "{{ item.api_token }}"
      droplets_host_user: "{{ item.host_user }}"
      droplets_host_pass: "{{ item.host_pass }}"
      droplets_hosts_group: "{{ item.hosts_group }}"
      droplets_info: "{{ item.droplet_info }}"
      droplets_tags: "{{ item.do_tags }}"
      droplets_list: "{{ item.droplets }}"
    with_items:
    - "{{ main_droplet_info_list }}"

###############################################################################

- name: Play 02 - Wait for hosts to be ready
  hosts: host
  tags:
    - setup
  vars_files: 
    - /home/main/env/env.yml
  vars:
    main: "{{ env }}"
  gather_facts: no
  roles:
  - role: host_test
    vars:
      host_test_log_file: "{{ main.log_file }}"
      host_test_setup_last_line: "{{ main.setup_last_line }}"
      host_test_initial_connection_timeout: "{{ main.initial_connection_timeout }}"
      host_test_setup_finished_timeout: "{{ main.setup_finished_timeout }}"

###############################################################################
