- name: "{{ main_cloud_title }} - set_fact - main"
  set_fact: 
    main_cloud_role: "{{ main_cloud_var.type }}"
    main_cloud_aux:
      ssh_encrypted_key_path: >-
        {{ 
        main_cloud_instance_params.ssh_encrypted_key_path_rel | default('') | 
        ternary(env_dir + '/' + 
        (main_cloud_instance_params.ssh_encrypted_key_path_rel | default('')), '') 
        }}
      ssh_key_path: >-
        {{ 
        main_cloud_instance_params.ssh_encrypted_key_path_rel | 
        ternary(main_cloud_tmp_dir + '/' + main_cloud_node_id + '.key', '')
        }}
  tags: ["no_print"]

- name: "{{ main_cloud_title }} - set_fact - inner vars"
  set_fact: 
    main_cloud_inner_vars:
      title: "{{ main_cloud_node_id }} - {{ main_cloud_node_params.region }}"
      hosts_file: "{{ main_cloud_hosts_file }}"
      api_token: "{{ main_cloud_var.api_token }}"
      all_tags: "{{ main_cloud_params.tags | default([]) }}"
      all_firewalls: "{{ main_cloud_params.firewalls | default([]) }}"
      instance_name: "{{ main_cloud_env_name }}-{{ main_cloud_node_id }}"
      instance_type: "{{ main_cloud_node_id }}"
      region: "{{ main_cloud_node_params.region }}"
      instance_size: "{{ main_cloud_node_params.size }}"
      instance_image: "{{ main_cloud_instance_params.image }}"
      instance_count: "{{ main_cloud_node.amount }}"
      instance_max: "{{ main_cloud_node.amount_to_check }}"
      user_data_file: "{{ main_cloud_instance_params.user_data_file | default('') }}"
      ipv6: "{{ main_cloud_instance_params.ipv6 }}"
      host_user: "{{ main_cloud_instance_params.host_user }}"
      host_pass: "{{ main_cloud_instance_params.host_pass }}"
      ssh_public_keys: "{{ main_cloud_instance_params.host_ssh_public_keys }}"
      ssh_encrypted_key_path: "{{ main_cloud_aux.ssh_encrypted_key_path }}"
      ssh_key_path: "{{ main_cloud_aux.ssh_key_path }}"
      tags: "{{ main_cloud_node_params.tags }}"
      instance_tmp: "{{ main_cloud_node.tmp | default(false) }}"
      tmp_dir: "{{ main_cloud_tmp_dir }}"
      shutdown: "{{ main_cloud_shutdown | default(false) }}"
  tags: ["no_print"]

- name: "{{ main_cloud_title }} - set_fact"
  set_fact: { "{{ main_cloud_item_key }}": "{{ main_cloud_item_value }}" }
  vars:
    main_cloud_item_key: "{{ main_cloud_role + '_' + main_cloud_item.key }}"
    main_cloud_item_value: "{{ main_cloud_item.value }}"
  loop: "{{ main_cloud_inner_vars | dict2items }}"
  loop_control:
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.key }}"
  tags: ["no_print"]

- name: "{{ main_cloud_title }} - execute role {{ main_cloud_role }}"
  include_role: 
    name: '{{ main_cloud_role }}'

# main_cloud_role + '_active_hosts' has the hosts created by the role
- set_fact: 
    main_cloud_active_hosts: "{{ lookup('vars', main_cloud_role + '_active_hosts') }}"
    main_cloud_hosts_info: ""
    main_cloud_unencrypt_key: >-
      {{
      ((main_cloud_aux.ssh_encrypted_key_path | default('', true)) != '') 
      and 
      ((main_cloud_aux.ssh_key_path | default('', true)) != '')
      }}

- name: >-
    {{ main_cloud_title }} - create unencrypted key file dir - 
    {{ main_cloud_aux.ssh_key_path | dirname }}
  file:
    path: "{{ main_cloud_aux.ssh_key_path | dirname }}"
    state: directory
    mode: 0755
  when: (main_cloud_unencrypt_key | bool)

- name: "{{ main_cloud_title }} - generate unencrypted key file - {{ main_cloud_aux.ssh_key_path }}"
  copy:
    src: "{{ main_cloud_aux.ssh_encrypted_key_path }}"
    dest: "{{ main_cloud_aux.ssh_key_path }}"
    decrypt: yes
    mode: 0600
  when: main_cloud_unencrypt_key | bool

- name: "{{ main_cloud_title }} - generate the hosts information with the instances ips"
  set_fact: 
    main_cloud_hosts_info: >-
      {{ main_cloud_hosts_info | default('') }}

      {{ main_cloud_item.name }}
      ansible_host={{ main_cloud_item.public_ipv4 }}
      ansible_user={{ main_cloud_instance_params.host_user }}
      {{ 
      main_cloud_instance_params.host_pass | 
      ternary('ansible_become_pass=' + main_cloud_instance_params.host_pass, '') 
      }}
      {{ 
      main_cloud_aux.ssh_key_path | 
      ternary('ansible_ssh_private_key_file=' + main_cloud_aux.ssh_key_path, '') 
      }}
      instance_type={{ main_cloud_node_id }}
      instance_index={{ main_cloud_index }}
      ansible_host_service={{ 
      main_cloud_node.dmz | default(false) | bool | 
      ternary(main_cloud_item.public_ipv4, main_cloud_item.private_ip) 
      }}
  loop: "{{ main_cloud_active_hosts | list }}"
  loop_control:
    index_var: main_cloud_index
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.name }}"

- name: '{{ main_cloud_title }} - Update the hosts file with the generated hosts'
  blockinfile:
    path: "{{ main_cloud_hosts_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ main_cloud_node_id }}"
    insertafter: "\\[{{ main_cloud_node_id }}\\]"
    block: "{{ main_cloud_hosts_info }}"
  tags: ["print_action"]

- name: '{{ main_cloud_title }} - refresh inventory'
  meta: refresh_inventory
  tags: ["print_action"]

- name: "create the main dns record (IPv6) point to the instance when in the dmz layer"
  include_role: 
    name: "cloud_dns"
  vars: 
    cloud_dns_title: "{{ main_cloud_title }} - main dns - IPv6"
    cloud_dns_type: "{{ main_cloud_dns_dict[main_cloud_item.name].type }}"
    cloud_dns_credentials: "{{ main_cloud_dns_dict[main_cloud_item.name].credentials }}"
    cloud_dns_zone: "{{ main_cloud_dns_dict[main_cloud_item.name].zone }}"
    cloud_dns_type: "AAAA"
    cloud_dns_record: "{{ main_cloud_item.record }}"
    cloud_dns_value: "{{ main_cloud_active_hosts[0].public_ipv6 }}"
  loop: "{{ (main_cloud_node.dns | default([])) | list }}"
  loop_control:
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.name }}"
  when: >-
    (main_cloud_dns_dict[main_cloud_item.name] is defined) and
    (main_cloud_dns_dict[main_cloud_item.name].task is defined) and
    (main_cloud_active_hosts | length == 1) and 
    (main_cloud_node.dmz | bool) and 
    (main_cloud_active_hosts[0].public_ipv6 is defined)
  tags: ["print_action"]

- name: "create the main dns record (IPv4) point to the instance when in the dmz layer"
  include_role: 
    name: "cloud_dns"
  vars: 
    cloud_dns_title: "{{ main_cloud_title }} - main dns - IPv4"
    cloud_dns_task: "{{ main_cloud_dns_dict[main_cloud_item.name].type }}"
    cloud_dns_credentials: "{{ main_cloud_dns_dict[main_cloud_item.name].credentials }}"
    cloud_dns_zone: "{{ main_cloud_dns_dict[main_cloud_item.name].zone }}"
    cloud_dns_type: "A"
    cloud_dns_record: "{{ main_cloud_item.record }}"
    cloud_dns_value: "{{ main_cloud_active_hosts[0].public_ipv4 }}"
  loop: "{{ (main_cloud_node.dns | default([])) | list }}"
  loop_control:
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.name }}"
  when: >-
    (main_cloud_dns_dict[main_cloud_item.name] is defined) and
    (main_cloud_dns_dict[main_cloud_item.name].task is defined) and
    (main_cloud_active_hosts | length == 1) and 
    (main_cloud_node.dmz | bool) and 
    (main_cloud_active_hosts[0].public_ipv4 is defined)
  tags: ["print_action"]
    