- set_fact: { "main_cloud_{{ main_cloud_item }}": "{{ main_cloud_vars[main_cloud_role + '_' + main_cloud_item] }}" }
  loop: 
  - "instance_type"
  - "title"
  - "hosts_file"
  - "host_user"
  - "host_pass"
  - "instance_group"
  loop_control:
    loop_var: main_cloud_item

- set_fact: { "{{ main_cloud_item.key }}": "{{ main_cloud_item.value }}" }
  loop: "{{ main_cloud_vars | dict2items }}"
  loop_control:
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.key }}"

- set_fact: { "{{ main_cloud_role }}_shutdown": "{{ main_cloud_shutdown | default(false) }}" }

- name: '{{ main_cloud_title }} - execute role {{ main_cloud_role }}'
  include_role: 
    name: '{{ main_cloud_role }}'

- set_fact: 
    main_cloud_active_hosts: "{{ lookup('vars', main_cloud_role + '_active_hosts') }}"
    main_cloud_hosts_info: ""

- name: '{{ main_cloud_title }} - generate the hosts information with the instances ips'
  set_fact: 
    main_cloud_hosts_info: |
      {{ main_cloud_hosts_info | default('') }}
      {{ main_cloud_item.name }} ansible_host={{ main_cloud_extra.dmz | ternary(main_cloud_item.public_ip, main_cloud_item.private_ip) }} ansible_user={{ main_cloud_host_user }} ansible_become_pass={{ main_cloud_host_pass }} instance_type={{ main_cloud_instance_type }}
  loop: "{{ main_cloud_active_hosts | list }}"
  loop_control:
    loop_var: main_cloud_item
    label: "{{ main_cloud_item.name }}"

- name: '{{ main_cloud_title }} - Update the hosts file with the generated hosts'
  blockinfile:
    path: "{{ main_cloud_vars[main_cloud_role + '_hosts_file'] }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ main_cloud_instance_group }}"
    insertafter: "\\[{{ main_cloud_instance_group }}\\]"
    block: "{{ main_cloud_hosts_info }}"

- name: '{{ main_cloud_title }} - refresh inventory'
  meta: refresh_inventory

- debug:
    var: main_cloud_dns

- name: "create the main dns record point to the instance when in the dmz layer"
  include_role: 
    name: "main_dns"
  vars: 
    main_dns_title: "{{ main_cloud_title }} - main dns"
    main_dns_task: "{{ main_cloud_dns.task }}"
    main_dns_credentials: "{{ main_cloud_dns.credentials }}"
    main_dns_zone: "{{ main_cloud_dns.zone }}"
    main_dns_type: "A"
    main_dns_record: "{{ main_cloud_dns.main_record }}"
    main_dns_value: "{{ main_cloud_active_hosts[0].public_ip }}"
  when: (main_cloud_active_hosts | length == 1) and main_cloud_extra.dmz
