- name: "{{ cloud_main_title }} - generate cloud params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ cloud_main_cloud.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_main_cloud.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_main_cloud.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_main_cloud.shared_group_params | default('') }}"
    params_mixer_shared_params_names_dict: "{{ cloud_main_cloud_shared_params_dict | default({}) }}"
    params_mixer_shared_group_params_names_dict: "{{ cloud_main_cloud_shared_group_params_dict | default({}) }}"
    params_mixer_params_dict: "{{ cloud_main_cloud_params_dict | default({}) }}"

- set_fact:
    cloud_main_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_main_title }} - prepare the cloud"
  include_tasks: "ext/{{ cloud_main_cloud.type }}.main.yml"
  vars:
    cloud_main_inner_title: "{{ cloud_main_title }} - {{ cloud_main_cloud.type }}"
    cloud_main_inner_api_token: "{{ cloud_main_credentials.api_token }}"
    cloud_main_inner_params: "{{ cloud_main_params }}"
    cloud_main_inner_tmp_dir: "{{ cloud_main_tmp_dir }}"
  when: cloud_main_cloud.type != 'local'