- name: "discourse - {{ discourse_container_name }} - initial vars"
  set_fact: 
    discourse_container_vars: "{{ discourse_container_vars | default({}) }}"

# - name: "discourse - {{ discourse_container_name }} - debug"
#   debug:
#     msg: "{{ discourse_container_index }} - {{ discourse_container_item.count }} - {{ discourse_max_host_count }} - {{ discourse_container_index * discourse_container_item.count / discourse_max_host_count) | int }}"
#   loop: "{{ discourse_container_dynamic_host_vars }}"
#   loop_control:
#     loop_var: discourse_container_item

- name: "discourse - {{ discourse_container_name }} - dynamic vars"
  set_fact: { "discourse_container_vars[{{ discourse_container_item.name }}]": "{{ hostvars[groups[discourse_container_item.group][(discourse_container_index * discourse_container_item.count / discourse_max_host_count) | int]] }}" }
  loop: "{{ discourse_container_dynamic_host_vars }}"
  loop_control:
    loop_var: discourse_container_item
    label: "{{ discourse_container_item.name }}"

- name: "discourse - {{ discourse_container_name }} - all vars"
  set_fact: { "discourse_var_{{ discourse_container_item.key }}": "{{ discourse_container_item.value }}" }
  loop: "{{ discourse_container_vars | dict2items }}"
  loop_control:
    loop_var: discourse_container_item
    label: "{{ discourse_container_item.key }}"

- name: "discourse - {{ discourse_container_name }} - transfer template file"
  become: yes
  template: 
    src: "{{ discourse_templates_containers_path }}/{{ discourse_container_name }}.yml"
    dest: "{{ discourse_location }}/containers/{{ discourse_container_name }}.yml"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0600
  vars:
    base_image: "{{ discourse_var_base_image | default('') }}"
    hostname: "{{ discourse_var_hostname | default('') }}"
    email: "{{ discourse_var_email | default('') }}"
    smtp_address: "{{ discourse_var_smtp_address | default('') }}"
    smtp_port: "{{ discourse_var_smtp_port | default('') }}"
    smtp_user_name: "{{ discourse_var_smtp_user_name | default('') }}"
    smtp_pass: "{{ discourse_var_smtp_pass | default('') }}"
    use_ssl: "{{ discourse_var_use_ssl | default(false | bool) }}"
    use_cf: "{{ discourse_var_use_cf | default(false | bool) }}"
    ssl_email: "{{ discourse_var_ssl_email | default('') }}"
    use_cdn: "{{ discourse_var_use_cdn | default(false | bool) }}"
    cdn_url: "//{{ discourse_var_cdn_url | default('') }}"
    lang: "{{ discourse_var_lang | default('') }}"
    workers: "{{ discourse_var_workers | default('') }}"
    text_search_config: "{{ discourse_var_text_search_config | default('') }}"
    db_shared_buffers: "{{ discourse_var_db_shared_buffers | default('') }}"
    http_port: "{{ discourse_var_http_port | default('') }}"
    https_port: "{{ discourse_var_https_port | default('') }}"
    db_pass: "{{ discourse_var_db_pass | default('') }}"
    db_host: "{{ discourse_var_db_host | default('') }}"
    redis_host: "{{ discourse_var_redis_host | default('') }}"

    enable_s3_uploads: "{{ discourse_var_enable_s3_uploads | default('') }}"
    s3_access_key_id: "{{ discourse_var_s3_access_key_id | default('') }}"
    s3_secret_access_key: "{{ discourse_var_s3_secret_access_key | default('') }}"
    s3_region: "{{ discourse_var_s3_region | default('') }}"
    s3_upload_bucket: "{{ discourse_var_s3_upload_bucket | default('') }}"
    s3_endpoint: "{{ discourse_var_s3_endpoint | default('') }}"
    s3_cdn_url: "{{ discourse_var_s3_cdn_url | default('') }}"
    force_https: "{{ discourse_var_force_https | default('') }}"
    enable_backups: "{{ discourse_var_enable_backups | default('') }}"
    backup_location: "{{ discourse_var_backup_location | default('') }}"
    maximum_backups: "{{ discourse_var_maximum_backups | default('') }}"
    backup_frequency: "{{ discourse_var_backup_frequency | default('') }}"
    s3_backup_bucket: "{{ discourse_var_s3_backup_bucket | default('') }}"