- name: "{{ discourse_title }} - ensure docker is running"
  become: yes
  service: 
    name: docker
    state: started

- name: "{{ discourse_title }} - download docker git repo"
  become: yes
  git:
    repo: "{{ discourse_docker_repo }}"
    version: "{{ discourse_version }}"
    dest: "{{ discourse_location }}"
    update: yes
   
- name: "{{ discourse_title }} - copy discourse setup file"
  become: yes
  copy: 
    src: "{{ discourse_setup_location }}/setup.sh"
    dest: "{{ discourse_location }}/discourse-custom-setup"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755
 
- name: "{{ discourse_title }} - copy discourse configuration .yml file(s) setting the parameters"
  include_tasks: 'container.yml'
  vars:
    discourse_container_name: "{{ discourse_item.name }}"
    discourse_container_vars: "{{ discourse_item.vars | default({}) }}"
    discourse_container_dynamic_host_vars: "{{ discourse_item.dynamic_host_vars | default([]) }}"
    discourse_container_index: "{{ discourse_index }}"
    discourse_container_host_count: "{{ discourse_host_count }}"
  loop: "{{ discourse_containers | flatten(levels=1) }}"
  loop_control:
    index_var: discourse_index
    loop_var: "discourse_item"

- name: "{{ discourse_title }} - prepare the machine (setup)"
  become: yes
  include_role: 
    name: long_run
  vars:
    long_run_title: '{{ discourse_title }} - prepare the machine (setup)'
    long_run_become: "{{ discourse_setup_become }}"
    long_run_output_path: "{{ discourse_setup_output_path }}"
    long_run_output_file: "{{ discourse_setup_output_file }}"
    long_run_path: "{{ discourse_location }}"
    long_run_cmd: "{{ discourse_setup_cmd }}"