- name: "{{ discourse_title }} - ensure docker is running"
  become: yes
  service: 
    name: docker
    state: started

- name: "{{ discourse_title }} - download docker git repo"
  become: yes
  git:
    repo: "{{ discourse_docker_repo }}"
    version: "{{ discourse_docker_version }}"
    dest: "{{ discourse_location }}"
    update: yes
  tags: ["print_action"]
    
- name: "{{ discourse_title }} - set_fact"
  set_fact: 
    discourse_setup_file_path: >-
      {{ discourse_location }}/{{ discourse_setup_file }}
    discourse_setup_tmp_file_path: >-
      {{ discourse_setup_tmp_file_dir }}/{{ discourse_setup_file }}

- name: >-
    {{ discourse_title }} - create the temporary directory 
    '{{ discourse_setup_tmp_file_dir }}'
  become: yes
  file:
    path: "{{ discourse_setup_tmp_file_dir }}"
    state: directory
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0700

- name: >-
    {{ discourse_title }} - create empty setup file into temporary directory
    if there is no file there
  become: yes
  copy: 
    force: no
    content: ""
    dest: "{{ discourse_setup_tmp_file_path }}"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0600
   
- name: "{{ discourse_title }} - copy discourse setup file"
  become: yes
  copy: 
    src: "{{ discourse_setup_location }}/setup.sh"
    dest: "{{ discourse_setup_file_path }}"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755
   
- name: "{{ discourse_title }} - copy the discourse templates files"
  become: yes
  copy: 
    src: "{{ discourse_templates_location }}/{{ discourse_item }}"
    dest: "{{ discourse_location }}/templates/{{ discourse_item }}"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755
  loop: 
  - "web.template.validate.yml"
  - "web.template.build.yml"
  - "web.template.run.yml"
  loop_control:
    loop_var: "discourse_item"

- name: >-
    {{ discourse_title }} -
    copy discourse configuration .yml file(s) defining the parameters
  include_tasks: 'container.yml'
  vars:
    discourse_container_name: "{{ discourse_item.name }}"
    discourse_container_vars: "{{ discourse_item.vars | default({}) }}"
    discourse_container_dynamic_host_vars: >
      {{ discourse_item.dynamic_host_vars | default([]) }}
    discourse_container_index: "{{ discourse_index }}"
    discourse_container_instance_max: "{{ discourse_instance_max }}"
    discourse_container_docker_git_repo: "{{ discourse_docker_repo }}"
    discourse_container_docker_git_repo_version: "{{ discourse_docker_version }}"
  loop: "{{ discourse_containers | flatten(levels=1) }}"
  loop_control:
    loop_var: "discourse_item"
  when: not (discourse_item.skip | default(false) | bool)

- name: "{{ discourse_title }} - get the difference of two files (old and current)"
  become: yes
  command: "diff {{ discourse_setup_file_path }} {{ discourse_setup_tmp_file_path }}"
  register: discourse_diff
  failed_when: discourse_diff.rc > 1
  changed_when: discourse_diff.rc == 1

- name: "{{ discourse_title }} - prepare the machine (setup)"
  include_role: 
    name: long_run
  vars:
    long_run_title: '{{ discourse_title }} - prepare the machine (setup)'
    long_run_become: "{{ discourse_setup_become }}"
    long_run_output_path: "{{ discourse_setup_output_path }}"
    long_run_output_file: "{{ discourse_setup_output_file }}"
    long_run_path: "{{ discourse_location }}"
    long_run_cmd: "{{ discourse_setup_cmd }}"
  when: "discourse_diff.changed" 
   
- name: "{{ discourse_title }} - backup the discourse setup file"
  become: yes
  copy: 
    remote_src: yes
    src: "{{ discourse_setup_file_path }}"
    dest: "{{ discourse_setup_tmp_file_path }}"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755