- name: ensure docker is running
  become: yes
  service: 
    name: docker
    state: restarted

- name: download docker git repo
  become: yes
  git:
    repo: "{{ discourse_docker_repo }}"
    version: "{{ discourse_version }}"
    dest: "{{ discourse_location }}"
    update: yes
   
- name: copy discourse setup file
  become: yes
  copy: 
    src: "{{ discourse_setup_location }}/setup.sh"
    dest: "{{ discourse_location }}/discourse-custom-setup"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755
 
- name: copy discourse configuration .yml file(s) setting the parameters
  include_tasks: 'container.yml'
  vars:
    discourse_container_name: "{{ discourse_item.name }}"
    discourse_container_dynamic_host_vars: "{{ discourse_item.dynamic_host_vars | default([]) }}"
    discourse_container_index: "{{ discourse_index }}"
    discourse_container_host_count: "{{ discourse_host_count }}"
  loop: "{{ discourse_containers | flatten(levels=1) }}"
  loop_control:
    index_var: discourse_index
    loop_var: "discourse_item"
