- name: ensure docker is running
  become: yes
  service: 
    name: docker
    state: restarted

- name: download git repo
  become: yes
  git:
    repo: "{{ discourse_repo }}"
    dest: "{{ discourse_location }}"
    update: no

- name: copy discourse setup file
  become: yes
  copy: 
    src: "{{ discourse_setup_location }}/setup.sh"
    dest: "{{ discourse_location }}/discourse-custom-setup"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0755

- name: copy discourse configuration app.yml
  become: yes
  copy: 
    src: "{{ discourse_env_location }}/app.yml"
    dest: "{{ discourse_location }}/containers/app.yml"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"
    mode: 0600