- name: ensure docker is running
  become: yes
  service: 
    name: docker
    state: restarted

- name: download git repo
  become: yes
  git:
    repo: "{{ discourse_repo }}"
    dest: "{{ discourse_location }}"
    update: no

- name: copy discourse configuration app.yml
  become: yes
  copy: 
    src: "{{ discourse_env_location }}/app.yml "
    dest: "{{ discourse_location }}/containers/app.yml"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"

- name: fix discourse permissions
  become: yes
  file: 
    path: "{{ discourse_location }}"
    owner: "{{ discourse_user }}"
    group: "{{ discourse_group }}"