- name: compose run
  include_role: 
    name: compose_run
  vars:
    compose_run_context: "{{ main_item }}"
    compose_run_base_dir: "{{ main_vars.base_dir }}/{{ main_item.name | default('') }}"
    compose_run_file_env_vars_relative_src: >-
      {{ main_vars.prepare.file_env_vars_relative }}
    compose_run_file_env_vars_relative_dest: >-
      {{ main_vars.run.file_env_vars_relative }}
    compose_run_docker_become: "{{ main_vars.run.docker_become }}"
    compose_run_host_user: "{{ env.cloud_host_user }}"
    compose_run_host_group: "{{ env.cloud_host_user }}"
    compose_run_env_cmd: "{{ env_cmd | default('') }}"
    # compose_run_index: "{{ instance_index }}"
    # compose_run_instance_max: "{{ main_item.vars.cloud.instance_max }}"
    # compose_run_cloud: "{{ main_vars.cloud }}"
  loop: "{{ main_vars.prepare.contexts | default([]) | list }}"
  loop_control:
    loop_var: main_item
    label: "{{ main_item.group }} - {{ main_item.name }}"
  when: main_item.group == instance_type