- name: "{{ repo_title }} - repo_dir_dev"
  set_fact:
    repo_dir_dev: "{{ (repo_dev | bool) and ((repo_dev_path | default('')) != '') }}"
  tags: ["no_print"]

- name: "{{ repo_title }} - repo_dir"
  set_fact:
    repo_dir: >-
      {{
        repo_dir_dev | bool
        | ternary(
          repo_dev_base_dir + '/' + (repo_dev_path | default('')),
          repo_default_dir
        )
      }}
  tags: ["no_print"]

- name: >-
    {{ repo_title }} - create the default base directory
    ({{ repo_default_dir | dirname }})
  file:
    path: "{{ repo_default_dir | dirname }}"
    state: directory
    mode: "{{ repo_dev | bool | ternary(0777, 0755) }}"
  when: repo_dir != repo_default_dir

- name: "{{ repo_title }} - git (outer)"
  include_tasks: "git.yml"
  vars:
    git_title: "{{ repo_title }} - git"
    git_repo: "{{ repo_main }}"
    git_ssh_src_dir: "{{ repo_ssh_src_dir }}"
    git_secrets_dir: "{{ repo_secrets_dir }}"
    git_repo_dir: "{{ repo_dir }}"
    git_update: "{{ not (repo_dir_dev | bool) }}"
    git_dev: "{{ repo_dev }}"
  tags: ["no_print"]

- name: "{{ repo_title }} - git_result"
  set_fact:
    repo_git_result: "{{ git_result }}"
  tags: ["no_print"]

- name: "{{ repo_title }} - create symbolic link"
  file:
    src: "{{ repo_dir | relpath(repo_default_dir | dirname) }}"
    dest: "{{ repo_default_dir }}"
    state: link
  when: repo_dir != repo_default_dir
