- name: "{{ wordpress_title }} - verify if docker compose file is defined"
  fail:
    msg: "[Error] Specify the environment repo variable: docker_compose_file"
  when: (wordpress_docker_compose_file is not defined) or (wordpress_docker_compose_file == '')

- name: "{{ wordpress_title }} - verify if the temporary dir is specified"
  fail:
    msg: "The parameter wordpress_local_tmp_dir must be specified"
  when: (wordpress_local_tmp_dir is not defined) or (wordpress_local_tmp_dir == '')

- name: "{{ wordpress_title }} - ensure docker is running"
  become: yes
  service: 
    name: docker
    state: started

- name: "{{ wordpress_title }} - copy the docker compose executable file"
  become: yes
  copy: 
    src: "roles/wordpress/files/docker-compose.sh"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

- name: "{{ wordpress_title }} - create the repo directories"
  become: yes
  file:
    path: "{{ wordpress_item }}"
    state: directory
    mode: 0700
  loop:
  - "{{ wordpress_repo_location }}"
  - "{{ wordpress_repo_location_tmp }}"
  - "{{ wordpress_env_location_backup }}"
  loop_control:
    loop_var: wordpress_item

- name: "{{ wordpress_title }} - update the temporary repo directory"
  become: yes
  git:
    repo: "{{ wordpress_docker_repo }}"
    version: "{{ wordpress_docker_repo_version }}"
    dest: "{{ wordpress_repo_location_tmp }}"
    update: yes
  register: wordpress_git_result
  tags: ["print_action"]

- set_fact:
    wordpress_git_commit: "{{ wordpress_git_result.after }}"

- name: "{{ wordpress_title }} - fetch template from single remote host"
  run_once: true
  fetch:
    src: "{{ wordpress_repo_location_tmp }}/templates/.env"
    dest: "{{ wordpress_local_tmp_dir }}/.env"
    flat: yes
    fail_on_missing: yes

- name: "{{ wordpress_title }} - transfer the env template file"
  become: yes
  template: 
    src: "{{ wordpress_local_tmp_dir }}/.env"
    dest: "{{ wordpress_repo_location_tmp }}/.env"
    mode: 0600

- name: >-
    {{ wordpress_title }} - create empty env file in backup directory
    if there is no file there
  become: yes
  copy: 
    force: no
    content: ""
    dest: "{{ wordpress_env_location_backup }}/.env"
    mode: 0600

- name: "{{ wordpress_title }} - get the difference of the 2 env files (old and current)"
  become: yes
  command: >-
    diff {{ wordpress_repo_location_tmp }}/.env {{ wordpress_env_location_backup }}/.env
  register: wordpress_diff
  failed_when: wordpress_diff.rc > 1
  changed_when: wordpress_diff.rc == 1
  tags: ["print_action"]

- block:

  - set_fact:
      wordpress_docker_compose_cmd: "docker-compose -f {{ wordpress_docker_compose_file }}"

  - name: "{{ wordpress_title }} - prepare the temporary images (pull and build)"
    become: yes
    command: "{{ wordpress_item }}"
    args:
      chdir: "{{ wordpress_repo_location_tmp }}/"
    loop:
    - "{{ wordpress_docker_compose_cmd }} pull"
    - "{{ wordpress_docker_compose_cmd }} build --pull"
    loop_control:
      loop_var: wordpress_item
    tags: ["print_action"]

  - name: "{{ wordpress_title }} - update the repo directory"
    become: yes
    git:
      repo: "{{ wordpress_docker_repo }}"
      version: "{{ wordpress_docker_repo_version }}"
      dest: "{{ wordpress_repo_location }}"
      update: yes
    tags: ["print_action"]

  - name: "{{ wordpress_title }} - copy the env file"
    become: yes
    copy: 
      remote_src: yes
      src: "{{ wordpress_repo_location_tmp }}/.env"
      dest: "{{ wordpress_repo_location }}/.env"
      mode: 0600

  - name: "{{ wordpress_title }} - prepare the images (build)"
    become: yes
    command: "{{ wordpress_docker_compose_cmd }} build"
    args:
      chdir: "{{ wordpress_repo_location }}/"
    tags: ["print_action"]
    
  - name: "{{ wordpress_title }} - backup the wordpress env file"
    become: yes
    copy: 
      remote_src: yes
      src: "{{ wordpress_repo_location }}/.env"
      dest: "{{ wordpress_env_location_backup }}/.env"
      mode: 0600

  when: "wordpress_diff.changed" 