- name: "{{ main_do_title }} - create firewalls"
  digital_ocean_firewall:
    name: "{{ main_do_item.name }}"
    state: "present"
    droplet_ids: "{{ main_do_item.droplet_ids | default([]) }}"
    tags: "{{ main_do_item.tags | default([]) }}"
    inbound_rules:
      protocol: "{{ (main_do_item.inbound_rules | default({})).protocol | default('tcp') }}"
      ports: "{{ (main_do_item.inbound_rules | default({})).ports | default([]) }}"
      sources:
        addresses: "{{ (((main_do_item.inbound_rules | default({})).sources | default({})).addresses | default([]) }}"
        droplet_ids: "{{ (((main_do_item.inbound_rules | default({})).sources | default({})).droplet_ids | default([]) }}"
        load_balancer_uids: "{{ (((main_do_item.inbound_rules | default({})).sources | default({})).load_balancer_uids | default([]) }}"
        tags: "{{ (((main_do_item.inbound_rules | default({})).sources | default({})).tags | default([]) }}"
    outbound_rules:
      protocol: "{{ (main_do_item.outbound_rules | default({})).protocol | default('tcp') }}"
      ports: "{{ (main_do_item.outbound_rules | default({})).ports | default([]) }}"
      destinations:
        addresses: "{{ (((main_do_item.outbound_rules | default({})).destinations | default({})).addresses | default([]) }}"
        droplet_ids: "{{ (((main_do_item.outbound_rules | default({})).destinations | default({})).droplet_ids | default([]) }}"
        load_balancer_uids: "{{ (((main_do_item.outbound_rules | default({})).destinations | default({})).load_balancer_uids | default([]) }}"
        tags: "{{ (((main_do_item.outbound_rules | default({})).destinations | default({})).tags | default([]) }}"
  loop: "{{ main_do_tags_details | default([]) }}"
  loop_control:
    loop_var: main_do_item
    label: "{{ main_do_item.name }}"

- set_fact:
    main_do_cloud_instances: []

- name: '{{ main_do_title }} - define instances to be created'
  set_fact:
    main_do_cloud_instances: "{{ main_do_cloud_instances + [{ 'name': main_do_instance_name + '-' + main_do_region + '-' + ('%03d'  | format(main_do_item)), 'region_id': main_do_region, 'state': ((main_do_item | int) <= (main_do_instance_count | int)) | ternary('present', 'deleted') }] }}"
  loop: "{{ range(1, (main_do_instance_max | int) + 1) | list }}"
  loop_control:
    loop_var: main_do_item

- name: '{{ main_do_title }} - create droplets'
  include_role: 
    name: droplets
  vars:
    droplets_title: "{{ main_do_title }} - create droplets - {{ main_do_instance_group }}"
    droplets_hosts_group: "{{ main_do_instance_group }}"
    droplets_hosts_file: "{{ main_do_hosts_file }}"
    droplets_instance_type: "{{ main_do_instance_type }}"
    droplets_api_token: "{{ main_do_api_token }}"
    droplets_host_user: "{{ main_do_host_user }}"
    droplets_host_pass: "{{ main_do_host_pass }}"
    droplets_user_data: "{{ main_do_user_data }}"
    droplets_size_id: "{{ main_do_size_id }}"
    droplets_image_id: "{{ main_do_image_id }}"
    droplets_private_networking: "{{ main_do_private_networking }}"
    droplets_ipv6: "{{ main_do_ipv6 }}"
    droplets_wait_timeout: "{{ main_do_wait_timeout }}"
    droplets_tags: "{{ main_do_tags }}"
    droplets_host_data: "{{ main_do_host_data }}"
    droplets_list: "{{ main_do_cloud_instances }}"

- name: '{{ main_do_title }} - Init array main_do_active_hosts'
  set_fact: 
    main_do_active_hosts: []

- name: '{{ main_do_title }} - Include items in main_do_active_hosts'
  set_fact: 
    main_do_active_hosts: "{{ main_do_active_hosts + [{ 'name': main_do_item.name, 'ip_address': main_do_item.ip_address }] }}"
  loop: "{{ droplets_active }}"
  loop_control:
    loop_var: main_do_item
    label: "{{ main_do_item.name }}"