- block:
  
  - set_fact:
      cloud_main_inner_tmp_file_tags_src: "{{ cloud_main_inner_tmp_dir }}/tags.src.txt"
      cloud_main_inner_tmp_file_tags_dest: "{{ cloud_main_inner_tmp_dir }}/tags.dest.txt"
      cloud_main_inner_tags_final: []
    tags: ["no_print"]

  - set_fact:
      cloud_main_inner_tags_final: >-
        {{
        cloud_main_inner_tags_final +
        [cloud_main_inner_item]
        }}
    loop: "{{ cloud_main_inner_tags | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
    tags: ["no_print"]

  - name: >-
      {{ cloud_main_inner_title }} - create the temporary directory 
      '{{ cloud_main_inner_tmp_dir }}'
    file:
      path: "{{ cloud_main_inner_tmp_dir }}"
      state: directory
      mode: 0751
    when: cloud_main_state == 'present'

  - name: "{{ cloud_main_inner_title }} - tags tmp file src"
    copy: 
      content: "{{ cloud_main_inner_tags_final | default([]) }}" 
      dest: "{{ cloud_main_inner_tmp_file_tags_src }}"

  - name: "{{ cloud_main_inner_title }} - tags tmp file dest if empty"
    copy: 
      force: "{{ (cloud_main_state != 'present') | ternary(true, false) }}"
      content: ""
      dest: "{{ cloud_main_inner_tmp_file_tags_dest }}"
      mode: 0640

  - name: "{{ cloud_main_inner_title }} - tags - get the difference of two files (old and current)"
    command: >-
      diff {{ cloud_main_inner_tmp_file_tags_src }} {{ cloud_main_inner_tmp_file_tags_dest }}
    register: cloud_main_inner_diff
    failed_when: cloud_main_inner_diff.rc > 1
    changed_when: cloud_main_inner_diff.rc == 1
    when: cloud_main_state == 'present'

  - set_fact:
      cloud_main_inner_diff: { changed: false }
    when: cloud_main_state != 'present'
    tags: ["no_print"]

  - name: >-
      {{ cloud_main_inner_title }} -
      {{ (cloud_main_state == 'present') | ternary('create', 'destroy')}}
      tags
    digital_ocean_tag:
      api_token: "{{ cloud_main_inner_api_token }}"
      name: "{{ cloud_main_inner_item }}"
      state: "{{ cloud_main_state }}"
    loop: "{{ cloud_main_inner_tags_final | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
    when: (cloud_main_state != 'present') or cloud_main_inner_diff.changed
    tags: ["print_action"]

  - name: "{{ cloud_main_inner_title }} - tags tmp file dest"
    copy: 
      remote_src: yes
      src: "{{ cloud_main_inner_tmp_file_tags_src }}" 
      dest: "{{ cloud_main_inner_tmp_file_tags_dest }}"
      mode: 0640
    when: (cloud_main_state == 'present') and cloud_main_inner_diff.changed

  when: (cloud_main_inner_tags | default([])) | length > 0

- block:

  - set_fact:
      cloud_main_inner_tmp_file_firewalls_src: "{{ cloud_main_inner_tmp_dir }}/firewalls.src.txt"
      cloud_main_inner_tmp_file_firewalls_dest: "{{ cloud_main_inner_tmp_dir }}/firewalls.dest.txt"
      cloud_main_inner_firewalls_final: []
    tags: ["no_print"]

  - include_tasks: "digital_ocean.firewall_tags.yml"
    vars:
      cloud_main_inner_firewall: "{{ cloud_main_inner_item }}"
    loop: "{{ cloud_main_inner_firewalls | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
    tags: ["no_print"]

  - name: "{{ cloud_main_inner_title }} - firewalls tmp file src"
    copy: 
      content: "{{ cloud_main_inner_firewalls_final | default([]) }}" 
      dest: "{{ cloud_main_inner_tmp_file_firewalls_src }}"

  - name: "{{ cloud_main_inner_title }} - firewalls tmp file dest if empty"
    copy: 
      force: "{{ (cloud_main_state != 'present') | ternary(true, false) }}"
      content: ""
      dest: "{{ cloud_main_inner_tmp_file_firewalls_dest }}"
      mode: 0640

  - name: "{{ cloud_main_inner_title }} - firewalls - get the difference of two files (old and current)"
    command: >-
      diff 
      {{ cloud_main_inner_tmp_file_firewalls_src }} 
      {{ cloud_main_inner_tmp_file_firewalls_dest }}
    register: cloud_main_inner_diff
    failed_when: cloud_main_inner_diff.rc > 1
    changed_when: cloud_main_inner_diff.rc == 1
    when: cloud_main_state == 'present'

  - set_fact:
      cloud_main_inner_diff: { changed: false }
    when: cloud_main_state != 'present'
    tags: ["no_print"]

  - name: >-
      {{ cloud_main_inner_title }} -
      {{ (cloud_main_state == 'present') | ternary('create', 'destroy')}}
      firewalls
    digital_ocean_firewall:
      api_token: "{{ cloud_main_inner_api_token }}"
      name: "{{ cloud_main_inner_item.name }}"
      droplet_ids: "{{ cloud_main_inner_item.droplet_ids | default([]) }}"
      tags: "{{ cloud_main_inner_item.tags | default([]) }}"
      inbound_rules: "{{ cloud_main_inner_item.inbound_rules | default([]) }}"
      outbound_rules: "{{ cloud_main_inner_item.outbound_rules | default([]) }}"
      state: "{{ cloud_main_state }}"
    loop: "{{ cloud_main_inner_firewalls_final | default([]) }}"
    loop_control:
      loop_var: cloud_main_inner_item
      label: "{{ cloud_main_inner_item.name }}"
    when: (cloud_main_state != 'present') or cloud_main_inner_diff.changed
    tags: ["print_action"]

  - name: "{{ cloud_main_inner_title }} - firewalls tmp file dest"
    copy: 
      remote_src: yes
      src: "{{ cloud_main_inner_tmp_file_firewalls_src }}" 
      dest: "{{ cloud_main_inner_tmp_file_firewalls_dest }}"
      mode: 0640
    when: (cloud_main_state == 'present') and cloud_main_inner_diff.changed

  when: (cloud_main_inner_firewalls | default([])) | length > 0
