---

# - name: 'checking {{ watch_job }} status until finished'
#   include_tasks: 'loop.yml'
#   delay: '{{ watch_poll }}'
#   retries: '{{ watch_timeout / watch_poll }}'
#   until: watch_status.finished

- name: 'retries'
  set_fact:
    watch_retries: '{{ watch_timeout / watch_poll }}'
  
- name: 'checking {{ watch_job }} status until finished'
  include_tasks: 'loop.yml'
  loop: "{{ range(0, watch_retries | int, 1) | list }}"

- name: 'watch_status is finished'
  assert:
    that: watch_status.finished
