---

- name: 'initialize watch_count'
  set_fact:
    watch_count: 0

- name: 'checking {{ watch_job }} status until finished'
  become: yes
  include_tasks: 'recursive.yml'

- name: 'watch_status is finished'
  assert:
    that: watch_status.finished

- debug:
    var: watch_status
