---
  
- name: 'checking {{ watch_job }} status'
  become: yes
  async_status:
    jid: '{{ job.ansible_job_id }}'
  register: 'watch_status'
  vars:
    job: '{{ lookup("vars", watch_job) }}'
  when: 'job.ansible_job_id is defined'

- name: 'tail -n +{{ watch_lines }} {{ watch_file }}'
  become: yes
  shell: 'tail -n +{{ watch_lines }} {{ watch_file }}'
  register: 'watch_tail'
  failed_when: false
  changed_when: false

- block:

  - name: '{{ watch_output_lines }} lines captured'
    set_fact:
      watch_lines: '{{ watch_lines|int + watch_output_lines|int }}'

  - name: '{{ watch_file }}'
    debug:
      var: 'watch_output'

  vars:
    watch_output: '{{ watch_tail.stdout_lines|default([]) }}'
    watch_output_lines: '{{ watch_output|length|int }}'
  when: 'watch_output_lines > 0'
