---

- name: 'checking {{ watch_job }} status'
  become: yes
  async_status:
    jid: '{{ job.ansible_job_id }}'
  register: 'watch_status'
  vars:
    job: '{{ lookup("vars", watch_job) }}'
  when: 'job.ansible_job_id is defined'

- name: 'watch_job'
  debug:
    var: '{{ watch_job }}'

- name: 'watch_status'
  debug:
    var: '{{ watch_status }}'

- name: 'watch_status2'
  debug:
    msg: '{{ watch_status.finished }} --- {{ watch_status.skipped }}'

- name: 'tail -n +{{ watch_lines }} {{ watch_file }}'
  failed_when: false
  shell: 'tail -n +{{ watch_lines }} {{ watch_file }}'
  register: 'watch_tail'

- block:
  - name: '{{ output_lines }} lines captured'
    set_fact:
      watch_lines: '{{ watch_lines|int + output_lines|int }}'

  - name: '{{ watch_file }}'
    debug:
      var: 'output'

  vars:
    output: '{{ watch_tail.stdout_lines|default([]) }}'
    output_lines: '{{ output|length|int }}'
  when: 'output_lines > 0'
