---
  
- name: '[{{ watch_title }}] - checking {{ watch_job }} status'
  become: "{{ watch_become }}"
  async_status:
    jid: '{{ job.ansible_job_id }}'
  register: 'watch_status'
  vars:
    job: '{{ lookup("vars", watch_job) }}'
  when: 'job.ansible_job_id is defined'
  changed_when: false
  tags: ["no_print"]

- name: '[{{ watch_title }}] - tail -n +{{ watch_lines }} {{ watch_file }}'
  become: "{{ watch_become }}"
  shell: 'tail -n +{{ watch_lines }} {{ watch_file }}'
  register: 'watch_tail'
  failed_when: false
  changed_when: false
  tags: ["no_print"]

- set_fact:
    watch_output: '{{ watch_tail.stdout_lines | default([]) }}'
  tags: ["no_print"]
      
- set_fact:
    watch_output_lines: '{{ watch_output | length | int }}'
  tags: ["no_print"]

- debug:
    var: watch_lines

- debug:
    var: watch_output_lines
  
- block:
 
  - name: '[{{ watch_title }}] - {{ watch_output_lines }} lines captured'
    set_fact:
      watch_lines: '{{ watch_lines|int + watch_output_lines|int }}'
    tags: ["no_print"]

  - name: '[{{ watch_title }}] - {{ watch_file }} - {{ watch_output_lines }} lines captured'
    debug:
      var: watch_output
    tags: ["print_action"]
    
  when: (watch_output_lines | int) > 0
