---

- name: "{{ watch_title }} - checking the job ({{ watch_job }}) status"
  become: "{{ watch_become }}"
  async_status:
    jid: "{{ job.ansible_job_id }}"
  register: "watch_status"
  vars:
    job: "{{ lookup('vars', watch_job) }}"
  when: job.ansible_job_id is defined
  changed_when: false
  tags: ["no_print"]

- name: "{{ watch_title }} - tail -n +{{ watch_lines }} {{ watch_file }}"
  become: "{{ watch_become }}"
  shell: "tail -n +{{ watch_lines }} {{ watch_file }}"
  register: "watch_tail"
  failed_when: false
  changed_when: false
  tags: ["no_print"]

- name: "{{ watch_title }} - watch_output"
  set_fact:
    watch_output: "{{ watch_tail.stdout_lines | default([]) }}"
  tags: ["no_print"]

- name: "{{ watch_title }} - watch_output_lines"
  set_fact:
    watch_output_lines: "{{ watch_output | length | int }}"
  tags: ["no_print"]

- name: "{{ watch_title }} - main block"
  block:

  - name: "{{ watch_title }} - watch_lines"
    set_fact:
      watch_lines: "{{ (watch_lines | int) + (watch_output_lines | int) }}"
    tags: ["no_print"]

  - name: "{{ watch_title }} - {{ watch_file }} - {{ watch_output_lines }} lines captured"
    debug:
      var: watch_output

  when: (watch_output_lines | int) > 0
  tags: ["no_print_skipped"]
