---

- name: "{{ watch_title }} - watch_lines (initial)"
  set_fact:
    watch_lines: 1
  tags: ["no_print"]

- name: "{{ watch_title }} - include_task [again.yml]"
  include_tasks: "again.yml"
  tags: ["no_print"]
