---

- name: 'checking {{ watch_job }} status (recursive)'
  become: yes
  include_tasks: 'loop.yml'

- name: 'set watch_finished'
  become: yes
  set_fact:
    watch_finished: "{{ watch_status.finished }}"

- debug:
    var: watch_status

- debug:
    msg: "watch_finished={{ watch_finished }}"

- debug:
    msg: "not watch_finished={{ not watch_finished }}"

- name: 'count ({{ watch_count | int + 1 }})'
  set_fact:
    watch_count: '{{ watch_count | int + 1 }}'

- name: 'retries ({{ (watch_timeout | int / watch_poll | int) | int }})'
  set_fact:
    watch_retries: '{{ (watch_timeout | int / watch_poll | int) | int }}'

- name: 'timeout ({{ watch_timeout }} seconds)'
  fail: 
    msg: "Timeout of {{ watch_timeout }} seconds exceeded ({{ watch_retries }} retries)"
  when: (not watch_finished) and (watch_count | int > watch_retries | int)

- name: 'wait for {{ watch_poll }} seconds'
  wait_for:
    timeout: '{{ watch_poll | int }}'
  when: not watch_finished

- name: 'call itself recursively'
  include_tasks: 'recursive.yml'
  when: not watch_finished