# repo files

- name: >-
    {{ cloud_repos_extra_repo_title }} - repo files - create the dest files directories
  file:
    path: "{{ (cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest) | dirname }}"
    state: directory
    mode: "{{ cloud_repos_env_dev | bool | ternary(0777, 0755) }}"
  loop: "{{ cloud_repos_item.files | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_title }} - repo files - copy"
  copy:
    src: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.src }}"
    dest: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest }}"
    mode: "{{ cloud_repos_env_dev | bool | ternary(0666, 0600) }}"
  loop: "{{ cloud_repos_item.files | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.src }} -> {{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print_skipped"]

# env files

- name: >-
    {{ cloud_repos_extra_repo_title }} - env files - create the dest files directories
  file:
    path: "{{ (cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest) | dirname }}"
    state: directory
    mode: "{{ cloud_repos_env_dev | bool | ternary(0777, 0755) }}"
  loop: "{{ cloud_repos_item.env_files | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_title }} - env files - copy"
  copy:
    src: "{{ cloud_repos_env_dir + '/' + cloud_repos_extra_repo_item.src }}"
    dest: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest }}"
    mode: "{{ cloud_repos_env_dev | bool | ternary(0666, 0600) }}"
  loop: "{{ cloud_repos_item.env_files | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.src }} -> {{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print_skipped"]

# repo templates

- name: >-
    {{ cloud_repos_extra_repo_title }} - repo templates - create the dest templates directories
  file:
    path: "{{ (cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest) | dirname }}"
    state: directory
    mode: "{{ cloud_repos_env_dev | bool | ternary(0777, 0755) }}"
  loop: "{{ cloud_repos_item.templates | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_title }} - repo templates - transfer"
  template:
    src: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.src }}"
    dest: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest }}"
    mode: "{{ cloud_repos_env_dev | bool | ternary(0666, 0600) }}"
  vars:
    params: "{{ cloud_repos_extra_repo_item.params }}"
  loop: "{{ cloud_repos_item.templates | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.src }} -> {{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print_skipped"]

# env templates

- name: >-
    {{ cloud_repos_extra_repo_title }} - env templates - create the dest templates directories
  file:
    path: "{{ (cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest) | dirname }}"
    state: directory
    mode: "{{ cloud_repos_env_dev | bool | ternary(0777, 0755) }}"
  loop: "{{ cloud_repos_item.env_templates | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_title }} - env templates - transfer"
  template:
    src: "{{ cloud_repos_env_dir + '/' + cloud_repos_extra_repo_item.src }}"
    dest: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest }}"
    mode: "{{ cloud_repos_env_dev | bool | ternary(0666, 0600) }}"
  vars:
    params: "{{ cloud_repos_extra_repo_item.params }}"
  loop: "{{ cloud_repos_item.env_templates | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_item.src }} -> {{ cloud_repos_extra_repo_item.dest }}"
  tags: ["no_print_skipped"]

# links

- name: "{{ cloud_repos_extra_repo_title }} - error var"
  set_fact:
    error: {}
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_title }} - links (outer)"
  include_tasks: "extra_repo_link.yml"
  vars:
    tmp_target_repo_name: >-
      {{ cloud_repos_extra_repo_item.repo | default(cloud_repos_extra_repo_name, true) }}
    tmp_target_repos: >-
      {{
        cloud_repos_ctx_extra_repos
        | selectattr('repo', 'equalto', tmp_target_repo_name) | list
      }}
    tmp_target_repo: >-
      {{
        ((tmp_target_repos | length) > 0)
        | ternary(
          tmp_target_repos[0],
          error['extra repo link: repo ' + cloud_repos_extra_repo_name + ' not found'],
        )
      }}
    tmp_src_default: >-
      {{
        cloud_repos_extra_repos_dir + '/' +
        tmp_target_repo.dir + '/' +
        cloud_repos_extra_repo_item.src
      }}
    tmp_dev_path_src: "{{ cloud_repos_env_path_map[tmp_target_repo_name] | default('') }}"
    cloud_repos_extra_repo_link_src: >-
      {{
        (tmp_dev_path_src != '')
        | ternary(
          cloud_repos_dev_repos_dir + '/' + tmp_dev_path_src + '/' + cloud_repos_extra_repo_item.src,
          tmp_src_default
        )
      }}
    tmp_dest_default: "{{ cloud_repos_extra_repo_dir + '/' + cloud_repos_extra_repo_item.dest }}"
    tmp_dev_path_dest: "{{ cloud_repos_env_path_map[cloud_repos_extra_repo_name] | default('') }}"
    cloud_repos_extra_repo_link_dest: >-
      {{
        (tmp_dev_path_dest != '')
        | ternary(
          cloud_repos_dev_repos_dir + '/' + tmp_dev_path_dest + '/' + cloud_repos_extra_repo_item.dest,
          tmp_dest_default
        )
      }}
    cloud_repos_extra_repo_link_title: >-
      {{ cloud_repos_extra_repo_title }} -
      link [{{ cloud_repos_extra_repo_link_dest }} -> {{ cloud_repos_extra_repo_link_src }}]
  loop: "{{ cloud_repos_item.links | default([]) }}"
  loop_control:
    loop_var: cloud_repos_extra_repo_item
    label: "{{ cloud_repos_extra_repo_link_dest }} -> {{ cloud_repos_extra_repo_link_src }}"
  tags: ["no_print"]
