- name: "{{ cloud_repos_extra_repo_link_title }} - create src directory"
  file:
    path: "{{ cloud_repos_extra_repo_link_src | dirname }}"
    state: directory
    mode: "{{ repo_dev | bool | ternary(0777, 0755) }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_link_title }} - create dest directory"
  file:
    path: "{{ cloud_repos_extra_repo_link_dest | dirname }}"
    state: directory
    mode: "{{ repo_dev | bool | ternary(0777, 0755) }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_extra_repo_link_title }} - create link"
  file:
    src: "{{ cloud_repos_extra_repo_link_src | relpath(cloud_repos_extra_repo_link_dest | dirname) }}"
    dest: "{{ cloud_repos_extra_repo_link_dest }}"
    state: link
    mode: "{{ repo_dev | bool | ternary(0777, 0755) }}"
  tags: ["no_print"]
