- name: "{{ cloud_repos_layer_title }} - main (outer)"
  include_tasks: "tasks/repo.yml"
  vars:
    repo_title: "{{ cloud_repos_layer_title }} - main"
    repo_main: "{{ cloud_repos_repos_dict[cloud_repos_layer.repo] }}"
    repo_ssh_src_dir: "{{ cloud_repos_env_dir }}"
    repo_secrets_dir: "{{ cloud_repos_secrets_repos_dir }}/{{ cloud_repos_layer.repo }}"
    repo_default_dir: "{{ cloud_repos_layer_dest }}"
    repo_dev_base_dir: "{{ cloud_repos_dev_repos_dir }}"
    repo_dev_path: "{{ cloud_repos_env_path_map[cloud_repos_layer.repo] | default('') }}"
    repo_dev: "{{ cloud_repos_env_dev }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_layer_title }} - cloud_repos_layer_dir"
  set_fact:
    cloud_repos_layer_dir: "{{ repo_dir }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_layer_title }} - env repos"
  include_tasks: "tasks/repo.yml"
  vars:
    repo_title: "{{ cloud_repos_layer_title }} - env repo ({{ cloud_repos_layer_item.repo }})"
    repo_main: "{{ cloud_repos_repos_dict[cloud_repos_layer_item.repo] }}"
    repo_ssh_src_dir: "{{ cloud_repos_env_dir }}"
    repo_secrets_dir: "{{ cloud_repos_secrets_repos_dir }}/{{ cloud_repos_layer_item.repo }}"
    repo_default_dir: "{{ cloud_repos_layer_dir }}/{{ cloud_repos_layer_item.dir }}"
    repo_dev_base_dir: "{{ cloud_repos_dev_repos_dir }}"
    repo_dev_path: "{{ cloud_repos_env_path_map[cloud_repos_layer_item.repo] | default('') }}"
    repo_dev: "{{ cloud_repos_env_dev }}"
  loop: "{{ cloud_repos_layer.env_repos | default([]) }}"
  loop_control:
    loop_var: cloud_repos_layer_item
    label: "{{ cloud_repos_layer_item.repo }}"
  tags: ["no_print"]
