- name: "{{ cloud_repos_layer_title }} - main (outer)"
  include_tasks: "git.yml"
  vars:
    git_title: "{{ cloud_repos_layer_title }} - main"
    git_repo: "{{ cloud_repos_layer_repo }}"
    git_ssh_src_dir: "{{ cloud_repos_env_dir }}"
    git_secrets_dir: "{{ cloud_repos_env_tmp_dir }}/{{ cloud_repos_layer.repo }}"
    git_repo_dir: "{{ cloud_repos_layer_dest }}"
    git_update: "{{ cloud_repos_layer_git_update }}"
    git_dev: "{{ env_dev }}"
  tags: ["no_print"]

- name: "{{ cloud_repos_layer_title }} - env repos"
  include_tasks: "git.yml"
  vars:
    git_title: "{{ cloud_repos_layer_title }} - env repo ({{ cloud_repos_layer_item.repo }})"
    git_repo: "{{ cloud_repos_repos_dict[cloud_repos_layer_item.repo] }}"
    git_ssh_src_dir: "{{ cloud_repos_env_dir }}"
    git_secrets_dir: "{{ cloud_repos_env_tmp_dir }}/{{ cloud_repos_layer.repo }}"
    git_repo_dir: "{{ cloud_repos_layer_dest }}/{{ cloud_repos_layer_item.dir }}"
    git_update: "{{ cloud_repos_layer_git_update }}"
    git_dev: "{{ env_dev }}"
  loop: "{{ cloud_repos_layer.env_repos | default([]) }}"
  loop_control:
    loop_var: cloud_repos_layer_item
    label: "{{ cloud_repos_layer_item.repo }}"
  tags: ["no_print"]