- set_fact:
    cloud_repos_pods_list: []
  tags: ["no_print"]

- set_fact:
    cloud_repos_pods_list: "{{ cloud_repos_pods_list + (cloud_repos_node.pods | default([])) }}"
  vars:
    cloud_repos_node_key: "{{ cloud_repos_item.key | default(cloud_repos_item.name) | default(cloud_repos_item) }}"
    cloud_repos_node: "{{ cloud_repos_nodes_dict[cloud_repos_node_key] }}"
  loop: "{{ cloud_repos_nodes }}"
  loop_control:
    loop_var: cloud_repos_item
  tags: ["no_print"]

- include_tasks: "layer.yml"
  vars:
    cloud_repos_layer_type: "pod"
    cloud_repos_layer_name: "{{ cloud_repos_item.name | default(cloud_repos_item) }}"
    cloud_repos_layer_key: "{{ cloud_repos_item.key | default(cloud_repos_item.name) | default(cloud_repos_item) }}"
    cloud_repos_layer: "{{ cloud_repos_pods_dict[cloud_repos_layer_key] }}"
    cloud_repos_layer_title: >-
      {{ cloud_repos_title }} - pods - repositories - local (for remote) - 
      {{ cloud_repos_layer.repo }}
    cloud_repos_layer_dest: >-
      {{ cloud_repos_env_tmp_dir + '/repo/pod/' + cloud_repos_layer_name }}
    cloud_repos_layer_git_update: yes
    cloud_repos_layer_git_force: yes
    cloud_repos_layer_dir_mode: "0755"
    cloud_repos_layer_become: "{{ cloud_repos_layer.root | default(false) }}"
  loop: "{{ cloud_repos_pods_list }}"
  loop_control:
    loop_var: cloud_repos_item
  when: not (cloud_repos_layer_key in (cloud_repos_local_pods | default([])))

- fail: 
    msg: "local pod {{ cloud_repos_item }} is not defined"
  vars:
    cloud_repos_local_pod: "{{ cloud_repos_env_local_pod_dict[cloud_repos_item] }}"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_local_pod is not defined

- fail: 
    msg: "local pod {{ cloud_repos_item }} has no repository defined"
  vars:
    cloud_repos_local_pod: "{{ cloud_repos_env_local_pod_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_pod.repo] }}"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_repo is not defined
    
- include_tasks: "layer.yml"
  vars:
    cloud_repos_layer_type: "pod"
    cloud_repos_layer_name: "{{ cloud_repos_item }}"
    cloud_repos_layer_key: "{{ cloud_repos_item }}"
    cloud_repos_layer: "{{ cloud_repos_pods_dict[cloud_repos_layer_key] }}"
    cloud_repos_layer_title: >-
      {{ cloud_repos_title }} - pods - repositories - local (for remote) - 
      {{ cloud_repos_layer.repo }}
    cloud_repos_layer_dest: >-
      {{ cloud_repos_env_local_pod_dict[cloud_repos_layer_name].dir }}
    cloud_repos_layer_git_update: no
    cloud_repos_layer_git_force: no
    cloud_repos_layer_dir_mode: "0777"
    cloud_repos_layer_become: "{{ cloud_repos_layer.root | default(false) }}"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item

- fail: 
    msg: "local app {{ cloud_repos_item }} is not defined"
  vars:
    cloud_repos_local_app: "{{ cloud_repos_env_local_app_dict[cloud_repos_item] }}"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_local_app is not defined

- fail: 
    msg: "local app {{ cloud_repos_item }} has no repository defined"
  vars:
    cloud_repos_local_app: "{{ cloud_repos_env_local_app_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_app.repo] }}"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_repo is not defined

- include_tasks: "layer.yml"
  vars:
    cloud_repos_layer_type: "app"
    cloud_repos_layer_name: "{{ cloud_repos_item }}"
    cloud_repos_layer: "{{ cloud_repos_apps_dict[cloud_repos_layer_name] }}"
    cloud_repos_layer_title: >-
      {{ cloud_repos_title }} - apps - repositories - local (for remote) - 
      {{ cloud_repos_layer.repo }}
    cloud_repos_layer_dest: >-
      {{ cloud_repos_env_local_app_dict[cloud_repos_layer_name].dir }}
    cloud_repos_layer_git_update: no
    cloud_repos_layer_git_force: no
    cloud_repos_layer_dir_mode: "0777"
    cloud_repos_layer_become: "{{ cloud_repos_layer.root | default(false) }}"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item