- include_role: 
    name: "cloud_git"
  vars:
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_item.value.repo] }}"
    cloud_git_key: "{{ cloud_repos_item.value.repo }}"
    cloud_git_title: >-
      {{ cloud_repos_title }} - pods - repositories - local (for remote) - 
      {{ cloud_repos_item.value.repo }}
    cloud_git_repo: "{{ cloud_repos_repo.src }}"
    cloud_git_version: "{{ cloud_repos_repo.version }}"
    cloud_git_private: "{{ cloud_repos_repo.private | default(false) }}"
    cloud_git_key_file_encrypted: >-
      {{ cloud_repos_env_dir }}/{{ cloud_repos_repo.key_file_encrypted }}
    cloud_git_dest: "{{ cloud_repos_env_tmp_dir }}/repo/pod/{{ cloud_repos_item.key }}"
    cloud_git_tmp_dir: "{{ cloud_repos_env_tmp_dir }}/repo/tmp/{{ cloud_repos_item.value.repo }}"
    cloud_git_update: yes
    cloud_git_force: yes
    cloud_git_dir_mode: "0755"
  loop: "{{ lookup('dict', (cloud_repos_pods_dict | default({})), wantlist=True) }}"
  loop_control:
    loop_var: cloud_repos_item
    label: "{{ cloud_repos_item.key }}"
  when: not (cloud_repos_item.key in (cloud_repos_local_pods | default([])))

- fail: 
    msg: "local pod {{ cloud_repos_item }} is not defined"
  vars:
    cloud_repos_local_pod: "{{ cloud_repos_env_local_pod_dict[cloud_repos_item] }}"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_local_pod is not defined

- fail: 
    msg: "local pod {{ cloud_repos_item }} has no repository defined"
  vars:
    cloud_repos_local_pod: "{{ cloud_repos_env_local_pod_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_pod.repo] }}"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_repo is not defined
    
- include_role: 
    name: "cloud_git"
  vars:
    cloud_repos_local_pod: "{{ cloud_repos_env_local_pod_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_pod.repo] }}"
    cloud_git_key: "{{ cloud_repos_local_pod.repo }}"
    cloud_git_title: >-
      {{ cloud_repos_title }} - pods - repositories - local (dev) - 
      {{ cloud_repos_local_pod.repo }}
    cloud_git_repo: "{{ cloud_repos_repo.src }}"
    cloud_git_version: "{{ cloud_repos_repo.version }}"
    cloud_git_private: "{{ cloud_repos_repo.private | default(false) }}"
    cloud_git_key_file_encrypted: >-
      {{ cloud_repos_env_dir }}/{{ cloud_repos_repo.key_file_encrypted }}
    cloud_git_dest: "{{ cloud_repos_env_tmp_dir }}/repo/pod/{{ cloud_repos_item }}"
    cloud_git_tmp_dir: "{{ cloud_repos_env_tmp_dir }}/repo/tmp/{{ cloud_repos_local_pod.repo }}"
    cloud_git_update: no
    cloud_git_force: no
    cloud_git_dir_mode: "0777"
  loop: "{{ cloud_repos_local_pods | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item

- fail: 
    msg: "local app {{ cloud_repos_item }} is not defined"
  vars:
    cloud_repos_local_app: "{{ cloud_repos_env_local_app_dict[cloud_repos_item] }}"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_local_app is not defined

- fail: 
    msg: "local app {{ cloud_repos_item }} has no repository defined"
  vars:
    cloud_repos_local_app: "{{ cloud_repos_env_local_app_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_app.repo] }}"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item
  when: cloud_repos_repo is not defined

- include_role: 
    name: "cloud_git"
  vars:
    cloud_repos_local_app: "{{ cloud_repos_env_local_app_dict[cloud_repos_item] }}"
    cloud_repos_repo: "{{ cloud_repos_repos_dict[cloud_repos_local_app.repo] }}"
    cloud_git_key: "{{ cloud_repos_local_app.repo }}"
    cloud_git_title: >-
      {{ cloud_repos_title }} - pods - repositories - local (dev) - 
      {{ cloud_repos_local_app.repo }}
    cloud_git_repo: "{{ cloud_repos_repo.src }}"
    cloud_git_version: "{{ cloud_repos_repo.version }}"
    cloud_git_private: "{{ cloud_repos_repo.private | default(false) }}"
    cloud_git_key_file_encrypted: >-
      {{ cloud_repos_env_dir }}/{{ cloud_repos_repo.key_file_encrypted }}
    cloud_git_dest: "{{ cloud_repos_env_tmp_dir }}/repo/pod/{{ cloud_repos_item }}"
    cloud_git_tmp_dir: "{{ cloud_repos_env_tmp_dir }}/repo/tmp/{{ cloud_repos_local_app.repo }}"
    cloud_git_update: no
    cloud_git_force: no
    cloud_git_dir_mode: "0777"
  loop: "{{ cloud_repos_local_apps | default([]) }}"
  loop_control:
    loop_var: cloud_repos_item