- set_fact:
    cloud_repos_pods_list: []
  tags: ["no_print"]

- set_fact:
    cloud_repos_pods_list: "{{ cloud_repos_pods_list + (cloud_repos_node.pods | default([])) }}"
  vars:
    cloud_repos_node_key: "{{ cloud_repos_item.key | default(cloud_repos_item.name) | default(cloud_repos_item) }}"
    cloud_repos_node: "{{ cloud_repos_nodes_dict[cloud_repos_node_key] }}"
  loop: "{{ cloud_repos_nodes }}"
  loop_control:
    loop_var: cloud_repos_item
  tags: ["no_print"]

- name: "{{ cloud_repos_title }} - local repos - pods"
  include_tasks: "layer.yml"
  vars:
    cloud_repos_layer_name: "{{ cloud_repos_item.name | default(cloud_repos_item) }}"
    cloud_repos_layer_key: "{{ cloud_repos_item.key | default(cloud_repos_item.name) | default(cloud_repos_item) }}"
    cloud_repos_layer: "{{ cloud_repos_pods_dict[cloud_repos_layer_key] }}"
    cloud_repos_layer_title: >-
      {{ cloud_repos_title }} - local repos - pod
      [{{ cloud_repos_layer_name }} ({{ cloud_repos_layer.repo }})]
    cloud_repos_layer_dest: >-
      {{ cloud_repos_pods_dir + '/' + cloud_repos_layer_name }}
  loop: "{{ cloud_repos_pods_list }}"
  loop_control:
    loop_var: cloud_repos_item
  tags: ["no_print"]

- name: "{{ cloud_repos_title }} - extra repos (local)"
  include_tasks: "layer.yml"
  vars:
    cloud_repos_layer: "{{ cloud_repos_item }}"
    cloud_repos_layer_title: >-
      {{ cloud_repos_title }} - extra repos (local)
      [{{ cloud_repos_item.dir }} ({{ cloud_repos_item.repo }})]
    cloud_repos_layer_dest: >-
      {{ cloud_repos_extra_repos_dir + '/' + cloud_repos_item.dir }}
  loop: "{{ cloud_repos_ctx_extra_repos }}"
  loop_control:
    loop_var: cloud_repos_item
  tags: ["no_print"]
#
# - name: "{{ cloud_repos_title }} - extra repos (local)"
#   include_tasks: "extra_repo.yml"
#   vars:
#     cloud_repos_extra_repo: "{{ cloud_repos_item }}"
#     cloud_repos_extra_repo_name: "{{ cloud_repos_item.repo }}"
#     cloud_repos_extra_repo_title: >-
#       {{ cloud_repos_title }} - extra repo (local)
#       [{{ cloud_repos_item.dir }} ({{ cloud_repos_extra_repo_name }})]
#     cloud_repos_extra_repo_dir: >-
#       {{ cloud_repos_extra_repos_dir + '/' + cloud_repos_item.dir }}
#   loop: "{{ cloud_repos_ctx_extra_repos }}"
#   loop_control:
#     loop_var: cloud_repos_item
#   tags: ["no_print"]
