- block:
    - name: "{{ pod_dependency_title }}"
      set_fact:
        pod_dependency_index_aux: >-
          {{
            (pod_dependency_ips | length) *
              (instance_index | int) /
                (pod_dependency_total_src_nodes | int)
          }}
      tags: ["no_print"]

    - name: "{{ pod_dependency_title }}"
      set_fact:
        pod_dependency_index: "{{ (pod_dependency_index_aux | int) - 1}}"
      tags: ["no_print"]

    - name: "{{ pod_dependency_title }}"
      set_fact:
        pod_dependencies: >-
          {{
            pod_dependencies
            +
            [{
              'host': pod_dependency_host,
              'ip': pod_dependency_ips[pod_dependency_index | int]
            }]
          }}
      tags: ["no_print"]

    - name: "{{ pod_dependency_title }}"
      set_fact:
        pod_dependencies_ip_dict: >-
          {{
            pod_dependencies_ip_dict | combine({
              pod_dependency_host:
              pod_dependency_ips[pod_dependency_index | int]
            })
          }}
      tags: ["no_print"]

  when: (not (pod_dependency_all | bool)) and ((pod_dependency_ips | length) > 0)
  tags: ["no_print_skipped"]

- block:
    - name: "{{ pod_dependency_title }}"
      set_fact:
        pod_dependencies: >-
          {{
            pod_dependencies
            +
            [{
              'host': pod_dependency_host + '-' + pod_dependency_index,
              'ip': pod_dependency_item
            }]
          }}
      loop: "{{ pod_dependency_ips | flatten(levels=1) }}"
      loop_control:
        index_var: pod_dependency_index
        loop_var: pod_dependency_item
      tags: ["no_print"]

  when: pod_dependency_all | bool
  tags: ["no_print_skipped"]

- name: "{{ pod_dependency_title }}"
  set_fact:
    pod_dependencies_ips_dict: >-
      {{
        pod_dependencies_ips_dict | combine({
          pod_dependency_host:
          pod_dependency_ips
        })
      }}
  tags: ["no_print"]
