# Node Vars

- name: "{{ pod_title }} - pod_node_credential"
  set_fact:
    pod_node_local: "{{ pod_node.local | default(false) | bool }}"
    pod_node_credential: "{{ pod_node.credential | default({}) }}"
    pod_remote_node_base_dir: >-
      {{ pod_node.base_dir | default('') }}
  tags: ["no_print"]

# Dependencies

- name: "{{ pod_title }}- pod_dependencies"
  set_fact:
    pod_dependencies: []
    pod_dependencies_ip_dict: {}
    pod_dependencies_ips_dict: {}
  tags: ["no_print"]

- name: "{{ pod_title }} - node dependencies (outer)"
  include_tasks: "tasks/pods/dependency.yml"
  vars:
    pod_dependency_title: >-
      {{ pod_title }} - dependency[{{ pod_node_item.host }}]
    pod_dependency_host: "{{ pod_node_item.host }}"
    pod_dependency_node: "{{ pod_node_item.node }}"
    pod_dependency_all: "{{ pod_node_item.all | default(false) | bool }}"
    pod_dependency_field: >-
      {{
        pod_node_item.public | default(false) | bool
        | ternary('instance_public_ipv4', 'instance_private_ip')
      }}
    pod_dependency_total_src_nodes: "{{ groups[pod_node_name] | length }}"
    pod_dependency_ips: >-
      {{
        groups[pod_dependency_node]
        | map('extract', hostvars, [pod_dependency_field]) | list
      }}
  loop: "{{ pod_node.dependencies | default([]) | list }}"
  loop_control:
    loop_var: pod_node_item
  when: not (pod_node_local | bool)
  tags: ["no_print"]

- name: "{{ pod_title }} - define the dependencies ips"
  become: true
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ pod_node_item.host }}$"
    line: "{{ pod_node_item.ip }} {{ pod_node_item.host }}"
    state: present
  loop: "{{ pod_dependencies }}"
  loop_control:
    loop_var: pod_node_item
    label: "{{ pod_node_item.host }}"
  tags: ["no_print_skipped"]

# Pods

- name: "{{ pod_title }} - pods (outer)"
  include_tasks: "tasks/pods/pod.yml"
  vars:
    pod_pod_info: "{{ pod_node_item }}"
    pod_pod_name: "{{ pod_node_item.name | default(pod_node_item) }}"
    pod_pod_key: >-
      {{
        pod_node_item.key
        | default(pod_node_item.name, true)
        | default(pod_node_item, true)
      }}
    pod_pod_main: >-
      {{
        (pod_node_item.main | default(false) | bool)
        or
        ((pod_node.pods | default([]) | length) == 1)
      }}
    pod_pod: "{{ env.pods[pod_pod_key] }}"
    pod_node_info_pod_params: >-
      {{ pod_node_info.pods[pod_pod_name] | default({}) }}
    pod_pod_title: >-
      {{ pod_title }} - pod[{{ pod_pod_name }}]
    pod_pod_dirname: >-
      {{ pod_pod.base_dir | default(pod_pod_name, true) }}
    pod_remote_pod_base_dir: >-
      {{ pod_remote_node_base_dir }}/{{ pod_pod_dirname }}
    pod_pod_identifier: >-
      {{ env.name }}/{{ env_ctx_name }}/{{ pod_pod_name }}
    pod_host_user: "{{ pod_node_credential.host_user }}"
    pod_host_group: "{{ pod_node_credential.host_user }}"
    pod_local_pod_default_repo_dir: >-
      {{ pod_local_pods_base_dir + '/' + pod_pod_name }}
    pod_pod_local_tmp_dir: >-
      {{ pod_node_tmp_dir }}/pod/{{ pod_pod_name }}
    pod_pod_local_data_dir_inside: >-
      {{
        (pod_local_data_dir_inside | default('') != '')
        | ternary(
          pod_local_data_dir_inside
            + '/' + pod_pod_identifier,
          ''
        )
      }}
  loop: "{{ pod_node.pods | default([]) }}"
  loop_control:
    loop_var: pod_node_item
  when: (env_pod | default('')) in ['', pod_pod_name]
  tags: ["no_print_skipped"]
