### Set vars ###

- name: "{{ pod_inner_title }} - pod_local_repo_dir (local)"
  set_fact:
    pod_local_repo_dir: "{{ pod_item.local_dir }}"=
  tags: ["no_print"]

- name: "{{ pod_inner_title }} - pod_main_repo_dir"
  set_fact:
    pod_main_repo_dir: >-
      {{ pod_remote_base_dir
      }}{{ pod_item.flat | default(false, true) | bool | ternary('', '/main') }}
    pod_tmp_base_dir: "{{ pod_remote_tmp_dir }}"
    pod_tmp_repo_dir: "{{ pod_remote_tmp_dir + '/main' }}"
  tags: ["no_print"]

- name: "{{ pod_inner_title }} - pod_main_repo_dir (local)"
  set_fact:
    pod_main_repo_dir: "{{ pod_item.local_dir }}"
    pod_tmp_base_dir: "{{ pod_item.local_dir + '/tmp' }}"
    pod_tmp_repo_dir: "{{ pod_item.local_dir + '/tmp/pod' }}"
  when: pod_node_local | bool
  tags: ["no_print"]

- name: "{{ pod_inner_title }} - pod_backup_file"
  set_fact:
    pod_backup_file: >-
      {{ pod_tmp_base_dir }}/env/{{ pod_env_vars_relative_file_name }}
    pod_backup_file_tmp: >-
      {{ pod_tmp_base_dir }}/env/{{ pod_env_vars_relative_file_name }}.tmp
  when: not (pod_fast | bool)
  tags: ["no_print"]

### Prepare the directories ###

- name: "{{ pod_inner_title }} - create the backup directories"
  become: "{{ pod_item.root }}"
  file:
    path: "{{ pod_inner_item | dirname }}"
    state: directory
    mode: "{{ (pod_node_local | bool) | ternary(0777, 0755) }}"
  loop:
    - "{{ pod_backup_file }}"
    - "{{ pod_backup_file_tmp }}"
  loop_control:
    loop_var: pod_inner_item
    label: "{{ pod_inner_item | dirname }}"
  when: not (pod_fast | bool)
  tags: ["no_print_skipped"]

- name: >-
    {{ pod_inner_title }} - create the file to verify if there was a change,
    if it was not created before
  become: "{{ pod_item.root }}"
  copy:
    force: no
    content: ""
    dest: "{{ pod_backup_file }}"
    owner: "{{ pod_host_user }}"
    group: "{{ pod_host_group }}"
    mode: "{{ (pod_node_local | bool) | ternary(0666, 0640) }}"
  when: not (pod_fast | bool)
  tags: ["no_print_skipped"]

### Prepare the temporary directory (to catch errors before updating the real one) ###

- block:
    - name: "{{ pod_inner_title }} - prepare the temporary directory"
      include_tasks: "tasks/pods/prepare.yml"
      vars:
        pod_prepare_title: "{{ pod_inner_title }} - tmp"
        pod_repo_dir: "{{ pod_tmp_repo_dir }}"
      tags: ["no_print"]

    - name: "{{ pod_inner_title }} - get the difference of the 2 files (old and current)"
      become: "{{ pod_item.root }}"
      command: "diff {{ pod_backup_file_tmp }} {{ pod_backup_file }}"
      register: pod_diff
      failed_when: pod_diff.rc > 1
      changed_when: pod_diff.rc == 1
      when: not (pod_fast | bool)
      tags: ["no_print_skipped"]

    - name: "{{ pod_inner_title }} - debug - outer"
      debug:
        msg: "variables unchanged"
      when: not (pod_diff.changed | default(false, true) | bool)
      tags: ["no_print_skipped"]

  when: not (pod_item.fast_prepare | default(false, true) | bool)
  tags: ["no_print_skipped"]

### Prepare the real directory ###

- block:
    - name: "{{ pod_inner_title }} - prepare the main directory"
      include_tasks: "tasks/pods/prepare.yml"
      vars:
        pod_prepare_title: "{{ pod_inner_title }} - main"
        pod_repo_dir: "{{ pod_main_repo_dir }}"
      tags: ["no_print"]

    - name: >-
        {{ pod_inner_title }} -
        update the file to verify if there was a change (for newer runs)
      become: "{{ pod_item.root }}"
      copy:
        remote_src: yes
        src: "{{ pod_backup_file_tmp }}"
        dest: "{{ pod_backup_file }}"
        owner: "{{ pod_host_user }}"
        group: "{{ pod_host_group }}"
        mode: "{{ (pod_node_local | bool) | ternary(0666, 0640) }}"
      when: not (pod_node_local | bool)
      tags: ["no_print_skipped"]

  when: >-
    (pod_item.fast_prepare | default(false, true) | bool) or
    (pod_diff | default({})).changed | default(false, true) | bool
  tags: ["no_print_skipped"]
