### Create / Update the repository ###

- name: "{{ pod_prepare_title }} - pod_prepare_repo"
  set_fact:
    pod_prepare_repo: >-
      {{ env.repos[pod_item.repo] }}
    pod_prepare_clone_repo: >-
      {{ (not (pod_node_local | bool)) or (pod_prepare_tmp | default(false) | bool) }}
  tags: ["no_print"]

- name: "{{ pod_prepare_title }} - pod - repo (outer)"
  include_tasks: "tasks/util/repo.yml"
  vars:
    repo_title: "{{ pod_prepare_title }} - pod - repo"
    repo_main: "{{ pod_prepare_repo }}"
    repo_ssh_src_dir: "{{ env_dir }}"
    repo_secrets_dir: "{{ pod_secrets_repos_dir }}/{{ pod_item.repo }}"
    repo_default_dir: "{{ pod_repo_dir }}"
    repo_dev_base_dir: "{{ env_dev_repos_dir }}"
    repo_root: "{{ pod_root | bool }}"
    repo_dev: "{{ (env_dev | bool) and (pod_node_local | bool) }}"
    repo_lax: "{{ env_lax }}"
  when: pod_prepare_clone_repo | bool
  tags: ["no_print"]

### Create the environment pod repositories in the env folders (when defined) ###

- name: "{{ pod_prepare_title }}"
  include_tasks: "tasks/pods/env_repos.yml"
  vars:
    pod_prepare_env_repo_name: "{{ pod_prepare_item.repo }}"
    pod_prepare_env_repo: >-
      {{ env.repos[pod_prepare_item.repo] }}
  loop: "{{ pod_item.env_repos | default([], true) }}"
  loop_control:
    loop_var: pod_prepare_item
    label: "{{ pod_prepare_item.repo }}"
  when: pod_prepare_clone_repo | bool
  tags: ["no_print"]

### Transfer the pod artifacts (when ctx is defined in the pod) ###

- name: "{{ pod_prepare_title }} - transfer (outer)"
  include_tasks: "tasks/pods/transfer.yml"
  vars:
    pod_transfer_title: "{{ pod_prepare_title }} - ctx"
  when: (pod_item.ctx | default('')) != ''
  tags: ["no_print_skipped"]

### Transfer the pod contents ###

- name: "{{ pod_prepare_title }} - transfer (outer)"
  include_tasks: "tasks/util/transfer.yml"
  vars:
    transfer_title: "{{ pod_prepare_title }} - transfer #{{ pod_prepare_idx + 1 }}"
    transfer_prepared: true
    transfer_content: "{{ pod_prepare_item.src }}"
    transfer_input:
      dependencies: "{{ pod_node_dependencies }}"
    transfer_dest: "{{ pod_repo_dir }}/{{ pod_prepare_item.dest }}"
    transfer_tmp_dest: "{{ pod_tmp_dir }}/{{ pod_prepare_item.dest }}"
    transfer_custom_dir: "{{ pod_item.local_dir }}"
    transfer_become: "{{ pod_root | bool }}"
    transfer_mode: "{{ pod_prepare_item.mode }}"
    transfer_dir_mode: "{{ pod_prepare_item.dir_mode }}"
  when: pod_prepare_item.when | default(true, true) | bool
  loop: "{{ pod_item.prepared_transfer | default([]) }}"
  loop_control:
    index_var: pod_prepare_idx
    loop_var: pod_prepare_item
    label: "{{ pod_prepare_idx }}"
  tags: ["no_print_skipped"]
