# get the pod vars

- name: "{{ pod_transfer_title }} - pod_vars"
  set_fact:
    pod_transfer_directories: "{{ pod_transfer_vars.directories }}"
    pod_transfer_templates: "{{ pod_transfer_vars.templates }}"
    pod_transfer_files: "{{ pod_transfer_vars.files }}"
  vars:
    pod_transfer_vars: >-
      {{
        lookup(
          'lrd.cloud.pod_vars',
          pod_item,
          env_data=env_data,
          dependencies_data=pod_dependencies_data,
        )
      }}
  tags: ["no_print"]

# create the directories

- name: "{{ pod_transfer_title }} - create the directories"
  become: "{{ pod_item.root }}"
  file:
    state: directory
    path: "{{ pod_transfer_item.path }}"
    owner: "{{ pod_host_user | default(omit, true) }}"
    group: "{{ pod_host_group | default(omit, true) }}"
    mode: "{{ pod_transfer_item.mode }}"
  loop: "{{ pod_transfer_directories | default([], true) }}"
  loop_control:
    loop_var: pod_transfer_item
    label: "{{ pod_transfer_item.path }}"
  tags: ["no_print_skipped"]

# transfer the templates

- name: >-
    {{ pod_transfer_title }} -
    transfer the templates to the specified tmp locations
  become: "{{ pod_item.root }}"
  template:
    src: "{{ pod_transfer_item.src }}"
    dest: "{{ pod_transfer_item.dest_tmp }}"
    owner: "{{ pod_host_user | default(omit, true) }}"
    group: "{{ pod_host_group | default(omit, true) }}"
    mode: "{{ pod_transfer_item.mode }}"
  vars:
    params: "{{ pod_transfer_item.params }}"
  loop: "{{ pod_transfer_templates | default([], true) }}"
  loop_control:
    loop_var: pod_transfer_item
    label: "{{ pod_transfer_item.dest_tmp }}"
  changed_when: false
  tags: ["no_print_skipped"]

- name: "{{ pod_transfer_title }} - pod_transfer_template_regex"
  set_fact:
    pod_transfer_template_regex: "^\\s*$"
  tags: ["no_print"]

- name: "{{ pod_transfer_title }} - pod_transfer_template_regex"
  set_fact:
    pod_transfer_template_regex: "\\n\\s*$"
  when: env.meta.template_no_empty_lines | default(false) | bool
  tags: ["no_print"]

- name: >-
    {{ pod_transfer_title }} -
    remove excess of blank lines of files created from the templates
  replace:
    path: "{{ pod_transfer_item.dest_tmp }}"
    regexp: "{{ pod_transfer_template_regex }}"
    replace: ""
  loop: "{{ pod_transfer_templates | default([], true) }}"
  loop_control:
    loop_var: pod_transfer_item
    label: "{{ pod_transfer_item.dest_tmp }}"
  changed_when: false
  tags: ["no_print_skipped"]

- name: >-
    {{ pod_transfer_title }} -
    copy the normalized files created from the templates
  become: "{{ pod_item.root }}"
  copy:
    remote_src: true
    src: "{{ pod_transfer_item.dest_tmp }}"
    dest: "{{ pod_transfer_item.dest }}"
    owner: "{{ pod_host_user | default(omit, true) }}"
    group: "{{ pod_host_group | default(omit, true) }}"
    mode: "{{ pod_transfer_item.mode }}"
  loop: "{{ pod_transfer_templates | default([], true) }}"
  loop_control:
    loop_var: pod_transfer_item
    label: "{{ pod_transfer_item.dest }}"
  tags: ["no_print_skipped"]

# transfer the files

- name: "{{ pod_transfer_title }} - copy the static files to the specified locations"
  become: "{{ pod_item.root }}"
  copy:
    remote_src: "{{ pod_transfer_item.remote_src | default(false) | bool }}"
    src: "{{ pod_transfer_item.src }}"
    dest: "{{ pod_transfer_item.dest }}"
    owner: "{{ pod_host_user | default(omit, true) }}"
    group: "{{ pod_host_group | default(omit, true) }}"
    mode: "{{ pod_transfer_item.mode }}"
  loop: "{{ pod_transfer_files | default([], true) }}"
  loop_control:
    loop_var: pod_transfer_item
    label: "{{ pod_transfer_item.dest }}"
  tags: ["no_print_skipped"]
