- set_fact: 
    test_vars:
      a: "123"
      boolean1: true
      xyz: "456"
      boolean3: true

- set_fact: { "test_var_{{ test_item.name }}": "{{ test_vars[test_item.name] | default(test_item.default) }}" }
  loop: 
  - { name: "a", default: "bcd" }
  - { name: "efg", default: "hij" }
  - { name: "boolean1", default: false }
  - { name: "obj", default: {} }
  - { name: "xyz", default: "abc" }
  - { name: "def", default: "ghi" }
  - { name: "boolean2", default: true }
  - { name: "boolean3", default: false }
  loop_control:
    loop_var: test_item
    label: "{{ test_item.name }} - {{ (test_vars[test_item.name] | default('---')) }}"

- debug:
    var: test_var_a
- debug:
    var: test_var_efg
- debug:
    var: test_var_boolean1
- debug:
    var: test_var_obj
- debug:
    var: test_var_xyz
- debug:
    var: test_var_def
- debug:
    var: test_var_boolean2
- debug:
    var: test_var_boolean3
    

- set_fact: { "discourse_run_{{ discourse_run_item.name }}": "{{ discourse_run_vars[discourse_run_item.name] | default(discourse_run_item.default) }}" }
  loop: 
  - { name: "name", default: "app" }
  - { name: "action", default: "rebuild" }
#   - { name: "vars", default: {} }
  - { name: "push", default: "false" }
#   - { name: "push_credentials", default: {} }
  - { name: "push_name", default: "" }
  - { name: "push_tag", default: "" }
  - { name: "output_path", default: "/tmp/main/discourse" }
  - { name: "output_file", default: "app.log" }
  - { name: "path", default: "/var/discourse" }
  loop_control:
    loop_var: discourse_run_item
    label: "{{ discourse_run_item.name }} - {{ (discourse_run_vars[discourse_run_item.name] | default('---')) }}"
    
- set_fact: 
    discourse_run_title: "discourse - {{ discourse_run_action }} {{ discourse_run_name }}"

# - name: "{{ discourse_run_title }} - main action"
#   include_role: 
#     name: long_run
#   vars:
#     long_run_title: "{{ discourse_run_title }}"
#     long_run_become: yes
#     long_run_output_path: "{{ discourse_run_output_path }}"
#     long_run_output_file: "{{ discourse_run_output_file }}"
#     long_run_path: "{{ discourse_run_path }}"
#     long_run_cmd: "./launcher {{ discourse_run_action }} {{ discourse_run_name }}"

- block:

    - name: "{{ discourse_run_title }} - log into docker registry"
      docker_login:
        registry: "{{ discourse_run_push_credentials.registry }}"
        username: "{{ discourse_run_push_credentials.username }}"
        password: "{{ discourse_run_push_credentials.password }}"
        reauthorize: "{{ discourse_run_push_credentials.reauthorize }}"

    - set_fact: 
        discourse_run_registry_prefix: "{{ discourse_run_push_credentials.registry | ternary(discourse_run_push_credentials.registry + '/', '') }}"
        discourse_run_push_owner_prefix: "{{ discourse_run_push_owner | ternary(discourse_run_push_owner + '/', '') }}"

    - set_fact:
        discourse_run_push_repository: "{{ discourse_run_registry_prefix }}{{ discourse_run_push_owner_prefix }}{{ discourse_run_push_name }}:{{ discourse_run_push_tag }}"

    # - name: "{{ discourse_run_title }} - tag and push to docker registry"
    #   docker_image:
    #     name: "{{ discourse_run_name }}"
    #     repository: "{{ discourse_run_push_repository }}"
    #     push: yes

  when: discourse_run_push_condition