- name: "{{ env_title }} - generate the context vars"
  lrd.cloud.ctx:
    ctx_name: "{{ env_ctx_name }}"
    env_data: "{{ env_data }}"
    validate: "{{ ctx_validate | default(false) | bool }}"
  register: ctx_data_result

- name: "{{ env_title }} - ctx_data"
  set_fact:
    ctx_data: "{{ ctx_data_result.data }}"
  tags: ["no_print"]

- name: "{{ env_title }} - env_ctx"
  set_fact:
    env_ctx: "{{ ctx_data }}"
    env_ctx_params: "{{ ctx_data.params | default({}) }}"
  tags: ["no_print"]
