- name: "{{ env_title }} - generate the context vars"
  set_fact:
    ctx_data: >-
      {{
        lookup(
          'lrd.cloud.ctx',
          env_ctx_name,
          env_data=env_data,
          validate=(ctx_validate | default(false) | bool)
        )
      }}
