- name: "{{ env_title | default('[env] setup') }} - gathering facts"
  setup:
  when: init_run_setup | default(false) | bool
  tags: ["no_print_skipped"]

- name: "env (outer)"
  include_tasks: "tasks/util/env.yml"
  vars:
    env_stage_title: "main"
  when: env is not defined
  tags: ["no_print"]

- name: "{{ env_title }} - init_failed_hosts"
  set_fact:
    init_failed_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
  tags: ["no_print"]

- name: "{{ env_title }} - ctx (outer)"
  include_tasks: "tasks/util/ctx.yml"
  when: ctx is not defined
  tags: ["no_print"]

- name: "{{ env_title }} - fail when localhost failed"
  fail:
    msg: "localhost (in ansible group 'main') failed"
  when: "'localhost' in init_failed_hosts"
  tags: ["no_print_skipped"]

- name: "{{ env_title }} - hosts data (outer)"
  include_tasks: "tasks/util/hosts_data.yml"
  when: >-
    (init_load_node_dependencies | default(false) | bool)
    and
    (ctx_node_dependencies is not defined)
    and
    (ctx_data.has_node_dependency | default(false) | bool)
  tags: ["no_print"]

- name: "{{ env_title }} - generate the node dependencies"
  set_fact:
    ctx_node_dependencies: >-
      {{
        ctx_data.node_dependencies
        | lrd.cloud.node_dependencies(
          ctx_hosts_data | default({}),
          instance_type=instance_type
        )
      }}
  when: >-
    (init_load_node_dependencies | default(false) | bool)
    and
    (ctx_node_dependencies is not defined)
  tags: ["no_print"]

- debug:
    var: ctx_node_dependencies
  when: >-
    (init_load_node_dependencies | default(false) | bool)
  tags: ["no_print_skipped"]
