- name: "{{ env_title | default('[env] setup') }} - gathering facts"
  setup:
  when: init_run_setup | default(false) | bool
  tags: ["no_print_skipped"]

- name: "env (outer)"
  include_tasks: "tasks/util/env.yml"
  vars:
    env_stage_title: "main"
  when: env is not defined
  tags: ["no_print"]

- name: "{{ env_title }} - init_failed_hosts"
  set_fact:
    init_failed_hosts: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
  tags: ["no_print"]

- name: "{{ env_title }} - ctx (outer)"
  include_tasks: "tasks/util/ctx.yml"
  when: ctx is not defined
  tags: ["no_print"]

- name: "{{ env_title }} - fail when localhost failed"
  fail:
    msg: "localhost (in ansible group 'main') failed"
  when: "'localhost' in init_failed_hosts"
  tags: ["no_print_skipped"]

- name: "{{ env_title }} - hosts data (outer)"
  include_tasks: "tasks/util/hosts_data.yml"
  when: >-
    (init_load_hosts_data | default(false) | bool)
    and
    (ctx_node_dependencies is not defined)
  tags: ["no_print"]
