- name: "{{ repo_validate_title }} - validate the repo"
  fail:
    msg: "Repository should be defined as a dictionary: {{ repo_validate_repo }}"
  when: not (repo_validate_repo is mapping)
  tags: ["no_print_skipped"]

- name: "{{ repo_validate_title }} - repo_validate_allowed_props"
  set_fact:
    repo_validate_allowed_props:
      - "src"
      - "version"
      - "ssh_file"
      - "ssh_file_encrypted"
  tags: ["no_print"]

- name: "{{ repo_validate_title }} - validate the repo allowed props"
  fail:
    msg: |
      Invalid property defined for the repository
      Property: {{ tmp_item }}
      Allowed:
      {{ repo_validate_allowed_props | to_nice_yaml }}
      Item Keys:
      {{ repo_validate_repo | to_nice_yaml }}
  when: tmp_item not in repo_validate_allowed_props
  loop: "{{ repo_validate_repo | dict2items | map(attribute='key') | sort | list }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]

- name: "{{ repo_validate_title }} - repo_validate_required_props"
  set_fact:
    repo_validate_required_props:
      - "src"
  tags: ["no_print"]

- name: "{{ repo_validate_title }} - validate the repo required props"
  fail:
    msg: |
      Required property not defined for the repository
      Property: {{ tmp_item }}
      Required:
      {{ repo_validate_required_props | to_nice_yaml }}
      Item Keys:
      {{ repo_validate_repo | to_nice_yaml }}
  when: tmp_item not in repo_validate_repo
  loop: "{{ repo_validate_required_props }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]

- name: "{{ repo_validate_title }} - repo_validate_str_props"
  set_fact:
    repo_validate_str_props:
      - "src"
      - "version"
      - "ssh_file"
  tags: ["no_print"]

- name: "{{ repo_validate_title }} - validate the repo string props"
  fail:
    msg: "Repository property should be a string: {{ tmp_item }}"
  when: >-
    (repo_validate_repo[tmp_item] is defined) and not (repo_validate_repo[tmp_item] is string)
  loop: "{{ repo_validate_str_props }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]
