- name: "{{ transfer_title }} - transfer_prepared_content"
  set_fact:
    transfer_prepared_content: "{{ transfer_content }}"
  tags: ["no_print"]

# Prepare (if needed)

- name: "{{ transfer_title }} - prepare the content"
  set_fact:
    transfer_prepared_content: >-
      {{
        lookup(
          'lrd.cloud.prepare_content',
          transfer_content,
          env_data=env_data,
          env=transfer_env | default(env, true),
          input=transfer_input | default(omit, true),
          custom_dir=transfer_custom_dir | default(''),
          validate=transfer_validate | default(true, true),
        )
      }}
  when: not (transfer_prepared | default(false) | bool)
  tags: ["no_print"]

- name: "{{ transfer_title }} - define transfer input"
  set_fact:
    transfer_input: "{{ transfer_prepared_content.input }}"
  when: >-
    (transfer_prepared_content.type == 'template')
    and
    (transfer_input is not defined)
    and
    (transfer_prepared_content.input is defined)
  tags: ["no_print"]

- name: "{{ transfer_title }} - prepare the content"
  fail:
    msg: |
      invalid prepared content type:
      type: {{ transfer_prepared_content.type }}
      allowed: {{ tmp_allowed | to_json }}
  vars:
    tmp_allowed: ["file", "template", "str"]
  when: transfer_prepared_content.type not in tmp_allowed
  tags: ["no_print"]

# Create the destination directory

- name: "{{ transfer_title }} - create the directory {{ transfer_dest | dirname }}"
  become: "{{ transfer_become | default(false) | bool }}"
  file:
    path: "{{ transfer_dest | dirname }}"
    state: directory
    mode: "{{ transfer_dir_mode | default(omit, true) }}"
  tags: ["no_print"]

- name: "{{ transfer_title }} - create the tmp directory {{ transfer_tmp_dest | dirname }}"
  become: "{{ transfer_become | default(false) | bool }}"
  file:
    path: "{{ transfer_tmp_dest | dirname }}"
    state: directory
    mode: "{{ transfer_dir_mode | default(omit, true) }}"
  when: transfer_prepared_content.type == 'template'
  tags: ["no_print"]

# String

- name: "{{ transfer_title }} - copy the string content to {{ transfer_dest }}"
  become: "{{ transfer_become | default(false) | bool }}"
  copy:
    content: "{{ transfer_prepared_content.params.value }}"
    dest: "{{ transfer_dest }}"
    owner: "{{ transfer_user | default(omit, true) }}"
    group: "{{ transfer_group | default(omit, true) }}"
    mode: "{{ transfer_mode | default(omit, true) }}"
  register: transfer_diff
  when: transfer_prepared_content.type == 'str'
  tags: ["no_print_skipped"]

# File

- name: "{{ transfer_title }} - copy the file content to {{ transfer_dest }}"
  become: "{{ transfer_become | default(false) | bool }}"
  copy:
    src: "{{ transfer_prepared_content.file }}"
    dest: "{{ transfer_dest }}"
    owner: "{{ transfer_user | default(omit, true) }}"
    group: "{{ transfer_group | default(omit, true) }}"
    mode: "{{ transfer_mode | default(omit, true) }}"
  register: transfer_diff
  when: transfer_prepared_content.type == 'file'
  tags: ["no_print_skipped"]

# Template

- name: >-
    {{ transfer_title }} - copy the template content to
    the temporary destination ({{ transfer_tmp_dest }})
  become: "{{ transfer_become | default(false) | bool }}"
  template:
    src: "{{ transfer_prepared_content.file }}"
    dest: "{{ transfer_tmp_dest }}"
    owner: "{{ transfer_user | default(omit, true) }}"
    group: "{{ transfer_group | default(omit, true) }}"
    mode: "{{ transfer_mode | default(omit, true) }}"
  vars:
    input: "{{ transfer_input | default({}) }}"
    params: "{{ transfer_prepared_content.params | default({}) }}"
    credentials: "{{ transfer_prepared_content.credentials | default({}) }}"
    contents: "{{ transfer_prepared_content.contents | default({}) }}"
  when: transfer_prepared_content.type == 'template'
  changed_when: false
  tags: ["no_print_skipped"]

- name: "{{ transfer_title }} - transfer_template_regex"
  set_fact:
    transfer_template_regex: "^\\s*$"
  when: transfer_prepared_content.type == 'template'
  tags: ["no_print"]

- name: "{{ transfer_title }} - transfer_template_regex"
  set_fact:
    transfer_template_regex: "\\n\\s*$"
  when: >-
    (transfer_prepared_content.type == 'template')
    and
    (env.meta.template_no_empty_lines | default(false) | bool)
  tags: ["no_print"]

- name: >-
    {{ transfer_title }} -
    remove excess of blank lines of the file created from the template
  replace:
    path: "{{ transfer_tmp_dest }}"
    regexp: "{{ transfer_template_regex }}"
    replace: ""
  when: transfer_prepared_content.type == 'template'
  changed_when: false
  tags: ["no_print_skipped"]

- name: >-
    {{ transfer_title }} -
    copy the normalized file created from the template
    to {{ transfer_dest }}
  become: "{{ transfer_become | default(false) | bool }}"
  copy:
    remote_src: true
    src: "{{ transfer_tmp_dest }}"
    dest: "{{ transfer_dest }}"
    owner: "{{ transfer_user | default(omit, true) }}"
    group: "{{ transfer_group | default(omit, true) }}"
    mode: "{{ transfer_mode | default(omit, true) }}"
  when: transfer_prepared_content.type == 'template'
  register: transfer_diff
  tags: ["no_print_skipped"]
