- name: "{{ cloud_service_title }} - validate entrypoint service (must be a list)"
  fail:
    msg: "the cloud service list is not defined"
  when: cloud_service_list is not defined

- name: "{{ cloud_service_title }} - validate the cloud service state (required)"
  fail:
    msg: "the cloud service state is not defined"
  when: (cloud_service_state | default('')) == ''

- name: "{{ cloud_service_title }} - validate the cloud service state (value)"
  fail:
    msg: "the cloud service state ({{ cloud_service_state }}) should be either 'present' or 'absent'"
  when: not (cloud_service_state in ['present', 'absent'])

- name: "{{ cloud_service_title }} - cloud_service_main_list"
  set_fact:
    cloud_service_main_list: []
    cloud_service_pending_list: []
    cloud_service_name_list: []
    cloud_service_pending_idx: 0
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - cloud_service_inner"
  set_fact:
    cloud_service_inner_title: "{{ cloud_service_title }}"
    cloud_service_inner_info: ""
    cloud_service_inner_name: ""
    cloud_service_inner_prev_name: ""
    cloud_service_inner:
      list: true
      services: "{{ cloud_service_list }}"
    cloud_service_inner_type: ""
    cloud_service_inner_tmp_dir: "{{ cloud_service_tmp_dir }}/main"
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - recursive services"
  include_tasks: "tasks/services/cloud_service_recursive.yml"
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_title }} - execute the service(s)"
  include_tasks: "{{ cloud_service_base_dir_prefix }}{{ cloud_service_type }}.yml"
  vars:
    cloud_service_title: "{{ cloud_service_item.title }}"
    cloud_service_name: "{{ cloud_service_item.name }}"
    cloud_service_type: "{{ cloud_service_item.type }}"
    cloud_service_params: "{{ cloud_service_item.params }}"
    cloud_service_credentials: "{{ cloud_service_item.credentials }}"
    cloud_service_base_dir_prefix: "{{ cloud_service_item.base_dir_prefix }}"
    cloud_service_tmp_dir: "{{ cloud_service_item.tmp_dir }}"
  loop: "{{ cloud_service_main_list }}"
  loop_control:
    loop_var: cloud_service_item
    label: "{{ cloud_service_item.name }}"
