# https://github.com/ansible/ansible/issues/64883
- name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_map"
  set_fact:
    cloud_service_inner_info_map: >-
      {{ (cloud_service_inner_info is mapping) | ternary(cloud_service_inner_info, {}) }}
  tags: ["no_print"]

- name: "{{ cloud_service_inner_title }} - top service info (may have a tmp property)"
  block:
    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_has_tmp"
      set_fact:
        cloud_service_inner_info_has_tmp: "{{ cloud_service_inner_info_map.tmp is defined }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - remove tmp property"
      block:
        - name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_map_aux"
          set_fact:
            cloud_service_inner_info_map_aux: {}
          tags: ["no_print"]

        - set_fact:
            cloud_service_inner_info_map_aux: >-
              {{ cloud_service_inner_info_map_aux | combine({ tmp_item.key: tmp_item.value }) }}
          when: not (tmp_item.key in ['tmp'])
          loop: "{{ cloud_service_inner_info_map | dict2items | list }}"
          loop_control:
            loop_var: tmp_item
            label: "{{ tmp_item.key }}"
          tags: ["no_print"]

        - name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_map_aux"
          set_fact:
            cloud_service_inner_info_map: "{{ cloud_service_inner_info_map_aux }}"
          tags: ["no_print"]

      when: cloud_service_inner_info_has_tmp | bool

  when: (cloud_service_inner_info is mapping) and (cloud_service_inner_prev_name == '')
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_inner_title }} - service list"
  block:
    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_allowed_props"
      set_fact:
        cloud_service_inner_allowed_props:
          - "list"
          - "services"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - validate the cloud service list props"
      fail:
        msg: |
          Invalid property defined for service list
          Property: {{ cloud_service_inner_item.key }}
          Allowed:
          {{ cloud_service_inner_allowed_props | to_nice_yaml }}
          Item:
          {{ cloud_service_inner | to_nice_yaml }}
      when: cloud_service_inner_item.key not in cloud_service_inner_allowed_props
      loop: "{{ cloud_service_inner | dict2items | list }}"
      loop_control:
        loop_var: cloud_service_inner_item
        label: "{{ cloud_service_inner_item.key }}"
      tags: ["no_print_skipped"]

    - name: "{{ cloud_service_inner_title }} - validate the cloud service list info props (outer)"
      block:
        - name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_allowed_props"
          set_fact:
            cloud_service_inner_info_allowed_props:
              - "name"
              - "key"
          tags: ["no_print"]

        - name: "{{ cloud_service_inner_title }} - validate the cloud service list info props"
          fail:
            msg: |
              Invalid property defined for service list info
              Property: {{ cloud_service_inner_item.key }}
              Allowed:
              {{ cloud_service_inner_info_allowed_props | to_nice_yaml }}
              Item:
              {{ cloud_service_inner_info_map | to_nice_yaml }}
          when: cloud_service_inner_item.key not in cloud_service_inner_info_allowed_props
          loop: "{{ cloud_service_inner_info_map | dict2items | list }}"
          loop_control:
            loop_var: cloud_service_inner_item
            label: "{{ cloud_service_inner_item.key }}"
          tags: ["no_print_skipped"]

      when: cloud_service_inner_info is mapping
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_pending_list_aux"
      set_fact:
        cloud_service_pending_list_aux: []
        cloud_service_inner_pending_list_aux: []
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_pending_list_aux - fill first"
      set_fact:
        cloud_service_pending_list_aux: >-
          {{ cloud_service_pending_list_aux + [cloud_service_pending_list[tmp_item_idx]] }}
      loop: "{{ range(0, cloud_service_pending_idx | int) | list }}"
      loop_control:
        index_var: tmp_idx
        loop_var: tmp_item_idx
        label: "{{ tmp_idx }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - define services to add (list)"
      set_fact:
        cloud_service_inner_pending_list_aux: "{{ cloud_service_inner_pending_list_aux + [tmp_service_to_add] }}"
      vars:
        tmp_info: "{{ tmp_item }}"
        tmp_name: "{{ tmp_info.name | default(tmp_info) | default('') }}"
        tmp_key: >-
          {{
            tmp_info.key
            | default(tmp_info.name)
            | default(tmp_info)
            | default('')
          }}
        tmp_title: "{{ cloud_service_title }} - service item [{{ tmp_name }}]"
        tmp_tmp_dir: "{{ cloud_service_tmp_dir }}/inner/{{ tmp_name }}"
        tmp_service_to_add:
          title: "{{ tmp_title }}"
          name: "{{ tmp_name }}"
          key: "{{ tmp_key }}"
          info: "{{ tmp_info }}"
          tmp_dir: "{{ tmp_tmp_dir }}"
          prev_name: "{{ cloud_service_inner_name }}"
      loop: "{{ cloud_service_inner.services | default([]) | list }}"
      loop_control:
        loop_var: tmp_item
        label: "{{ tmp_name }}"
      tags: ["no_print_skipped"]

    - name: "{{ cloud_service_inner_title }} - reverse order"
      set_fact:
        cloud_service_inner_pending_list_aux: >-
          {{ cloud_service_inner_pending_list_aux | reverse | list }}
      when: cloud_service_state == 'absent'
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - add services (list)"
      set_fact:
        cloud_service_pending_list_aux: >-
          {{ cloud_service_pending_list_aux + cloud_service_inner_pending_list_aux }}
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_pending_list_aux - fill last"
      set_fact:
        cloud_service_pending_list_aux: >-
          {{ cloud_service_pending_list_aux + [cloud_service_pending_list[tmp_item_idx]] }}
      loop: "{{ range(cloud_service_pending_idx | int, cloud_service_pending_list | length) | list }}"
      loop_control:
        index_var: tmp_idx
        loop_var: tmp_item_idx
        label: "{{ tmp_idx }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_pending_list"
      set_fact:
        cloud_service_pending_list: "{{ cloud_service_pending_list_aux }}"
      tags: ["no_print"]

  when: cloud_service_inner.list | default(false) | bool

- name: "{{ cloud_service_inner_title }} - service item"
  block:
    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_base_dir_prefix"
      set_fact:
        cloud_service_inner_base_dir_prefix: >-
          {{ (tmp_base_dir != '') | ternary(tmp_base_dir + '/', '') }}
      vars:
        tmp_base_dir: "{{ cloud_service_inner.base_dir | default('') }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - validate the cloud service type"
      fail:
        msg: "cloud service type not defined"
      when: (cloud_service_inner_type | default('')) == ''
      tags: ["no_print_skipped"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_allowed_props"
      set_fact:
        cloud_service_inner_allowed_props:
          - "list"
          - "base_dir"
          - "type"
          - "credentials"
          - "params"
          - "group_params"
          - "shared_params"
          - "shared_group_params"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - validate the cloud service props"
      fail:
        msg: |
          Invalid property defined for service
          Property: {{ cloud_service_inner_item.key }}
          Allowed:
          {{ cloud_service_inner_allowed_props | to_nice_yaml }}
          Item:
          {{ cloud_service_inner | to_nice_yaml }}
      when: cloud_service_inner_item.key not in cloud_service_inner_allowed_props
      loop: "{{ cloud_service_inner | dict2items | list }}"
      loop_control:
        loop_var: cloud_service_inner_item
        label: "{{ cloud_service_inner_item.key }}"
      tags: ["no_print_skipped"]

    - name: "{{ cloud_service_inner_title }} - validate the cloud service info props (outer)"
      block:
        - name: "{{ cloud_service_inner_title }} - cloud_service_inner_info_allowed_props"
          set_fact:
            cloud_service_inner_info_allowed_props:
              - "name"
              - "key"
              - "params"
              - "group_params"
              - "shared_params"
              - "shared_group_params"
          tags: ["no_print"]

        - name: "{{ cloud_service_inner_title }} - validate the cloud service info props"
          fail:
            msg: |
              Invalid property defined for service info
              Property: {{ cloud_service_inner_item.key }}
              Allowed:
              {{ cloud_service_inner_info_allowed_props | to_nice_yaml }}
              Item:
              {{ cloud_service_inner_info_map | to_nice_yaml }}
          when: cloud_service_inner_item.key not in cloud_service_inner_info_allowed_props
          loop: "{{ cloud_service_inner_info_map | dict2items | list }}"
          loop_control:
            loop_var: cloud_service_inner_item
            label: "{{ cloud_service_inner_item.key }}"
          tags: ["no_print_skipped"]

      when: cloud_service_inner_info is mapping
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - generate credentials params (outer)"
      include_tasks: "tasks/util/params_mixer.yml"
      vars:
        params_mixer_title: "{{ cloud_service_inner_title }} - generate credentials params"
        params_mixer_main_params: {}
        params_mixer_group_params_names: "{{ cloud_service_inner.credentials | default({}) }}"
        params_mixer_shared_params_names: []
        params_mixer_shared_params_names_dict: {}
        params_mixer_shared_group_params_name: ""
        params_mixer_shared_group_params_names_dict: {}
        params_mixer_params_dict: "{{ env.credentials }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_credentials"
      set_fact:
        cloud_service_inner_credentials: "{{ params_mixer_params }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - generate service params (outer)"
      include_tasks: "tasks/util/params_mixer.yml"
      vars:
        params_mixer_title: "{{ cloud_service_inner_title }} - generate service params"
        params_mixer_main_params: "{{ cloud_service_inner.params | default({}) }}"
        params_mixer_group_params_names: "{{ cloud_service_inner.group_params | default({}) }}"
        params_mixer_shared_params_names: "{{ cloud_service_inner.shared_params | default([]) }}"
        params_mixer_shared_group_params_name: "{{ cloud_service_inner.shared_group_params | default('') }}"
        params_mixer_shared_params_names_dict: "{{ env.service_shared_params | default({}) }}"
        params_mixer_shared_group_params_names_dict: "{{ env.service_shared_group_params | default({}) }}"
        params_mixer_params_dict: "{{ env.service_group_params | default({}) }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_params"
      set_fact:
        cloud_service_inner_params: "{{ params_mixer_params }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - generate service ctx params (outer)"
      include_tasks: "tasks/util/params_mixer.yml"
      vars:
        params_mixer_title: "{{ cloud_service_inner_title }} - generate service ctx params"
        params_mixer_main_params: "{{ cloud_service_inner_info.params | default({}) }}"
        params_mixer_group_params_names: "{{ cloud_service_inner_info.group_params | default({}) }}"
        params_mixer_shared_params_names: "{{ cloud_service_inner_info.shared_params | default([]) }}"
        params_mixer_shared_group_params_name: "{{ cloud_service_inner_info.shared_group_params | default('') }}"
        params_mixer_shared_params_names_dict: "{{ env.service_shared_params | default({}) }}"
        params_mixer_shared_group_params_names_dict: "{{ env.service_shared_group_params | default({}) }}"
        params_mixer_params_dict: "{{ env.service_group_params | default({}) }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_ctx_params"
      set_fact:
        cloud_service_inner_ctx_params: "{{ params_mixer_params }}"
      tags: ["no_print"]

    - name: "{{ cloud_service_inner_title }} - cloud_service_inner_item_to_add"
      set_fact:
        cloud_service_main_list: "{{ cloud_service_main_list + [tmp_service_to_add] }}"
      vars:
        tmp_service_to_add:
          title: "{{ cloud_service_inner_title }}"
          name: "{{ cloud_service_inner_name }}"
          type: "{{ cloud_service_inner_type }}"
          params: "{{ cloud_service_inner_params | combine(cloud_service_inner_ctx_params) }}"
          credentials: "{{ cloud_service_inner_credentials }}"
          base_dir_prefix: "{{ cloud_service_inner_base_dir_prefix }}"
          tmp_dir: "{{ cloud_service_inner_tmp_dir }}"
      tags: ["no_print"]

  when: >-
    (cloud_service_inner_type != 'skip')
    and
    (not (cloud_service_inner.list | default(false) | bool))
