- name: "{{ validate_dict_title }} - validate_dict_error_msgs"
  set_fact:
    validate_dict_error_msgs: []
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - validate_dict_error_msgs - block"
  block:
    - name: "{{ validate_dict_title }} - undefined dictionary value"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + [tmp_msg] }}
      vars:
        tmp_msg: >-
          Value of <{{ validate_dict_ctx }}> is not defined
      when: validate_dict_value is not defined
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_dict_type"
      set_fact:
        validate_dict_type: "{{ validate_dict_schema_info.type | default('') }}"
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - wrong type (dict expected)"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + [tmp_msg] }}
      vars:
        tmp_msg: "Type of <{{ validate_dict_ctx }}> should be a dict (no type found)"
      when: validate_dict_type == ''
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - wrong type (dict expected)"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + [tmp_msg] }}
      vars:
        tmp_msg: >-
          Type of <{{ validate_dict_ctx }}> should be a dict
          (<{{ validate_dict_type }}> found)
      when: not (validate_dict_type in ['dict', 'string_or_dict'])
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_dict_allowed_props"
      set_fact:
        validate_dict_allowed_props:
          - "type"
          - "props"
          - "non_empty"
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate the dict allowed schema props"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + [tmp_msg] }}
      vars:
        tmp_msg: |
          Invalid property defined for the schema (dict).
          Type: {{ validate_prop_type }}
          Context: {{ validate_dict_ctx }}
          Property: {{ tmp_item }}
          Allowed: {{ validate_dict_allowed_props | to_json }}
      when: tmp_item not in validate_dict_allowed_props
      loop: >-
        {{
          validate_dict_schema_info | default({})
          | dict2items | map(attribute='key') | sort | list
        }}
      loop_control:
        loop_var: tmp_item
        label: "{{ tmp_item }}"
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_dict_required_props"
      set_fact:
        validate_dict_required_props:
          - "type"
          - "props"
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate the dict required props"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + [tmp_msg] }}
      vars:
        tmp_msg: "Required property at <{{ validate_dict_ctx }}> not defined: {{ tmp_item }}"
        tmp_schema_info: validate_dict_schema_info.props[tmp_item]
      when: >-
        (tmp_schema_info.required | default(false) | bool)
        and
        (validate_dict_value is mapping)
        and
        (validate_dict_value[tmp_item] is not defined)
      loop: >-
        {{
          validate_dict_schema_info.props | default({})
          | dict2items | map(attribute='key') | sort | list
        }}
      loop_control:
        loop_var: tmp_item
        label: "{{ tmp_item }}"
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_elem_error_msgs - initial"
      set_fact:
        validate_elem_error_msgs: []
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate the dictionary"
      include_tasks: "tasks/validate/elem.yml"
      vars:
        validate_elem_title: >-
          {{ validate_dict_title }} - dictionary
          - schema [{{ validate_dict_schema_name }}]
        validate_elem_ctx: "{{ validate_dict_ctx }}"
        validate_elem_type: "{{ validate_dict_type }}"
        validate_elem_schema: ""
        validate_elem_value: "{{ validate_dict_value }}"
        validate_elem_non_empty: "{{ validate_dict_schema_info.non_empty | default(false) }}"
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_dict_error_msgs - elem"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + validate_elem_error_msgs }}
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate_dict_value_dict"
      set_fact:
        validate_dict_value_dict: {}
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate_dict_value_dict"
      set_fact:
        validate_dict_value_dict: "{{ validate_dict_value }}"
      when: validate_dict_value is mapping
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate_prop_error_msgs_cumulative"
      set_fact:
        validate_prop_error_msgs_cumulative: []
      tags: ["no_print"]

    - name: "{{ validate_dict_title }} - validate the props"
      include_tasks: "tasks/validate/prop.yml"
      vars:
        validate_prop_title: "{{ validate_dict_title }} - prop [{{ validate_dict_item }}]"
        validate_prop_ctx: >-
          {{
            (validate_dict_ctx != '')
            | ternary(
              validate_dict_ctx + '.' + validate_dict_item,
              validate_dict_item
            )
          }}
        validate_prop_value: "{{ validate_dict_value[validate_dict_item] }}"
        validate_prop_schema_info: >-
          {{ validate_dict_schema_info.props[validate_dict_item] | default({}) }}
      loop: >-
        {{
          validate_dict_value_dict
          | dict2items | map(attribute='key')
          | sort | list
        }}
      loop_control:
        loop_var: validate_dict_item
        label: "{{ validate_dict_item }}"
      tags: ["no_print_skipped"]

    - name: "{{ validate_dict_title }} - validate_dict_error_msgs - props"
      set_fact:
        validate_dict_error_msgs: >-
          {{ validate_dict_error_msgs + validate_prop_error_msgs_cumulative }}
      tags: ["no_print"]
  when: (validate_dict_error_msgs | length) == 0
