- name: "{{ validate_dict_title }} - undefined dictionary value"
  fail:
    msg: >-
      Value of <{{ validate_dict_ctx }}> is not defined
  when: validate_dict_value is not defined
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate_dict_type"
  set_fact:
    validate_dict_type: "{{ validate_dict_schema_info.type | default('') }}"
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - wrong type (dict expected)"
  fail:
    msg: "Type of <{{ validate_dict_ctx }}> should be a dict (no type found)"
  when: validate_dict_type == ''
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - wrong type (dict expected)"
  fail:
    msg: >-
      Type of <{{ validate_dict_ctx }}> should be a dict
      (<{{ validate_dict_type }}> found)
  when: not (validate_dict_type in ['dict', 'string_or_dict'])
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate_dict_allowed_props"
  set_fact:
    validate_dict_allowed_props:
      - "type"
      - "any_props"
      - "props"
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - validate the dict allowed schema props"
  fail:
    msg: |
      Invalid property defined for the schema (type dict).
      Property: {{ tmp_item }}
      Allowed: {{
        validate_dict_schema_info.props | default({})
        | dict2items | map(attribute='key')
        | sort | list | to_json
      }}
  when: tmp_item not in validate_dict_allowed_props
  loop: >-
    {{
      validate_dict_schema_info.props | default({})
      | dict2items | map(attribute='key') | sort | list
    }}
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate_dict_required_props"
  set_fact:
    validate_dict_required_props:
      - "type"
      - "any_props"
      - "props"
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - validate the dict required props"
  fail:
    msg: "Required propert at <validate_dict_ctx> not defined: {{ tmp_item }}"
  vars:
    tmp_schema_info: validate_dict_schema_info.props[tmp_item]
  when: >-
    (tmp_schema_info.required | default(false) | bool)
    and
    (validate_dict_prop_value is mapping)
    and
    (validate_dict_prop_value[tmp_item] is not defined)
  loop: >-
    {{
      validate_dict_schema_info.props | default({})
      | dict2items | map(attribute='key') | sort | list
    }}
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate the dict schema props"
  fail:
    msg: >-
      Schema has any_props (= true) and any_props properties
      (choose only one)
  when: >-
    (validate_dict_schema_info.any_props | default(false) | bool)
    and
    (validate_dict_schema_info.props is defined)
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate the dictionary"
  include_tasks: "tasks/validate/elem.yml"
  vars:
    validate_elem_title: >-
      {{ validate_dict_title }} - dictionary
      - schema [{{ validate_dict_schema_name }}]
    validate_elem_ctx: "{{ validate_dict_ctx }}"
    validate_elem_type: "{{ validate_dict_type }}"
    validate_elem_schema: ""
    validate_elem_value: "{{ validate_dict_value }}"
  tags: ["no_print_skipped"]

- name: "{{ validate_dict_title }} - validate_dict_prop_value_dict"
  set_fact:
    validate_dict_prop_value_dict: {}
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - validate_dict_prop_value_dict"
  set_fact:
    validate_dict_prop_value_dict: "{{ validate_dict_prop_value }}"
  when: >-
    (validate_dict_prop_value is mapping)
    and
    (not (validate_dict_schema_info.any_props | default(false) | bool))
  tags: ["no_print"]

- name: "{{ validate_dict_title }} - validate the props"
  include_tasks: "tasks/validate/prop.yml"
  vars:
    validate_dict_prop_value: "{{ validate_dict_value[validate_dict_item] }}"
    validate_prop_title: "{{ validate_dict_title }} - prop [{{ validate_dict_item }}]"
    validate_prop_ctx: >-
      {{
        (validate_dict_ctx != '')
        | ternary(
          validate_dict_ctx + '.' + validate_dict_item,
          validate_dict_item
        )
      }}
    validate_prop_value: "{{ validate_dict_prop_value }}"
    validate_prop_schema_info: >-
      {{ validate_dict_schema_info.props[validate_dict_item] | default({}) }}
  loop: >-
    {{
      validate_dict_prop_value_dict
      | dict2items | map(attribute='key')
      | sort | list
    }}
  loop_control:
    loop_var: validate_dict_item
    label: "{{ validate_dict_idx }}"
  tags: ["no_print_skipped"]
