- name: "{{ validate_list_title }} - wrong type (list expected)"
  fail:
    msg: "Value <{{ validate_list_ctx }}> should be a list"
  when: validate_list_type != 'list'
  tags: ["no_print_skipped"]

- name: "{{ validate_list_title }} - validate_list_allowed_props"
  set_fact:
    validate_list_allowed_props:
      - "type"
      - "elem_type"
      - "elem_schema"
  tags: ["no_print"]

- name: "{{ validate_list_title }} - validate the list allowed schema props"
  fail:
    msg: |
      Invalid property defined for the schema (type list).
      Context: {{ validate_list_ctx }}
      Property: {{ tmp_item }}
      Allowed: {{ validate_list_allowed_props | to_json }}
  when: tmp_item not in validate_list_allowed_props
  loop: "{{ validate_list_schema_info | dict2items | map(attribute='key') | sort | list }}"
  loop_control:
    loop_var: tmp_item
    label: "{{ tmp_item }}"
  tags: ["no_print_skipped"]

- name: "{{ validate_list_title }} - validate the allowed schema props"
  fail:
    msg: >-
      Schema for <{{ validate_list_ctx }}> has elem_type and elem_schema
      properties (choose only one)
  when: >-
    (validate_list_schema_info.elem_type is defined)
    and
    (validate_list_schema_info.elem_schema is defined)
  tags: ["no_print_skipped"]

- name: "{{ validate_list_title }} - validate the list"
  include_tasks: "tasks/validate/elem.yml"
  vars:
    validate_elem_title: "{{ validate_list_title }}"
    validate_elem_ctx: "{{ validate_list_ctx }}"
    validate_elem_type: "{{ validate_list_type }}"
    validate_elem_schema: ""
    validate_elem_value: "{{ validate_list_value }}"
  tags: ["no_print_skipped"]

- name: "{{ validate_list_title }} - validate the list items"
  include_tasks: "tasks/validate/elem.yml"
  vars:
    validate_elem_title: "{{ validate_list_title }} - list item"
    validate_elem_ctx: "{{ validate_list_ctx }}[{{ validate_list_idx }}]"
    validate_elem_type: "{{ validate_list_item.elem_type | default('') }}"
    validate_elem_schema: "{{ validate_list_item.elem_schema | default('') }}"
    validate_elem_value: "{{ validate_list_item }}"
  loop: "{{ validate_list_value }}"
  loop_control:
    loop_index: validate_list_idx
    loop_var: validate_list_item
    label: "{{ validate_list_idx }}"
  tags: ["no_print_skipped"]
