- name: "{{ project_ctx_title }}"
  set_fact:
    project_ctx_base_dir: >-
      {{ project_files_cloud_dir }}/ctxs/{{ project_ctx_key }}
    project_ctx_secrets_dir: >-
      {{ project_secrets_cloud_dir }}/ctxs/{{ project_ctx_key }}
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_path_map_repos"
  set_fact:
    project_ctx_path_map_repos: "{{ project_env_init.params.path_map_repos | default({}) }}"
  tags: ["no_print"]

# ctx - cloud repository

- name: "{{ project_ctx_title }} - validate - cloud repo - required"
  fail:
    msg: "cloud repo (under main) not specified for ctx [{{ project_ctx_key }}]"
  when: (project_env.main[project_ctx_key].repo | default('')) == ''
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_main"
  set_fact:
    project_ctx_main: "{{ project_env.main[project_ctx_key] }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_cloud_repo_key"
  set_fact:
    project_ctx_cloud_repo_key: "{{ project_ctx_main.repo }}"
    project_ctx_cloud_env_repos: "{{ project_ctx_main.env_repos | default([]) }}"
  tags: ["no_print"]

- name: "{{ project_env_title }} - set_fact - project_ctx_cloud_repo_dir"
  set_fact:
    project_ctx_cloud_repo_dir: "{{ project_ctx_base_dir + '/repo' }}"
    project_ctx_path_cloud: >-
      {{
        project_ctx_path_map_repos[project_ctx_cloud_repo_key]
        | default('')
      }}
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - cloud - repo (outer)"
  include_tasks: "external-tasks/repo.yml"
  vars:
    repo_title: "{{ project_ctx_title }} - cloud - repo"
    repo_main: "{{ project_env.repos[project_ctx_cloud_repo_key] | default({}) }}"
    repo_ssh_src_dir: "{{ project_env_dir }}"
    repo_secrets_dir: "{{ project_ctx_secrets_dir }}"
    repo_default_dir: "{{ project_ctx_cloud_repo_dir }}"
    repo_dev_base_dir: "{{ project_dev_repos_dir }}"
    repo_dev_path: "{{ project_ctx_path_cloud }}"
    repo_dev: "{{ env_dev }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - env repos (outer)"
  include_tasks: "external-tasks/repo.yml"
  vars:
    project_ctx_item_label: >-
      {{ project_ctx_item.dir | default('') }}
      ({{ project_ctx_item.repo | default('') }})
    project_ctx_path_cloud_env_repo: >-
      {{
        project_ctx_path_map_repos[project_ctx_item.repo | default('')]
        | default('')
      }}
    repo_title: >-
      {{ project_ctx_title }} -
      git cloud env repo [{{ project_ctx_item_label }}]
    repo_main: >-
      {{
        project_env.repos[project_ctx_item.repo | default('')]
        | default({})
      }}
    repo_ssh_src_dir: "{{ project_env_dir }}"
    repo_secrets_dir: "{{ project_ctx_secrets_dir + '/' + project_ctx_item.dir }}"
    repo_default_dir: "{{ project_ctx_cloud_repo_dir + '/' + project_ctx_item.dir }}"
    repo_dev_base_dir: "{{ project_dev_repos_dir }}"
    repo_dev_path: "{{ project_ctx_path_cloud_env_repo }}"
    repo_dev: "{{ env_dev }}"
  loop: "{{ project_ctx_cloud_env_repos }}"
  loop_control:
    loop_var: project_ctx_item
    label: "{{ project_ctx_item_label }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - create the ctx directory"
  file:
    path: "{{ project_ctx_base_dir }}"
    state: directory
    mode: "{{ env_dev | bool | ternary(0775, 0755) }}"

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params:
      project: "{{ project_env_init.key }}"
      ctx: "{{ project_ctx_key }}"
      env_dev: "{{ env_dev | bool | ternary('true', 'false') }}"
      ctx_dir: "{{ project_ctx_base_dir }}"
      env_dir: "{{ project_env_dir }}"
      env_file: "{{ project_env_dir }}/{{ project_env_file_rel }}"
      repo_dir: "{{ project_ctx_cloud_repo_dir }}"
      repo_run_file: >-
        {{ project_ctx_cloud_repo_dir }}/{{ project_ctx_main.run_file | default('run') }}
      vault_file: "{{ project_secrets_ctl_dir }}/vault"
      ssh_file: "{{ project_ssh_file }}"
      path_map_file: "{{ project_files_cloud_dir }}/{{ project_path_map_file_rel }}"
      dev_repos_dir: "{{ project_dev_repos_dir }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - create the project cloud ctx config file (vars.yml)"
  copy:
    content: "{{ project_ctx_params | to_nice_yaml }}"
    dest: "{{ project_ctx_base_dir }}/vars.yml"
    mode: "{{ env_dev | default(false, true) | bool | ternary(0666, 0600) }}"

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params_list: []
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params_list: >-
      {{
        project_ctx_params_list
        + [project_ctx_item.key + '=' + (project_ctx_item.value | quote)]
      }}
  loop: "{{ project_ctx_params | dict2items }}"
  loop_control:
    loop_var: project_ctx_item
    label: "{{ project_ctx_item.key }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - create the project cloud ctx config file (vars.sh)"
  copy:
    content: "{{ project_ctx_params_list | join('\n') }}"
    dest: "{{ project_ctx_base_dir }}/vars.sh"
    mode: "{{ env_dev | default(false, true) | bool | ternary(0666, 0600) }}"
