- name: "{{ project_ctx_title }}"
  set_fact:
    project_ctx_base_dir: >-
      {{ project_files_cloud_dir }}/ctxs/{{ project_ctx_key }}
    project_ctx_secrets_dir: >-
      {{ project_secrets_cloud_dir }}/ctxs/{{ project_ctx_key }}
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_var_dir"
  set_fact:
    project_ctx_var_dir: "{{ project_ctx_base_dir }}/var"
    project_ctx_path_map_repos: "{{ project_env_init.params.path_map_repos | default({}) }}"
  tags: ["no_print"]

# ctx - cloud repository

- name: "{{ project_ctx_title }} - validate - cloud repo - required"
  fail:
    msg: "cloud repo (under main) not specified for ctx [{{ project_ctx_key }}]"
  when: (project_env.main[project_ctx_key].repo | default('')) == ''
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_main"
  set_fact:
    project_ctx_main: "{{ project_env.main[project_ctx_key] }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_cloud_repo_key"
  set_fact:
    project_ctx_cloud_repo_key: "{{ project_ctx_main.repo }}"
    project_ctx_cloud_env_repos: "{{ project_ctx_main.env_repos | default([]) }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_path_cloud"
  set_fact:
    project_ctx_path_cloud: >-
      {{
        project_ctx_path_map_repos[project_ctx_cloud_repo_key]
        | default('')
      }}
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_cloud_repo_dir"
  set_fact:
    project_ctx_cloud_repo_dir: >-
      {{
        ((env_dev | bool) and (project_ctx_path_cloud != ''))
        | ternary(
          project_shared_repos_dir + '/clouds/' + project_ctx_path_cloud,
          project_ctx_base_dir + '/repo'
        )
      }}
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - git cloud (main)"
  include_tasks: "git.yml"
  vars:
    git_title: "{{ project_ctx_title }} - git cloud"
    git_repo: "{{ project_env.repos[project_ctx_cloud_repo_key] | default({}) }}"
    git_ssh_src_dir: "{{ project_env_dir }}"
    git_secrets_dir: "{{ project_ctx_secrets_dir }}"
    git_repo_dir: "{{ project_ctx_cloud_repo_dir }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - git cloud env repos (main)"
  include_tasks: "git.yml"
  vars:
    project_ctx_item_label: >-
      {{ project_ctx_item.dir | default('') }}
      ({{ project_ctx_item.repo | default('') }})
    git_title: "{{ project_ctx_title }} - git cloud env repo [{{ project_ctx_item_label }}]"
    git_repo: "{{ project_env.repos[project_ctx_item.repo | default('')] | default({}) }}"
    git_ssh_src_dir: "{{ project_env_dir }}"
    git_secrets_dir: "{{ project_ctx_secrets_dir + '/' + project_ctx_item.dir }}"
    git_repo_dir: "{{ project_ctx_cloud_repo_dir + '/' + project_ctx_item.dir }}"
  loop: "{{ project_ctx_cloud_env_repos }}"
  loop_control:
    loop_var: project_ctx_item
    label: "{{ project_ctx_item_label }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params:
      project: "{{ project_env_init.key }}"
      ctx: "{{ project_ctx_key }}"
      env_dev: "{{ env_dev | bool | ternary('true', 'false') }}"
      ctx_dir: "{{ project_ctx_base_dir }}"
      env_file: "{{ project_env_dir }}/{{ project_env_file_rel }}"
      repo_dir: "{{ project_ctx_cloud_repo_dir }}"
      repo_run_file: >-
        {{ project_ctx_cloud_repo_dir }}/{{ project_ctx_main.run_file | default('run') }}
      vault_file: "{{ project_secrets_ctl_dir }}/vault"
      ssh_file: "{{ project_ssh_file }}"
      path_map_file: "{{ project_files_cloud_dir }}/{{ project_path_map_file_rel }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - create the project cloud ctx config file (vars.yml)"
  copy:
    content: "{{ project_ctx_params | to_nice_yaml }}"
    dest: "{{ project_ctx_base_dir }}/vars.yml"
    mode: "{{ env_dev | default(false, true) | bool | ternary(0666, 0600) }}"

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params_list: []
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - project_ctx_params"
  set_fact:
    project_ctx_params_list: >-
      {{
        project_ctx_params_list
        + [project_ctx_item.key + '=' + (project_ctx_item.value | quote)]
      }}
  loop: "{{ project_ctx_params | dict2items }}"
  loop_control:
    loop_var: project_ctx_item
    label: "{{ project_ctx_item.key }}"
  tags: ["no_print"]

- name: "{{ project_ctx_title }} - create the project cloud ctx config file (vars.sh)"
  copy:
    content: "{{ project_ctx_params_list | join('\n') }}"
    dest: "{{ project_ctx_base_dir }}/vars.sh"
    mode: "{{ env_dev | default(false, true) | bool | ternary(0666, 0600) }}"
