# Main Vars and Validations

- name: "{{ cloud_node_item_title }} - ensure the inventory contains {{ '[' + cloud_node_name + ']' }}"
  lineinfile:
    name: "{{ inventory_file }}"
    line: "{{ '[' + cloud_node_name + ']' }}"
    state: present
  check_mode: yes
  register: cloud_node_conf
  failed_when: cloud_node_conf is failed
  tags: ["no_print_skipped"]

- name: >-
    {{ cloud_node_item_title }} -
    ensure the inventory contains {{ '[' + cloud_node_name + ']' }}
  fail:
    msg: "Ensure the inventory file contains a line with {{ '[' + cloud_node_name + ']' }}"
  when: cloud_node_conf is changed
  tags: ["no_print"]

- name: "{{ cloud_node_item_title }} - cloud_node_node"
  set_fact:
    cloud_node_node: "{{ env.nodes[cloud_node_key] }}"
  tags: ["no_print"]

- name: "{{ cloud_node_item_title }} - cloud_node_credential"
  set_fact:
    cloud_node_credential: >-
      {{
        env.credentials[cloud_node_node.credential | default('')] | default({})
      }}
  tags: ["no_print"]

### Cloud Node Params ###

- name: "{{ cloud_node_item_title }} - node params (outer)"
  include_tasks: "tasks/nodes/node_params.yml"
  vars:
    node_params_title: "{{ cloud_node_item_title }} - node params"
    node_params_node: "{{ cloud_node_node }}"
    node_params_info: "{{ cloud_node_info }}"
  tags: ["no_print"]

- name: "{{ cloud_node_item_title }} - cloud_node_params"
  set_fact:
    cloud_node_params: "{{ node_params }}"
  tags: ["no_print"]

### User Data ###

- name: "{{ cloud_node_item_title }} - cloud_node_user_data - initial"
  set_fact:
    cloud_node_user_data: ""
  tags: ["no_print"]

- name: "{{ cloud_node_item_title }} - cloud_node_user_data - fill (outer)"
  include_tasks: "cloud_node_user_data.yml"
  when: (cloud_node_params.user_data_file | default('')) != ''

### SSH Vars ###

- name: "{{ cloud_node_item_title }} - cloud_node_ssh_key_filename"
  set_fact:
    cloud_node_ssh_key_filename: "{{ cloud_node_name + '.key' }}"
  tags: ["no_print"]

- name: "{{ cloud_node_item_title }} - cloud_node_ssh_key_path"
  set_fact:
    cloud_node_ssh_file: >-
      {{
        cloud_node_credential.ssh_file | default('')
        | ternary(
          env_dir + '/' +
            (cloud_node_credential.ssh_file | default('')),
            ''
          )
      }}
    cloud_node_ssh_key_path: >-
      {{
        ((cloud_node_credential.ssh_file | default('')) != '')
        | ternary(cloud_node_tmp_dir + '/' + cloud_node_ssh_key_filename, '')
      }}
  tags: ["no_print"]

### SSH File ###

- name: >-
    {{ cloud_node_item_title }} - create the ssh key file dir -
    {{ cloud_node_ssh_key_path | dirname }}
  file:
    path: "{{ cloud_node_ssh_key_path | dirname }}"
    state: directory
    mode: 0755
  when: cloud_node_ssh_key_path != ''
  tags: ["no_print_skipped"]

- name: "{{ cloud_node_item_title }} - generate the ssh key file - {{ cloud_node_ssh_key_path }}"
  copy:
    src: "{{ cloud_node_ssh_file }}"
    dest: "{{ cloud_node_ssh_key_path }}"
    decrypt: "{{ cloud_node_credential.ssh_file_encrypted | default(false) | bool }}"
    mode: 0600
  when: cloud_node_ssh_key_path != ''
  tags: ["no_print_skipped"]

# Main Service

- name: "{{ cloud_node_item_title }} - run (outer)"
  include_tasks: "cloud_node_run.yml"
  when: (not (cloud_node_info.external | default(false) | bool))
  tags: ["no_print_skipped"]
