- name: "{{ cloud_node_title }} - nodes (outer)"
  include_tasks: "cloud_node_item.yml"
  vars:
    cloud_node_info: "{{ cloud_node_item }}"
    cloud_node_name: "{{ cloud_node_info.name | default(cloud_node_info) }}"
    cloud_node_key: >-
      {{
        cloud_node_info.key |
        default(cloud_node_info.name) |
        default(cloud_node_info)
      }}
    cloud_node_item_title: >-
      {{ cloud_node_title }} - {{ cloud_node_name }}
      {{ (cloud_node_name != cloud_node_key) | ternary('(' + cloud_node_key + ')', '') }}
    cloud_node_tmp_dir: >-
      {{ env_ctx_dir }}/cloud/node/{{ cloud_node_name }}
  loop: "{{ cloud_node_list }}"
  loop_control:
    loop_var: cloud_node_item
    label: "{{ cloud_node_name }}"
  when: >-
    (((env_node | default('')) == '') or (env_node == cloud_node_name))
    and
    (not (cloud_node_info.external | default(false) | bool))
  tags: ["no_print_skipped"]
