- name: "{{ cloud_node_title }} - nodes (outer)"
  include_tasks: "cloud_node_item.yml"
  vars:
    cloud_node_name: "{{ cloud_node_item.name }}"
    cloud_node_item_title: >-
      {{ cloud_node_title }} - node [{{ cloud_node_item.description }}]
  loop: "{{ cloud_node_list }}"
  loop_control:
    loop_var: cloud_node_item
    label: "{{ cloud_node_name }}"
  when: env_node in ['', cloud_node_name]
  tags: ["no_print_skipped"]
