- name: "{{ cron_title }} - cron node (outer)"
  include_tasks: "cron_node.yml"
  vars:
    cron_node_info: "{{ main_item }}"
    cron_node_name: "{{ cron_node_info.name | default(cron_node_info) }}"
    cron_node_key: >-
      {{
        cron_node_info.key
        | default(cron_node_info.name, true)
        | default(cron_node_info, true)
      }}
    cron_node: "{{ env.nodes[cron_node_key] }}"
    cron_node_title: "{{ cron_title }} - cron node [{{ cron_node_name }}]"
    cron_node_tmp_dir: "{{ cron_tmp_dir }}/{{ cron_node_name }}/cron"
  loop: "{{ cron_node_list }}"
  loop_control:
    loop_var: main_item
    label: "{{ cron_node_name }}"
  when: >-
    ((ansible_connection == 'local') or (cron_node_name == instance_type))
    and
    (((env_node | default('')) == '') or (env_node == cron_node_name))
  tags: ["no_print_skipped"]
