- name: "{{ node_params_title }} - generate node params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ node_params_title }} - generate node params"
    params_mixer_main_params: "{{ node_params_node.params | default({}) }}"
    params_mixer_group_params_names: "{{ node_params_node.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ node_params_node.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ node_params_node.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ env.shared_group_params | default({}) }}"
    params_mixer_shared_params_names_dict: "{{ env.node_shared_params | default({}) }}"
    params_mixer_group_params_dict: "{{ env.node_group_params | default({}) }}"
  tags: ["no_print"]

- name: "{{ node_params_title }} - node_params (tmp)"
  set_fact:
    node_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ node_params_title }} - generate node ctx params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ node_params_title }} - generate node ctx params"
    params_mixer_main_params: "{{ node_params_info.params | default({}) }}"
    params_mixer_group_params_names: "{{ node_params_info.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ node_params_info.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ node_params_info.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ env.shared_group_params | default({}) }}"
    params_mixer_shared_params_names_dict: "{{ env.node_shared_params | default({}) }}"
    params_mixer_group_params_dict: "{{ env.node_group_params | default({}) }}"
  tags: ["no_print"]

- name: "{{ node_params_title }} - node_params_info_params"
  set_fact:
    node_params_info_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ node_params_title }} - node_params"
  set_fact:
    node_params: >-
      {{ node_params | combine(node_params_info_params) }}
  tags: ["no_print"]
