- name: "{{ node_prepare_title }} - create the node directories"
  become: "{{ node_prepare_node.root | default(false) }}"
  file:
    path: "{{ node_prepare_item }}"
    state: directory
    mode: "{{ env_lax | bool | ternary(0777, 0755) }}"
  loop:
    - "{{ node_prepare_node.node_dir }}"
    - "{{ node_prepare_node.tmp_dir }}"
  loop_control:
    loop_var: node_prepare_item

- name: "{{ node_prepare_title }} - transfer (outer)"
  include_tasks: "tasks/util/transfer.yml"
  vars:
    node_prepare_dependencies: >-
      {{ ctx_node_dependencies[node_prepare_node.name] | default({}) }}
    transfer_title: "{{ node_prepare_title }} - transfer #{{ node_prepare_idx + 1 }}"
    transfer_prepared: true
    transfer_content: "{{ node_prepare_item.src }}"
    transfer_input:
      dependencies: "{{ node_prepare_dependencies }}"
    transfer_dest: "{{ node_prepare_node.node_dir }}/{{ node_prepare_item.dest }}"
    transfer_tmp_dest: "{{ node_prepare_node.tmp_dir }}/{{ node_prepare_item.dest }}"
    transfer_become: "{{ node_prepare_node.root | default(false) }}"
    transfer_mode: "{{ node_prepare_item.mode }}"
    transfer_dir_mode: "{{ node_prepare_item.dir_mode }}"
  when: node_prepare_item.when | default(true, true) | bool
  loop: "{{ node_prepare_node.prepared_transfer | default([]) }}"
  loop_control:
    index_var: node_prepare_idx
    loop_var: node_prepare_item
    label: "{{ node_prepare_idx }}"
  tags: ["no_print_skipped"]
