# Load Schema

- name: "{{ validate_title }} - load the schema"
  include_vars:
    file: "{{ validate_schema_file }}"
    name: validate_schema_wrapper

- name: "{{ validate_title }} - load the schema for schema"
  include_vars:
    file: "schemas/schema.yml"
    name: validate_schema_validator_wrapper

# Validate Schema

- name: "{{ validate_title }} - validate_schema_dict (schema validator)"
  set_fact:
    validate_schema_dict: "{{ validate_schema_validator_wrapper.schemas }}"
    validate_schema_list: "{{ [validate_schema_info] }}"
    validate_schema_idx: 0
    validate_schema_error_msgs: []
  vars:
    validate_schema_info:
      schema: "{{ validate_schema_validator_wrapper.root }}"
      value: "{{ validate_schema_wrapper }}"
      ctx: ""
  tags: ["no_print"]

- name: "{{ validate_title }} - validate schema (recursive)"
  include_tasks: "tasks/validate/recursive.yml"
  vars:
    validate_recursive_title: "{{ validate_title }} - validate schema"
  tags: ["no_print"]

- name: "{{ validate_title }} - fail (schema)"
  fail:
    msg: "{{ validate_schema_error_msgs | to_nice_yaml }}"
  when: (validate_schema_error_msgs | length) > 0
  tags: ["no_print"]

# Validate Value

- name: "{{ validate_title }} - validate_schema_dict"
  set_fact:
    validate_schema_dict: "{{ validate_schema_wrapper.schemas }}"
    validate_schema_list: "{{ [validate_schema_info] }}"
    validate_schema_idx: 0
    validate_schema_error_msgs: []
  vars:
    validate_schema_info:
      schema: "{{ validate_schema_wrapper.root }}"
      value: "{{ validate_value }}"
      ctx: ""
  tags: ["no_print"]

- name: "{{ validate_title }} - validate value (recursive)"
  include_tasks: "tasks/validate/recursive.yml"
  vars:
    validate_recursive_title: "{{ validate_title }} - validate value"
  tags: ["no_print"]

- name: "{{ validate_title }} - fail"
  fail:
    msg: "{{ validate_schema_error_msgs | to_nice_yaml }}"
  when: (validate_schema_error_msgs | length) > 0
  tags: ["no_print"]
