<% set var_run_stages = ctx_data.run_stages | default([], true) %>

# 'task': var_task,
# 'output_path': var_pod_data_dir + '/log/run',
# 'output_file': 'run.stage.' + var_run_stage_name + '.' +
# var_run_stage_task_name + '.' + var_task_tag + '.' +
# ('%Y-%m-%d_%H-%M-%S' | strftime()) + '.log',
# 'tmp_path': var_pod_data_dir + '/tmp/run',
# 'tmp_file': 'run.stage.' + var_run_stage_name + '.' +
# var_run_stage_task_name + '.' + var_task_tag + '.sh',
# 'chdir': var_pod_repo_location,
# 'node_item': var_node_item,
# 'pod_name': var_pod_name

# error['error.run_stage[' + var_run_stage_name +
# '].run_stage_task[' + var_run_stage_task_name +
# '].node[' + var_node_name +
# '].pod[' + var_pod_name +
# '].task_tag[' + var_task_tag +
# '].tasks_group[' + var_tasks_group_name +
# '].task[' + var_task_name +
# '].type.invalid.' + var_task_type]

<% set ns_outer_run = namespace(first=true) %>

<% for var_run_stage in var_run_stages %>

<% if (var_run_stage.tasks | default([], true) | length) > 0 %>

<% if not (ns_outer_run.first | bool) %>
###############################################################################
<% endif %>

<% set ns_outer_run.first = false %>

- name: Play 04.<< loop.index >> - Run (<< var_run_stage.name >>)
  hosts: << var_run_stage.hosts | join(',') >>
  strategy: free
  tags:
  - init
  - run
  gather_facts: no
  tasks:
  - include_tasks: "tasks/util/init.yml"
    when: ansible_connection != 'local'
    tags: ["no_print"]

  - name: "{{ env_title }}"
    include_role:
      name: "cloud_run"
    vars:
      main_tmp_stage_task: "{{ main_item.0 }}"
      main_tmp_task: "{{ main_tmp_stage_task.task }}"
      main_tmp_node: "{{ main_item.1 }}"
      main_tmp_label: >-
        [stage] << var_run_stage.name >> -
        [stage_task] {{ main_tmp_stage_task.name }} -
        [task] {{ main_tmp_task.name }} ({{ main_tmp_task.type }}) -
        [node] {{ main_tmp_node.description }}
      cloud_run_stage_name: "<< var_run_stage.name >>"
      cloud_run_title: "{{ main_tmp_label }}"
      cloud_run_task: "{{ main_tmp_task }}"
      cloud_run_task: "{{ main_tmp_task }}"
      cloud_run_node: "{{ main_tmp_node }}"
    loop: >-
      {{
        ctx_data.run_stages[<< loop.index - 1 >>]
        | map(attribute='tasks')
        | default[]
        | subelements('nodes')
      }}
    loop_control:
      loop_var: main_item
      label: "{{ main_tmp_label }}"
    when: >-
      (main_tmp_node | validate_connection(env_info))
      and
      ((main_tmp_task.type | default('')) != 'skip')
    tags: ["no_print_skipped"]

###############################################################################

- name: Play 04.<< loop.index >> - Wait (<< var_run_stage.name >>)
  hosts: main,host
  strategy: linear
  any_errors_fatal: true
  tags:
  - init
  - run
  gather_facts: no
  tasks:

    - name: "{{ env_title }} - wait hosts"
      debug:
        msg: "wait hosts..."

<% endif %>
<% endfor %>

<% if ns_outer_run.first | bool %>

- name: Play 04 - Run Stages (Empty)
  hosts: main
  strategy: linear
  any_errors_fatal: true
  tags:
  - init
  - run
  gather_facts: no
  tasks:

    - name: "{{ env_title }} - nothing to run"
      debug:
        msg: "nothing to run..."

<% endif %>