<<% set var_run_stages = ctx_data.run_stages | default([], true) %>>
<<% set ns_outer_run = namespace(first=true) %>>

<<% for var_run_stage in var_run_stages %>>

<<% if (var_run_stage.tasks | default([], true) | length) > 0 %>>

<<% if not (ns_outer_run.first | bool) %>>
###############################################################################
<<% endif %>>

- name: Play 04.<<{ loop.index }>> - Run Stage (<<{ var_run_stage.name }>>)
  hosts: <<{ var_run_stage.hosts | join(',') }>>
  strategy: free
  tags:
  - init
  - run
  gather_facts: no
  tasks:

    <<% if ns_outer_run.first | bool %>>

    - include_tasks: "tasks/util/init.yml"
      when: ansible_connection != 'local'
      tags: ["no_print"]

    <<% endif %>>

    - block:
        - name: "{{ env_title }} - run stage [<<{ var_run_stage.name }>>]"
          include_tasks: "tasks/nodes/cloud_run.yml"
          vars:
            main_tmp_stage_name: "<<{ var_run_stage.name }>>"
            main_tmp_stage_task: "{{ main_item.0 }}"
            main_tmp_task: "{{ main_tmp_stage_task.task }}"
            main_tmp_node: "{{ main_item.1 }}"
            main_tmp_label: >-
              [run_stage] {{ main_tmp_stage_name }} -
              [stage_task] {{ main_tmp_stage_task.name }} -
              [task] {{ main_tmp_task.description }} -
              [node] {{ main_tmp_node.description }}
            cloud_run_stage_name: "{{ main_tmp_stage_name }}"
            cloud_run_title: "{{ env_title }} - {{ main_tmp_label }}"
            cloud_run_task: "{{ main_tmp_task }}"
            cloud_run_node: "{{ main_tmp_node }}"
            cloud_run_task_target: "{{ main_tmp_stage_task.task_target }}"
          loop: >-
            {{ ctx_data.run_stages[<<{ loop.index - 1 }>>].tasks | default([]) | subelements('nodes') }}
          loop_control:
            loop_var: main_item
            label: "{{ main_tmp_label }}"
          when: >-
            (main_tmp_node | lrd.cloud.validate_connection(env_info))
            and
            ((main_tmp_task.type | default('')) != 'skip')
          tags: ["no_print_skipped"]
      when: not (instance_info_skip | bool)

###############################################################################

- name: Play 04.<<{ loop.index }>> - Wait Stage (<<{ var_run_stage.name }>>)
  hosts: main,host
  strategy: linear
  any_errors_fatal: true
  tags:
  - init
  - run
  gather_facts: no
  tasks:

    - name: "{{ env_title }} - wait hosts"
      debug:
        msg: "wait hosts..."


<<% set ns_outer_run.first = false %>>

<<% endif %>>
<<% endfor %>>

<<% if ns_outer_run.first | bool %>>

- name: Play 04 - Run Stages (Empty)
  hosts: main
  strategy: linear
  any_errors_fatal: true
  tags:
  - init
  - run
  gather_facts: no
  tasks:

    - name: "{{ env_title }} - run stages - nothing to run"
      debug:
        msg: "nothing to run..."

<<% endif %>>