- name: "make broken sync module work"
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sync_dir_host_user }}\s'
    line: '%{{ sync_dir_host_user }} ALL=(ALL) NOPASSWD: ALL'

- name: "synchronize"
  become: true
  synchronize:
    src: "{{ sync_dir_src }}"
    dest: "{{ sync_dir_dest }}"
    recursive: yes    
    delete: yes
    checksum: yes
    times: no
    rsync_opts:
    - "--chmod=F600"

- name: "cleanup after sync module"
  become: true
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sync_dir_host_user }}\s'
    line: '%{{ sync_dir_host_user }} ALL=(ALL) ALL'
