- name: move the docker compose executable file
  become: true
  template:
    src: "{{ docker_compose_bin_src }}"
    dest: "{{ docker_compose_bin_dest }}"
    mode: 0700

- name: update the repository with the docker_compose file
  become: true
  git:
    repo: "{{ docker_compose_repo }}"
    version: "{{ docker_compose_repo_version }}"
    refspec: "{{ docker_compose_repo_refspec }}"
    dest: "{{ docker_compose_repo_dest }}"
    force: "yes"

- name: Ensure directories are 0755
  command: find {{ docker_compose_repo_dest }} -type d -exec chmod -c 0755 {} \;
  register: docker_compose_chmod_result
  changed_when: 'docker_compose_chmod_result.stdout != ""'

- name: Ensure files are 0644
  command: find {{ docker_compose_repo_dest }} -type f -exec chmod -c 0644 {} \;
  register: docker_compose_chmod_result
  changed_when: 'docker_compose_chmod_result.stdout != ""'