### Ensure docker is running and update the docker-compose executable ###

- name: "{{ cloud_prepare_title }} - ensure docker is running"
  become: "{{ cloud_prepare_cloud.root }}"
  service: 
    name: docker
    state: started

- name: "{{ cloud_prepare_title }} - copy the docker compose executable file"
  become: "{{ cloud_prepare_cloud.root }}"
  template: 
    src: "roles/cloud_prepare/files/docker-compose.sh"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
  vars:
    params: 
      docker_compose_version: "{{ cloud_prepare_pod_orchestration.version }}"
  when: 
    ((cloud_prepare_pod_orchestration.version | default('')) != '')
    and
    (cloud_prepare_pod_orchestration.container | bool)
