- name: "{{ cloud_prepare_title }}"
  set_fact:
    cloud_prepare_dependencies: []
    cloud_prepare_dependencies_ip_dict: {}
    cloud_prepare_dependencies_ips_dict: {}
  tags: ["no_print"]

- name: "{{ cloud_prepare_title }}"
  include_tasks: "dependency.yml"
  vars:
    cloud_prepare_dependency_title: "{{ cloud_prepare_title }} - dependency[{{ cloud_prepare_item.host }}]"
    cloud_prepare_dependency_host: "{{ cloud_prepare_item.host }}"
    cloud_prepare_dependency_node: "{{ cloud_prepare_item.node }}"
    cloud_prepare_dependency_all: "{{ cloud_prepare_item.all | default(false) | bool }}"
    cloud_prepare_dependency_field: >-
      {{
      cloud_prepare_item.public | default(false) | bool |
      ternary('instance_public_ipv4', 'instance_private_ip')
      }}
    cloud_prepare_dependency_total_src_nodes: "{{ groups[cloud_prepare_node_name] | length }}"
    cloud_prepare_dependency_ips: >-
      {{
      groups[cloud_prepare_dependency_node] |
      map('extract', hostvars, [cloud_prepare_dependency_field]) | list
      }}
  loop: "{{ cloud_prepare_node_info.dependencies | default([]) | list }}"
  loop_control:
    loop_var: cloud_prepare_item
  when: cloud_prepare_cloud.type != 'local'
  tags: ["no_print"]

- name: "{{ cloud_prepare_title }} - define the dependencies ips"
  become: true
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ cloud_prepare_item.host }}$"
    line: "{{ cloud_prepare_item.ip }} {{ cloud_prepare_item.host }}"
    state: present
  loop: "{{ cloud_prepare_dependencies }}"
  loop_control:
    label: "{{ cloud_prepare_item.host }}"
    loop_var: cloud_prepare_item
  tags: ["no_print_skipped"]

- name: "{{ cloud_prepare_title }}"
  include_tasks: "pod.yml"
  vars:
    cloud_prepare_pod_info: "{{ cloud_prepare_item }}"
    cloud_prepare_pod_name: "{{ cloud_prepare_item.name | default(cloud_prepare_item) }}"
    cloud_prepare_pod_key: "{{ cloud_prepare_item.key | default(cloud_prepare_item.name) | default(cloud_prepare_item) }}"
    cloud_prepare_pod_main: >-
      {{ ((cloud_prepare_item.main | default(false) | bool) or ((cloud_prepare_node.pods | default([]) | length) == 1)) }}
    cloud_prepare_pod: "{{ cloud_prepare_pods_dict[cloud_prepare_pod_key] }}"
    cloud_prepare_node_info_pod_params: "{{ cloud_prepare_node_info.pods[cloud_prepare_pod_name] | default({}) }}"
    cloud_prepare_pod_title: "{{ cloud_prepare_title }} - pod[{{ cloud_prepare_pod_name }}]"
    cloud_prepare_pod_dirname: "{{ cloud_prepare_pod.base_dir | default(cloud_prepare_pod_name, true) }}"
    cloud_prepare_pod_base_dir: "{{ cloud_prepare_base_dir }}/{{ cloud_prepare_pod_dirname }}"
    cloud_prepare_pod_identifier: >-
      {{ cloud_prepare_env_name }}/{{ cloud_prepare_ctx_name }}/{{ cloud_prepare_pod_name }}
    cloud_prepare_host_user: "{{ cloud_prepare_node_credentials.host_user }}"
    cloud_prepare_host_group: "{{ cloud_prepare_node_credentials.host_user }}"
    cloud_prepare_local_pod_default_repo_dir: >-
      {{ cloud_prepare_local_pods_base_dir + '/' + cloud_prepare_pod_name }}
    cloud_prepare_pod_local_tmp_dir: >-
      {{ cloud_prepare_local_tmp_dir }}/pod/{{ cloud_prepare_pod_name }}
    cloud_prepare_pod_local_data_dir_inside: >-
      {{
      (cloud_prepare_local_data_dir_inside | default('') != '')
      | ternary(cloud_prepare_local_data_dir_inside + '/' + cloud_prepare_pod_identifier, '')
      }}
  loop: "{{ cloud_prepare_node.pods | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_item
  when: cloud_prepare_env_pod in ['', cloud_prepare_pod_name]
  tags: ["no_print"]
