- name: "{{ cloud_prepare_title }}"
  include_tasks: "pod.yml"
  vars:
    cloud_prepare_pod_title: "{{ cloud_prepare_title }} - {{ cloud_prepare_item }}"
    cloud_prepare_pod_id: "{{ cloud_prepare_item }}"
    cloud_prepare_pod: "{{ cloud_prepare_pods_dict[cloud_prepare_item] }}"
    cloud_prepare_pod_orchestration: >-
      {{ cloud_prepare_orchestrations_dict[cloud_prepare_pod.orchestration] }}
    cloud_prepare_pod_base_dir: "{{ cloud_prepare_base_dir }}/{{ cloud_prepare_item }}"
    cloud_prepare_params: "{{ cloud_prepare_params_dict[cloud_prepare_pod.params] }}"
    cloud_prepare_host_user: "{{ cloud_prepare_node_credentials.host_user }}"
    cloud_prepare_host_group: "{{ cloud_prepare_node_credentials.host_user }}"
    cloud_prepare_local_pod_repo: >-
      {{ 
      (cloud_prepare_cloud.type == 'local') | ternary(
      cloud_prepare_local_pod_dict[cloud_prepare_item].dir
      | default(cloud_prepare_local_pod_repo_base + '/' + cloud_prepare_item),
      cloud_prepare_local_pod_repo_base + '/' + cloud_prepare_item
      )
      }}
    cloud_prepare_pod_local_tmp_dir: >-
      {{ cloud_prepare_local_tmp_dir }}/pod/{{ cloud_prepare_item }}
    cloud_prepare_pod_data_dir_inside: >-
      {{ cloud_prepare_data_dir_inside + '/' + cloud_prepare_item }}
    cloud_prepare_pod_local_data_dir_rel: >-
      {{ cloud_prepare_local_data_dir_rel + '/' + cloud_prepare_item }}
  loop: "{{ cloud_prepare_node.pods | default([cloud_prepare_node.main_pod]) | list }}"
  loop_control:
    loop_var: cloud_prepare_item
  when: cloud_prepare_env_pod in ['', cloud_prepare_item]
