### Create / Update the repository ###

- name: "{{ cloud_prepare_inner_title }} - set_fact - vars"
  set_fact:
    cloud_prepare_local_pod_repo: "/main/pod/{{ local_pod_dir_rel }}"
    cloud_prepare_repo_location: "/main/pod/{{ local_pod_dir_rel }}"
  when: "{{ cloud_prepare_cloud.type == 'local' }}"

- name: "{{ cloud_prepare_inner_title }} - create the repo directory"
  become: "{{ cloud_prepare_pod.root }}"
  file:
    path: "{{ cloud_prepare_repo_location }}"
    state: directory
    mode: 0755

- name: "{{ cloud_prepare_inner_title }} - update the repo directory"
  become: "{{ cloud_prepare_pod.root }}"
  git:
    repo: "{{ cloud_prepare_pod.repo }}"
    version: "{{ cloud_prepare_pod.repo_version }}"
    dest: "{{ cloud_prepare_repo_location }}"
    update: "{{ cloud_prepare_cloud.type != 'local' }}"
    force: "{{ cloud_prepare_cloud.type != 'local' }}"
  register: cloud_prepare_git_result
  tags: ["print_action"]

- name: "{{ cloud_prepare_inner_title }} - set_fact - vars"
  set_fact:
    cloud_prepare_git_commit: "{{ cloud_prepare_git_result.after }}"
    cloud_prepare_pod_env_dir: "{{ cloud_prepare_pod.env_dir | default('env') }}"

## Creates the environment pod repository in the env folder (when defined)

- block:

  - name: "{{ cloud_prepare_inner_title }} - set_fact - vars"
    set_fact:
      cloud_prepare_env_repo: "{{ cloud_prepare_pod.env_repo }}"
      cloud_prepare_repo_key_file: >-
        {{ cloud_prepare_repo_location }}/tmp/{{ cloud_prepare_pod_env_dir }}/env_key

  - name: >-
      {{ cloud_prepare_inner_title }} - create the directory for the temporary files
    become: "{{ cloud_prepare_pod.root }}"
    file:
      path: "{{ cloud_prepare_repo_location }}/tmp/{{ cloud_prepare_pod_env_dir }}"
      state: directory
      mode: 0755

  - name: "{{ cloud_prepare_inner_title }} - copy encrypted file to set location"
    become: "{{ cloud_prepare_pod.root }}"
    copy:
      src: >-
        {{ cloud_prepare_env_dir }}/{{ cloud_prepare_env_repo.key_file_encrypted }}
      dest: "{{ cloud_prepare_repo_key_file }}"
      decrypt: yes
      mode: 0600

  - name: >-
      {{ cloud_prepare_inner_title }} -
      environment pod repository
      ({{ cloud_prepare_repo_location }}/{{ cloud_prepare_pod.env_repo.dir }})
    become: "{{ cloud_prepare_pod.root }}"
    git:
      repo: "{{ cloud_prepare_env_repo.src }}"
      version: "{{ cloud_prepare_env_repo.version }}"
      dest: "{{ cloud_prepare_repo_location }}/{{ cloud_prepare_pod.env_repo.dir }}"
      key_file: "{{ cloud_prepare_repo_key_file }}"
      accept_hostkey: yes
      update: "{{ cloud_prepare_cloud.type != 'local' }}"
      force: "{{ cloud_prepare_cloud.type != 'local' }}"
    tags: ["print_action"]

  when: cloud_prepare_pod.env_repo is defined

### Generate the environment pod context variables ###

- name: "{{ cloud_prepare_inner_title }} - populate vars from templates (debug)"
  debug: 
    msg: "populate vars from templates"
  tags: ["print_action"]

- name: "{{ cloud_prepare_inner_title }} - set_fact"
  set_fact:
    cloud_prepare_ctx_tpl_dest: >-
      {{ cloud_prepare_pod_local_tmp_dir }}/cloud_prepare_ctx.yml

- name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_params_aux"
  set_fact:
    cloud_prepare_params_aux:
      pod_id: "{{ cloud_prepare_pod_id }}"
      pod: "{{ cloud_prepare_pod }}"
      git_commit: "{{ cloud_prepare_git_result.after }}"
      repo_name: "{{ cloud_prepare_env_name }}"
      pod_env_dir: "{{ cloud_prepare_pod_env_dir | default('env') }}"
      repo_location: "{{ cloud_prepare_repo_location }}"
      data_dir: "{{ cloud_prepare_data_dir }}"
      env_cmd: "{{ cloud_prepare_env_cmd }}"

- name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_credentials"
  set_fact:
    cloud_prepare_inner_credentials: {}
  
- name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_credentials"
  set_fact:
    cloud_prepare_inner_credentials: >-
      {{ 
      cloud_prepare_inner_credentials | 
      combine({ 
      cloud_prepare_inner_item.key: 
      cloud_prepare_credentials_dict[cloud_prepare_inner_item.value] }) 
      }}
  loop: "{{ cloud_prepare_pod.credentials | default({}) | dict2items }}"
  loop_control:
    loop_var: cloud_prepare_inner_item
    label: "{{ cloud_prepare_inner_item.key }} ({{ cloud_prepare_inner_item.value }})"

- debug:
    var: cloud_prepare_inner_credentials

- name: >-
    {{ cloud_prepare_inner_title }} - 
    create the local directory for the expanded context template
  file:
    path: "{{ cloud_prepare_ctx_tpl_dest | dirname }}"
    state: directory
    mode: 0755
  delegate_to: localhost
  
- name: "{{ cloud_prepare_inner_title }} - get the context data from the template"
  template: 
    src: "{{ cloud_prepare_local_pod_repo }}/{{ cloud_prepare_pod.ctx }}"
    dest: "{{ cloud_prepare_ctx_tpl_dest }}"
    mode: 0640
  vars:
    params: "{{ cloud_prepare_params }}"
    params_aux: "{{ cloud_prepare_params_aux }}"
    credentials: "{{ cloud_prepare_inner_credentials }}"
  delegate_to: localhost

- name: >-
    {{ cloud_prepare_inner_title }} - 
    load ctx environment vars ({{ cloud_prepare_pod_id }})
  include_vars:
    file: "{{ cloud_prepare_ctx_tpl_dest }}"
    name: cloud_prepare_ctx_outer_params
  delegate_to: localhost

### Generate a file with all the context environment expanded variables (for idempotence) ###

- name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_vars_full"
  set_fact:
    cloud_prepare_vars_full:
      main: "{{ cloud_prepare_ctx_outer_params }}"
      aux: "{{ cloud_prepare_params_aux }}"
      credentials: "{{ cloud_prepare_inner_credentials }}"

- name: "{{ cloud_prepare_inner_title }} - create the temporary file to verify if there was a change"
  become: "{{ cloud_prepare_pod.root }}"
  copy: 
    content: "{{ cloud_prepare_vars_full | to_nice_yaml }}"
    dest: "{{ cloud_prepare_backup_file_tmp }}"
    owner: "{{ cloud_prepare_owner }}"
    group: "{{ cloud_prepare_group }}"
    mode: 0640

- name: "{{ cloud_prepare_inner_title }} - get the difference of the 2 files (old and current)"
  become: "{{ cloud_prepare_pod.root }}"
  command: "diff {{ cloud_prepare_backup_file_tmp }} {{ cloud_prepare_backup_file }}"
  register: cloud_prepare_diff
  failed_when: cloud_prepare_diff.rc > 1
  changed_when: cloud_prepare_diff.rc == 1

### Continue the preparation only when changed from the previous ###

- block:

  ### Generate the environment pod expanded variables ###

  - name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_ctx_params"
    set_fact:
      cloud_prepare_ctx_params: "{{ cloud_prepare_ctx_outer_params.params }}"

  - name: "{{ cloud_prepare_inner_title }} - set_fact - vars"
    set_fact:
      cloud_prepare_vars_volumes: []
      cloud_prepare_vars_files: []
      cloud_prepare_vars_templates: []
      cloud_prepare_vars_env_files: []

  - name: "{{ cloud_prepare_inner_title }} - populate vars from templates (outer)"
    include_tasks: "vars.yml"
    loop: "{{ cloud_prepare_ctx_params }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.name }}"

  ### Polish previous variables to use them directly later ###

  - name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_tpl_list - empty"
    set_fact:
      cloud_prepare_files_list: []
      cloud_prepare_tpl_list: []
      cloud_prepare_env_files_list: []
      cloud_prepare_dir_list: []

  - name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_files_list - fill"
    set_fact:
      cloud_prepare_files_list: >-
        {{ 
        cloud_prepare_files_list
        + [{ 
        'src': cloud_prepare_inner_item_src_full, 
        'dest': cloud_prepare_inner_item_dest_full, 
        'mode': cloud_prepare_inner_item.mode | default('', true)
        }] 
        }}
    vars: 
      cloud_prepare_inner_item_src_full: >-
        {{ cloud_prepare_repo_location }}/{{ 
          cloud_prepare_inner_item.dir_base | default('files') 
        }}/{{ cloud_prepare_inner_item.src }}
      cloud_prepare_inner_item_dest_full: >-
        {{ cloud_prepare_repo_location }}/{{ 
        ((cloud_prepare_inner_item.root | default(false) | bool) | 
        ternary('', cloud_prepare_pod_env_dir + '/')) 
        + (cloud_prepare_inner_item.dest | default(cloud_prepare_inner_item.src)) 
        }}
    loop: "{{ cloud_prepare_vars_files | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest | default(cloud_prepare_inner_item.src) }}"

  - name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_tpl_list - fill"
    set_fact:
      cloud_prepare_tpl_list: >-
        {{ 
        cloud_prepare_tpl_list
        + [{ 
        'src': cloud_prepare_inner_item_src_local_full,
        'dest': cloud_prepare_inner_item_dest_full, 
        'mode': cloud_prepare_inner_item.mode | default('', true), 
        'params': cloud_prepare_inner_item_params
        }] 
        }}
    vars: 
      cloud_prepare_inner_item_src_local_full: >-
        {{ cloud_prepare_local_pod_repo }}/{{ 
          cloud_prepare_inner_item.dir_base | default('templates') 
        }}/{{ cloud_prepare_inner_item.src }}
      cloud_prepare_inner_item_dest_full: >-
        {{ cloud_prepare_repo_location }}/{{ 
        ((cloud_prepare_inner_item.root | default(false) | bool) | 
        ternary('', cloud_prepare_pod_env_dir + '/')) 
        + (cloud_prepare_inner_item.dest | default(cloud_prepare_inner_item.src)) 
        }}
      cloud_prepare_inner_item_params: "{{ cloud_prepare_inner_item.params | default({}) }}"
    loop: "{{ cloud_prepare_vars_templates | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest | default(cloud_prepare_inner_item.src) }}"

  - name: "{{ cloud_prepare_inner_title }} - set_fact - cloud_prepare_env_files_list - fill"
    set_fact:
      cloud_prepare_env_files_list: >-
        {{ 
        cloud_prepare_env_files_list
        + [{ 
        'src': cloud_prepare_inner_item_src_full, 
        'dest': cloud_prepare_inner_item_dest_full, 
        'mode': cloud_prepare_inner_item.mode | default('', true)
        }] 
        }}
    vars: 
      cloud_prepare_inner_item_src_full: "{{ cloud_prepare_env_dir }}/{{ cloud_prepare_inner_item.src }}"
      cloud_prepare_inner_item_dest_full: >-
        {{ cloud_prepare_repo_location }}/{{ 
        ((cloud_prepare_inner_item.root | default(false) | bool) | 
        ternary('', cloud_prepare_pod_env_dir + '/')) 
        + cloud_prepare_inner_item.dest
        }}
    loop: "{{ cloud_prepare_vars_env_files | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest }}"

  - name: "{{ cloud_prepare_inner_title }} - create the directories list var"
    set_fact:
      cloud_prepare_dir_list: "{{ cloud_prepare_dir_list + [cloud_prepare_inner_item.dest | dirname] }}"
    loop: >-
      {{ 
      (cloud_prepare_files_list | default([]))
      + 
      (cloud_prepare_tpl_list | default([])) 
      + 
      (cloud_prepare_env_files_list | default([])) 
      }}
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest | dirname }}"

  ### Create the directories ###

  - name: "{{ cloud_prepare_inner_title }} - create the volume directories"
    become: "{{ cloud_prepare_pod.root }}"
    file:
      state: directory
      path: "{{ cloud_prepare_inner_item.path }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: "{{ cloud_prepare_inner_item.mode }}"
    loop: "{{ cloud_prepare_vars_volumes | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.path }}"
    tags: ["print_action"]

  - name: "{{ cloud_prepare_inner_title }} - create the other directories"
    become: "{{ cloud_prepare_pod.root }}"
    file:
      state: directory
      path: "{{ cloud_prepare_inner_item }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: 0751
    loop: "{{ cloud_prepare_dir_list | unique | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item }}"

  ### Transfer the needed files and templates ###

  - name: "{{ cloud_prepare_inner_title }} - copy the files to the specified locations"
    become: "{{ cloud_prepare_pod.root }}"
    copy:
      remote_src: true
      src: "{{ cloud_prepare_inner_item.src }}"
      dest: "{{ cloud_prepare_inner_item.dest }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: "{{ cloud_prepare_inner_item.mode | default('0640', true) }}"
    loop: "{{ cloud_prepare_files_list | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest }}"
    tags: ["print_action"]
      
  - name: "{{ cloud_prepare_inner_title }} - transfer the templates to the specified locations"
    become: "{{ cloud_prepare_pod.root }}"
    template: 
      src: "{{ cloud_prepare_inner_item.src }}"
      dest: "{{ cloud_prepare_inner_item.dest }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: "{{ cloud_prepare_inner_item.mode | default('0640', true) }}"
    vars:
      params: "{{ cloud_prepare_inner_item.params }}"
    loop: "{{ cloud_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest }}"
    tags: ["print_action"]

  - name: "{{ cloud_prepare_inner_title }} - copy the environment files to the specified locations"
    become: "{{ cloud_prepare_pod.root }}"
    copy:
      src: "{{ cloud_prepare_inner_item.src }}"
      dest: "{{ cloud_prepare_inner_item.dest }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: "{{ cloud_prepare_inner_item.mode | default('0640', true) }}"
    loop: "{{ cloud_prepare_env_files_list | default([]) }}"
    loop_control:
      loop_var: cloud_prepare_inner_item
      label: "{{ cloud_prepare_inner_item.dest }}"
    tags: ["print_action"]
    
  - include_tasks: "{{ cloud_prepare_pod_orchestration.type }}_build.yml"
    when: cloud_prepare_pod_orchestration.type != 'none'

  when: cloud_prepare_diff.changed

- name: "{{ cloud_prepare_inner_title }} - debug - inner"
  debug: 
    msg: "variables unchanged"
  when: not cloud_prepare_diff.changed
  tags: ["print_action"]