### Create / Update the repository ###

- name: "{{ cloud_prepare_inner_title }} - create the repo directory"
  become: "{{ cloud_prepare_pod.root }}"
  file:
    path: "{{ cloud_prepare_repo_location }}"
    state: directory
    mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0777, 0755) }}"

- set_fact:    
    cloud_prepare_pod_inner_repo: >-
      {{ cloud_prepare_repos_dict[cloud_prepare_pod.repo] }}

- include_role: 
    name: "cloud_git"
  vars:
    cloud_git_key: "{{ cloud_prepare_pod.repo }}"
    cloud_git_title: >-
      {{ cloud_prepare_inner_title }} - update the repo directory
      ({{ cloud_prepare_pod.repo }})
    cloud_git_become: "{{ cloud_prepare_pod.root }}"
    cloud_git_repo: "{{ cloud_prepare_pod_inner_repo.src }}"
    cloud_git_version: "{{ cloud_prepare_pod_inner_repo.version }}"
    cloud_git_private: "{{ cloud_prepare_pod_inner_repo.private | default(false) }}"
    cloud_git_key_file_encrypted: >-
      {{ cloud_prepare_env_dir }}/{{ cloud_prepare_pod_inner_repo.key_file_encrypted }}
    cloud_git_dest: "{{ cloud_prepare_repo_location }}"
    cloud_git_tmp_dir: >-
      {{ cloud_prepare_pod_base_dir }}/tmp/repo/{{ cloud_prepare_pod.repo }}
    cloud_git_update: "{{ cloud_prepare_cloud.type != 'local' }}"
    cloud_git_force: "{{ cloud_prepare_cloud.type != 'local' }}"
    cloud_git_dir_mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0777, 0755) }}"

- set_fact:
    cloud_prepare_git_result: "{{ cloud_git_result }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_git_commit: "{{ cloud_prepare_git_result.after }}"
    cloud_prepare_pod_env_dir: "{{ cloud_prepare_pod.env_dir | default('env') }}"
  tags: ["no_print"]

### Create the environment pod repositories in the env folders (when defined) ###

- set_fact:
    cloud_prepare_env_repos_commits: []
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }}"
  include_tasks: "env_repos.yml"
  vars:
    cloud_prepare_pod_inner_env_repo: >-
      {{ cloud_prepare_repos_dict[cloud_prepare_pod_inner_item.repo] }}
  loop: "{{ cloud_prepare_pod.env_repos | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_pod_inner_item
    label: "{{ cloud_prepare_pod_inner_item.repo }}"

### Generate the environment pod context variables ###

- set_fact:
    cloud_prepare_dest_dir_base: >-
      {{ cloud_prepare_pod_env_dir }}/{{ cloud_prepare_pod_identifier }}
  tags: ["no_print"]

- set_fact:
    cloud_prepare_dest_dir_base_full: >-
      {{ cloud_prepare_repo_location }}/{{ cloud_prepare_dest_dir_base }}
  tags: ["no_print"]

- set_fact:
    cloud_prepare_params_pod:
      identifier: "{{ cloud_prepare_pod_identifier }}"
      name: "{{ cloud_prepare_pod_name }}"
      pod: "{{ cloud_prepare_pod }}"
      app: "{{ cloud_prepare_local_app_dict }}"
      git_commit: "{{ cloud_prepare_git_commit }}"
      repo_name: "{{ cloud_prepare_env_name }}"
      env_local_repo: "{{ cloud_prepare_env_local_repo }}"
      repo: "{{ cloud_prepare_pod_inner_repo }}"
      env_dir: "{{ cloud_prepare_pod_env_dir }}"
      repo_location: "{{ cloud_prepare_repo_location }}"
      data_dir: "{{ cloud_prepare_pod_data_dir }}"
      local_data_dir_inside: "{{ cloud_prepare_pod_local_data_dir_inside }}"
      env_cmd: "{{ cloud_prepare_env_cmd }}"
      env_repos_commits: "{{ cloud_prepare_env_repos_commits }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate credentials params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: {}
    params_mixer_group_params_names: "{{ cloud_prepare_pod.credentials | default({}) }}"
    params_mixer_shared_params_names: []
    params_mixer_shared_params_names_dict: {}
    params_mixer_shared_group_params_name: ""
    params_mixer_shared_group_params_names_dict: {}
    params_mixer_params_dict: "{{ cloud_prepare_credentials_dict }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_credentials: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate pod params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ cloud_prepare_pod.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_pod.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_pod.shared_params | default([]) }}"
    params_mixer_shared_params_names_dict: "{{ cloud_prepare_pod_shared_params_dict | default({}) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_pod.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ cloud_prepare_pod_shared_group_params_dict | default({}) }}"
    params_mixer_params_dict: "{{ cloud_prepare_pod_params_dict }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate node params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ cloud_prepare_node.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_node.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_node.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_node.shared_group_params | default('') }}"
    params_mixer_shared_params_names_dict: "{{ cloud_prepare_node_shared_params_dict | default({}) }}"
    params_mixer_shared_group_params_names_dict: "{{ cloud_prepare_node_shared_group_params_dict | default({}) }}"
    params_mixer_params_dict: "{{ cloud_prepare_node_params_dict }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_node_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate node ctx params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ cloud_prepare_node_info.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_node_info.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_node_info.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_node_info.shared_group_params | default('') }}"
    params_mixer_shared_params_names_dict: "{{ cloud_prepare_node_shared_params_dict | default({}) }}"
    params_mixer_shared_group_params_names_dict: "{{ cloud_prepare_node_shared_group_params_dict | default({}) }}"
    params_mixer_params_dict: "{{ cloud_prepare_node_params_dict }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_node_ctx_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_node_params: >-
      {{ cloud_prepare_inner_node_params | combine(cloud_prepare_inner_node_ctx_params) }}
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate pod params with node pod override params"
  include_role:
    name: "params_mixer"
  vars:
    params_mixer_main_params: "{{ cloud_prepare_pod_info.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_pod_info.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_pod_info.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_pod_info.shared_group_params | default('') }}"
    params_mixer_shared_params_names_dict: "{{ cloud_prepare_pod_shared_params_dict | default({}) }}"
    params_mixer_shared_group_params_names_dict: >-
      {{ cloud_prepare_pod_shared_group_params_dict | default({}) }}
    params_mixer_params_dict: "{{ cloud_prepare_pod_params_dict }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_node_pod_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_params: >-
      {{ cloud_prepare_inner_params | combine(cloud_prepare_inner_node_pod_params) }}
  tags: ["no_print"]

- block:

  - name: "{{ cloud_prepare_inner_title }} - generate pod params with ctx pod override params"
    include_role:
      name: "params_mixer"
    vars:
      params_mixer_main_params: "{{ cloud_prepare_node_info_pod_params.params | default({}) }}"
      params_mixer_group_params_names: "{{ cloud_prepare_node_info_pod_params.group_params | default({}) }}"
      params_mixer_shared_params_names: "{{ cloud_prepare_node_info_pod_params.shared_params | default([]) }}"
      params_mixer_shared_group_params_name: "{{ cloud_prepare_node_info_pod_params.shared_group_params | default('') }}"
      params_mixer_shared_params_names_dict: "{{ cloud_prepare_pod_shared_params_dict | default({}) }}"
      params_mixer_shared_group_params_names_dict: >-
        {{ cloud_prepare_pod_shared_group_params_dict | default({}) }}
      params_mixer_params_dict: "{{ cloud_prepare_pod_params_dict }}"
    tags: ["no_print"]

  - set_fact:
      cloud_prepare_inner_ctx_params: "{{ params_mixer_params }}"
    tags: ["no_print"]

  - set_fact:
      cloud_prepare_inner_params: >-
        {{ cloud_prepare_inner_params | combine(cloud_prepare_inner_ctx_params) }}
    tags: ["no_print"]

  when: (cloud_prepare_node_info_pod_params | dict2items | length) > 0

- set_fact:
    cloud_prepare_node_size: >-
      {{ 
      (cloud_prepare_inner_node_params.meta.use_dict | default(false) | bool) | ternary(
      cloud_prepare_inner_node_params.cloud_size_dict[cloud_prepare_cloud.type][cloud_prepare_inner_node_params.size], 
      cloud_prepare_inner_node_params.size) 
      }}
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_node_pod_params:
      size: "{{ cloud_prepare_node_size }}"
      node_pod_params: "{{ cloud_prepare_inner_node_params | default({}) }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_dirs:
      base_dir_rel: "{{ cloud_prepare_base_dir_rel }}"
      apps_dir_base: "{{ cloud_prepare_base_dir_rel }}/apps"
      dest_dir_base: "{{ cloud_prepare_dest_dir_base }}"
      dest_dir_base_full: "{{ cloud_prepare_dest_dir_base_full }}"
  tags: ["no_print"]

### Generate a file with the environment variables and state (for idempotence) ###

- set_fact:
    cloud_prepare_vars_full:
      env_name: "{{ cloud_prepare_env_name }}"
      ctx_name: "{{ cloud_prepare_ctx_name }}"
      main: "{{ cloud_prepare_inner_params }}"
      pod: "{{ cloud_prepare_params_pod }}"
      pod_info: "{{ cloud_prepare_pod_info }}"
      node: "{{ cloud_prepare_inner_node_pod_params }}"
      node_info_pod_params: "{{ cloud_prepare_node_info_pod_params }}"
      credentials: "{{ cloud_prepare_inner_credentials }}"
      dirs: "{{ cloud_prepare_inner_dirs }}"
      dependencies: "{{ cloud_prepare_dependencies }}"
      dependencies_node_ip_dict: "{{ cloud_prepare_dependencies_ip_dict }}"
      dependencies_node_ips_dict: "{{ cloud_prepare_dependencies_ips_dict }}"
  tags: ["no_print"]

- block:
    
  - name: "{{ cloud_prepare_inner_title }} - create the temporary file to verify if there was a change"
    become: "{{ cloud_prepare_pod.root }}"
    copy: 
      content: "{{ cloud_prepare_vars_full | to_nice_yaml }}"
      dest: "{{ cloud_prepare_backup_file_tmp }}"
      owner: "{{ cloud_prepare_owner }}"
      group: "{{ cloud_prepare_group }}"
      mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0666, 0640) }}"

  - name: "{{ cloud_prepare_inner_title }} - get the difference of the 2 files (old and current)"
    become: "{{ cloud_prepare_pod.root }}"
    command: "diff {{ cloud_prepare_backup_file_tmp }} {{ cloud_prepare_backup_file }}"
    register: cloud_prepare_diff
    failed_when: cloud_prepare_diff.rc > 1
    changed_when: cloud_prepare_diff.rc == 1

  when: cloud_prepare_cloud.type != 'local'

### Continue the preparation only when changed from the previous ###

- block:

  ### Copy the specified pod env files and templates ###

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_files is defined in the pod as well as in the node
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod.env_files is defined) and
      (cloud_prepare_pod_info.env_files is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_files is defined in the pod as well as in the context
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod.env_files is defined) and
      (cloud_prepare_node_info_pod_params.env_files is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_files is defined in the node as well as in the context
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod_info.env_files is defined) and
      (cloud_prepare_node_info_pod_params.env_files is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_templates is defined in the pod as well as in the node
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod.env_templates is defined) and
      (cloud_prepare_pod_info.env_templates is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_templates is defined in the pod as well as in the context
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod.env_templates is defined) and
      (cloud_prepare_node_info_pod_params.env_templates is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    fail:
      msg: >-
        env_templates is defined in the node as well as in the context
        (it should be in 1 only)
    when: >-
      (cloud_prepare_pod_info.env_templates is defined) and
      (cloud_prepare_node_info_pod_params.env_templates is defined)
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    include_tasks: "transfer.yml"
    vars:
      cloud_prepare_transfer_title: "{{ cloud_prepare_inner_title }} - pod env"
      cloud_prepare_transfer_src_env_files: >-
        {{ 
        cloud_prepare_node_info_pod_params.env_files 
        | default(cloud_prepare_pod_info.env_files) 
        | default(cloud_prepare_pod.env_files) 
        | default([]) 
        }}
      cloud_prepare_transfer_src_env_templates: >-
        {{ 
        cloud_prepare_node_info_pod_params.env_templates 
        | default(cloud_prepare_pod_info.env_templates) 
        | default(cloud_prepare_pod.env_templates) 
        | default([]) 
        }}

  ### Generate the environment pod expanded variables ###

  - set_fact:
      cloud_prepare_vars_volumes: []
      cloud_prepare_vars_files: []
      cloud_prepare_vars_templates: []
      cloud_prepare_vars_env_files: []
      cloud_prepare_vars_env_templates: []
      cloud_prepare_dir_list: ["{{ cloud_prepare_dest_dir_base_full }}"]
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }} - include_tasks - vars-ctx.yml"
    include_tasks: "vars-ctx.yml"
    vars:
      cloud_prepare_vars_ctx: 
        name: "{{ cloud_prepare_pod.ctx | default('') }}"
        params: "{{ cloud_prepare_vars_full }}"
    when: (cloud_prepare_pod.ctx | default('')) != ''
    tags: ["no_print"]

  - name: "{{ cloud_prepare_inner_title }}"
    include_tasks: "transfer.yml"
    vars:
      cloud_prepare_transfer_title: "{{ cloud_prepare_inner_title }} - ctx"
      cloud_prepare_transfer_src_volumes: "{{ cloud_prepare_vars_volumes | default([]) }}"
      cloud_prepare_transfer_src_dir_list: "{{ cloud_prepare_dir_list | default([]) }}"
      cloud_prepare_transfer_src_repo_files: "{{ cloud_prepare_vars_files | default([]) }}"
      cloud_prepare_transfer_src_env_files: "{{ cloud_prepare_vars_env_files | default([]) }}"
      cloud_prepare_transfer_src_repo_templates: "{{ cloud_prepare_vars_templates | default([]) }}"
      cloud_prepare_transfer_src_env_templates: "{{ (cloud_prepare_vars_env_templates | default([])) }}"
    
  when: (cloud_prepare_diff.changed | default(true) | bool) or (cloud_prepare_cloud.type == 'local')

- name: "{{ cloud_prepare_inner_title }} - debug - inner"
  debug: 
    msg: "variables unchanged"
  when: not (cloud_prepare_diff.changed | default(true) | bool)