
- set_fact:
    cloud_prepare_inner_vars_title: >-
      {{ cloud_prepare_inner_title }} - vars ({{ cloud_prepare_vars_ctx.name }})
  tags: ["no_print"]

- set_fact:
    cloud_prepare_vars_tpl_src: >-
      {{ cloud_prepare_local_pod_repo }}/{{ ''
      }}{{ cloud_prepare_vars_ctx.name }}
    cloud_prepare_vars_tpl_dest: >-
      {{ cloud_prepare_pod_local_tmp_dir }}/vars/cloud_prepare/{{ ''
      }}{{ cloud_prepare_vars_ctx.name }}
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_vars_title }} - create the local directories for the template"
  file:
    path: "{{ cloud_prepare_vars_tpl_dest | dirname }}"
    state: directory
    mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0777, 0755) }}"
  delegate_to: localhost

- name: "{{ cloud_prepare_inner_vars_title }} - populate vars from the template"
  set_fact: 
    cloud_prepare_inner_vars: >-
      {{ lookup('template', cloud_prepare_vars_tpl_src) | from_yaml }}
  vars:
    params: "{{ cloud_prepare_vars_ctx.params }}"
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_volumes: []
    cloud_prepare_inner_vars_files: []
    cloud_prepare_inner_vars_templates: []
    cloud_prepare_inner_vars_env_files: []
    cloud_prepare_inner_vars_env_templates: []
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_volumes: >-
      {{ cloud_prepare_inner_vars_volumes + [cloud_prepare_inner_vars_item] }}
  loop: "{{ cloud_prepare_inner_vars.volumes | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_vars_item
  when: cloud_prepare_inner_vars_item.when | default(true) | bool
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_files: >-
      {{ cloud_prepare_inner_vars_files + [cloud_prepare_inner_vars_item] }}
  loop: "{{ cloud_prepare_inner_vars.files | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_vars_item
  when: cloud_prepare_inner_vars_item.when | default(true) | bool
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_templates: >-
      {{ cloud_prepare_inner_vars_templates + [cloud_prepare_inner_vars_item] }}
  loop: "{{ cloud_prepare_inner_vars.templates | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_vars_item
  when: cloud_prepare_inner_vars_item.when | default(true) | bool
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_env_files: >-
      {{ cloud_prepare_inner_vars_env_files + [cloud_prepare_inner_vars_item] }}
  loop: "{{ cloud_prepare_inner_vars.env_files | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_vars_item
  when: cloud_prepare_inner_vars_item.when | default(true) | bool
  tags: ["no_print"]

- set_fact:
    cloud_prepare_inner_vars_env_templates: >-
      {{ cloud_prepare_inner_vars_env_templates + [cloud_prepare_inner_vars_item] }}
  loop: "{{ cloud_prepare_inner_vars.env_templates | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_vars_item
  when: cloud_prepare_inner_vars_item.when | default(true) | bool
  tags: ["no_print"]

- set_fact:
    cloud_prepare_vars_volumes: >-
      {{ cloud_prepare_vars_volumes + cloud_prepare_inner_vars_volumes }}
    cloud_prepare_vars_files: >-
      {{ cloud_prepare_vars_files + cloud_prepare_inner_vars_files }}
    cloud_prepare_vars_templates: >-
      {{ cloud_prepare_vars_templates + cloud_prepare_inner_vars_templates }}
    cloud_prepare_vars_env_files: >-
      {{ cloud_prepare_vars_env_files + cloud_prepare_inner_vars_env_files }}
    cloud_prepare_vars_env_templates: >-
      {{ cloud_prepare_vars_env_templates + cloud_prepare_inner_vars_env_templates }}
  tags: ["no_print"]

# Call itself recursively for the children
- name: "{{ cloud_prepare_inner_vars_title }} - populate vars from templates (recursive)"
  include_tasks: "vars.yml"
  vars:
    cloud_prepare_vars_ctx: "{{ cloud_prepare_inner_item }}"
  loop: "{{ cloud_prepare_inner_vars.children | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_inner_item
    label: "{{ cloud_prepare_inner_item.name }}"
  when: cloud_prepare_inner_item.when | default(true) | bool