- name: "{{ cloud_prepare_inner_title }} - set_fact - vars"
  set_fact:
    cloud_prepare_vars_tpl_src: >-
      {{ cloud_prepare_local_pod_repo }}/{{ ''
      }}{{ cloud_prepare_inner_item.name }}
    cloud_prepare_vars_tpl_dest: >-
      {{ cloud_prepare_pod_local_tmp_dir }}/vars/cloud_prepare/{{ ''
      }}{{ cloud_prepare_inner_item.name }}

- name: >-
    {{ cloud_prepare_inner_title }} -
    create the local directories for the vars template 
    ({{ cloud_prepare_inner_item.name }})
  file:
    path: "{{ cloud_prepare_vars_tpl_dest | dirname }}"
    state: directory
    mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0777, 0755) }}"
  delegate_to: localhost

- name: >-
    {{ cloud_prepare_inner_title }} -
    populate vars from templates ({{ cloud_prepare_inner_item.name }})
  template: 
    src: "{{ cloud_prepare_vars_tpl_src }}"
    dest: "{{ cloud_prepare_vars_tpl_dest }}"
    mode: "{{ (cloud_prepare_cloud.type == 'local') | ternary(0666, 0640) }}"
  vars:
    params: "{{ cloud_prepare_inner_item.params }}"
  delegate_to: localhost

- name: >-
    {{ cloud_prepare_inner_title }} - load environment vars
    ({{ cloud_prepare_inner_item.name }})
  include_vars:
    file: "{{ cloud_prepare_vars_tpl_dest }}"
    name: cloud_prepare_inner_vars
  delegate_to: localhost

- name: "{{ cloud_prepare_inner_title }} - set_fact ({{ cloud_prepare_inner_item.name }})"
  set_fact:
    cloud_prepare_vars_volumes: >-
      {{ cloud_prepare_vars_volumes + (cloud_prepare_inner_vars.volumes | default([])) }}
    cloud_prepare_vars_files: >-
      {{ cloud_prepare_vars_files + (cloud_prepare_inner_vars.files | default([])) }}
    cloud_prepare_vars_templates: >-
      {{ cloud_prepare_vars_templates + (cloud_prepare_inner_vars.templates | default([])) }}
    cloud_prepare_vars_env_files: >-
      {{ cloud_prepare_vars_env_files + (cloud_prepare_inner_vars.env_files | default([])) }}