- name: "{{ cloud_service_title }} - validate entrypoint service (must be a list)"
  fail:
    msg: "the cloud service list is not defined"
  when: cloud_service_list is not defined
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - validate the cloud service state (required)"
  fail:
    msg: "the cloud service state is not defined"
  when: (cloud_service_state | default('')) == ''
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - validate the cloud service state (value)"
  fail:
    msg: "the cloud service state ({{ cloud_service_state }}) should be either 'present' or 'absent'"
  when: not (cloud_service_state in ['present', 'absent'])
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - cloud_service_next - handle previous cases"
  set_fact:
    cloud_service_next: "{{ tmp_next }}"
  vars:
    tmp_idx: "{{ cloud_service_main_idx | default(0) }}"
    tmp_list: "{{ cloud_service_main_list | default([]) }}"
    tmp_service: "{{ tmp_list[tmp_idx | int] | default({}) }}"
    tmp_next_prev: "{{ cloud_service_next | default({ 'next_list': [] }) }}"
    tmp_next_service_item:
      name: "{{ tmp_service.name | default('') }}"
      namespace: "{{ tmp_service.namespace | default('') }}"
    tmp_next:
      next: "{{ tmp_next_prev }}"
      title: "{{ cloud_service_run_title | default('') }}"
      list: "{{ tmp_list }}"
      idx: "{{ tmp_idx }}"
      name: "{{ tmp_next_service_item.name }}"
      namespace: "{{ tmp_next_service_item.namespace }}"
      result_map: "{{ cloud_service_result_map | default({}) }}"
      next_list: "{{ [tmp_next_service_item] + tmp_next_prev.next_list }}"
  when: not (cloud_service_top | bool)
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - cloud_service_next - initialize"
  set_fact:
    cloud_service_next: { next_list: [] }
  when: cloud_service_top | bool
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - cloud_service_main_list"
  set_fact:
    cloud_service_original_title: "{{ cloud_service_title }}"
    cloud_service_main_list: []
    cloud_service_main_idx: 0
    cloud_service_pending_list: []
    cloud_service_name_list: []
    cloud_service_pending_idx: 0
    cloud_service_result_map: {}
    cloud_service_result_inner_map: {}
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - cloud_service_inner"
  set_fact:
    cloud_service_inner_title: "{{ cloud_service_original_title }}"
    cloud_service_inner_info: ""
    cloud_service_inner_name: ""
    cloud_service_inner_prev_name: ""
    cloud_service_inner:
      list: true
      flat_list: "{{ cloud_service_flat_list | default(false) }}"
      services: "{{ cloud_service_list }}"
    cloud_service_inner_type: ""
  tags: ["no_print"]

- name: "{{ cloud_service_title }} - recursive services"
  include_tasks: "tasks/services/cloud_service_recursive.yml"
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_title }} - cloud_service_run_title"
  set_fact:
    cloud_service_run_title: "{{ cloud_service_original_title }} - run"
  tags: ["no_print"]

- name: "{{ cloud_service_run_title }} - cloud_service_continue - before"
  set_fact:
    cloud_service_continue: >-
      {{ (cloud_service_main_idx | int) < (cloud_service_main_list | length) }}
  tags: ["no_print"]

- name: "{{ cloud_service_run_title }} - execute the service(s)"
  include_tasks: "tasks/services/cloud_service_run.yml"
  when: cloud_service_continue | bool

# set continue as true because it may be called inside a another service
# (to continue running the parent service, if there is one)
- name: "{{ cloud_service_run_title }} - cloud_service_continue - after"
  set_fact:
    cloud_service_continue: true
  tags: ["no_print"]

# set previous values for the parent service (if there is one)
- name: "{{ cloud_service_run_title }} - cloud_service_next - after"
  set_fact:
    cloud_service_next: "{{ tmp_next.next | default({ 'next_list': [] }) }}"
    cloud_service_run_title: "{{ tmp_next.title | default('') }}"
    cloud_service_main_list: "{{ tmp_next.list | default([]) }}"
    cloud_service_main_idx: "{{ tmp_next.idx | default(0) }}"
    cloud_service_result_inner_map: "{{ cloud_service_result_map }}"
    cloud_service_result_map: "{{ tmp_next.result_map | default({}) }}"
  vars:
    tmp_next: "{{ cloud_service_next | default({}) }}"
  tags: ["no_print"]
