- name: "{{ cloud_service_run_title }} - recursive - before"
  block:
    - name: "{{ cloud_service_run_title }} - cloud_service_run - before"
      set_fact:
        cloud_service_run: >-
          {{ cloud_service_main_list[cloud_service_main_idx | int] | default({}) }}
      tags: ["no_print"]

    - name: "{{ cloud_service_run.title }} - cloud_service_name_list"
      fail:
        msg: >-
          the service that would run ({{ cloud_service_run.name }}) has the same namespace
          ({{ cloud_service_run.namespace }}) that a parent or ancestor of this service
          ({{ tmp_item.name }}) has
      when: >-
        (cloud_service_run.namespace != '')
        and
        (cloud_service_run.namespace == tmp_item.namespace)
      loop: "{{ cloud_service_next.next_list }}"
      loop_control:
        loop_var: tmp_item
        label: "{{ tmp_item.name }}"
      tags: ["no_print"]

  when: cloud_service_continue | bool
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_run.title }} - result - initial"
  set_fact:
    cloud_service_result: {}
  tags: ["no_print"]

- name: "{{ cloud_service_run.title }} - execute the service"
  include_tasks: "{{ inner_service_base_dir_prefix }}{{ inner_service_type }}.yml"
  vars:
    cloud_service_top: false
    inner_service_state: "{{ cloud_service_state }}"
    inner_service_title: "{{ cloud_service_run.title }} - inside"
    inner_service_name: "{{ cloud_service_run.name }}"
    inner_service_type: "{{ cloud_service_run.type }}"
    inner_service_namespace: "{{ cloud_service_run.namespace }}"
    inner_service_params: "{{ cloud_service_run.params }}"
    inner_service_credentials: "{{ cloud_service_run.credentials }}"
    inner_service_base_dir_prefix: "{{ cloud_service_run.base_dir_prefix }}"
    inner_service_tmp_dir: "{{ cloud_service_run.tmp_dir }}"
  when: cloud_service_continue | bool
  tags: ["no_print_skipped"]

- name: "{{ cloud_service_run_title }} - cloud_service_run - after"
  set_fact:
    cloud_service_run: >-
      {{ cloud_service_main_list[cloud_service_main_idx | int] | default({}) }}
  when: cloud_service_continue | bool
  tags: ["no_print"]

- name: "{{ cloud_service_run.title }} - result - map"
  set_fact:
    cloud_service_result_map: >-
      {{
        cloud_service_result_map
        | combine({ cloud_service_run.name: cloud_service_result | default({}) })
      }}
  tags: ["no_print"]

- name: "{{ cloud_service_run.title }} - cloud_service_main_idx"
  set_fact:
    cloud_service_main_idx: "{{ (cloud_service_main_idx | int) + 1 }}"
  when: cloud_service_continue | bool
  tags: ["no_print"]

- name: "{{ cloud_service_run.title }} - cloud_service_continue ({{ tmp_continue }})"
  set_fact:
    cloud_service_continue: "{{ tmp_continue }}"
  vars:
    tmp_continue_before: "{{ cloud_service_continue }}"
    tmp_continue: "{{ (cloud_service_main_idx | int) < (cloud_service_main_list | length) }}"
  when: tmp_continue_before | bool
  tags: ["no_print"]

- name: "{{ cloud_service_run.title }} - execute the next service"
  include_tasks: "tasks/services/cloud_service_run.yml"
  when: cloud_service_continue | bool
  tags: ["no_print_skipped"]
