# {{ docker_git_repo }}@{{ docker_git_repo_version }}
templates:
  - "templates/redis.template.yml"

expose:
  - "{{ redis_port | default(6379, true) }}:6379"   # redis

env:
  LANG: {{ lang | default('en_US.UTF-8', true) }}

# any extra arguments for Docker?
# docker_args:

volumes:
  - volume:
      host: {{ host_shared_volume | default('/var/discourse/shared/redis', true) }}
      guest: /shared
  - volume:
      host: {{ host_log_volume | default('/var/discourse/shared/redis/log/var-log', true) }}
      guest: /var/log