templates:
  - "templates/redis.template.yml"

env:
  LANG: {{ lang }}

# any extra arguments for Docker?
# docker_args:

volumes:
  - volume:
      host: {{ host_shared_volume | default('/var/discourse/shared/redis') }}
      guest: /shared
  - volume:
      host: {{ host_log_volume | default('/var/discourse/shared/redis/log/var-log') }}
      guest: /var/log