# {{ docker_git_repo }}@{{ docker_git_repo_version }}
templates:
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"
## Uncomment these two lines if you wish to add Lets Encrypt (https)
  {{ use_ssl | ternary('', '#') }}- "templates/web.ssl.template.yml"
  {{ use_ssl | ternary('', '#') }}- "templates/web.letsencrypt.ssl.template.yml"
## Uncomment this line to add Cloudflare IPs to nginx
  {{ use_cf | ternary('', '#') }}- "templates/cloudflare.template.yml"

## which TCP/IP ports should this container expose?
## If you want Discourse to share a port with another webserver like Apache or nginx,
## see https://meta.discourse.org/t/17247 for details
expose:
  - "{{ http_port | default(80, true) }}:80"   # http
  - "{{ https_port | default(443, true) }}:443" # https

# Use 'links' key to link containers together, aka use Docker --link flag.
links: "{{ links | default([], true) }}"

# any extra arguments for Docker?
# docker_args:

params:
  ## Which Git revision should this container use? (default: tests-passed)
  version: {{ version | default('tests-passed', true) }}

env:
  LANG: {{ lang | default('en_US.UTF-8', true) }}
  DISCOURSE_DEFAULT_LOCALE: {{ locale | default('en', true) }}

  ## How many concurrent web requests are supported? Depends on memory and CPU cores.
  ## will be set automatically by bootstrap based on detected CPUs, or you can override
  UNICORN_WORKERS: {{ workers | default(2, true) }}

  ## TODO: The domain name this Discourse instance will respond to
  DISCOURSE_HOSTNAME: {{ hostname }}

  ## Uncomment if you want the container to be started with the same
  ## hostname (-h option) as specified above (default "$hostname-$config")
  #DOCKER_USE_HOSTNAME: true

  ## TODO: List of comma delimited emails that will be made admin and developer
  ## on initial signup example 'user1@example.com,user2@example.com'
  DISCOURSE_DEVELOPER_EMAILS: '{{ email }}'

  ## TODO: The SMTP mail server used to validate new accounts and send notifications
  # SMTP ADDRESS, username, and password are required
  # WARNING the char '#' in SMTP password can cause problems!
  DISCOURSE_SMTP_ADDRESS: {{ smtp_address }}
  DISCOURSE_SMTP_PORT: {{ smtp_port }}
  DISCOURSE_SMTP_USER_NAME: {{ smtp_user_name }}
  DISCOURSE_SMTP_PASSWORD: "{{ smtp_pass }}"
  DISCOURSE_SMTP_ENABLE_START_TLS: {{ start_tls | default('true', true) }}

  ## If you added the Lets Encrypt template, uncomment below to get a free SSL certificate
  {{ use_ssl | ternary('', '#') }}LETSENCRYPT_ACCOUNT_EMAIL: {{ ssl_email | default('', true) }}

  ## The http or https CDN address for this Discourse instance (configured to pull)
  ## see https://meta.discourse.org/t/14857 for details
  {{ use_cdn | ternary('', '#') }}DISCOURSE_CDN_URL: {{ cdn_url | default('', true) }}

  {{ force_https | ternary('', '#') }}DISCOURSE_FORCE_HTTPS: {{ force_https | default(false, true) }}  
  
  {{ enable_s3_uploads | ternary('', '#') }}DISCOURSE_ENABLE_S3_UPLOADS: {{ enable_s3_uploads | default(true, true) }}
  {{ s3_access_key_id | ternary('', '#') }}DISCOURSE_S3_ACCESS_KEY_ID: "{{ s3_access_key_id | default('', true) }}"
  {{ s3_secret_access_key | ternary('', '#') }}DISCOURSE_S3_SECRET_ACCESS_KEY: "{{ s3_secret_access_key | default('', true) }}"
  {{ s3_region | ternary('', '#') }}DISCOURSE_S3_REGION: "{{ s3_region | default('us-east-1', true) }}"
  {{ s3_upload_bucket | ternary('', '#') }}DISCOURSE_S3_UPLOAD_BUCKET: "{{ s3_upload_bucket | default('', true) }}"
  {{ s3_endpoint | ternary('', '#') }}DISCOURSE_S3_ENDPOINT: "{{ s3_endpoint | default('', true) }}"
  {{ s3_cdn_url | ternary('', '#') }}DISCOURSE_S3_CDN_URL: "{{ s3_cdn_url | default('', true) }}"

  {{ enable_backups | ternary('', '#') }}DISCOURSE_ENABLE_BACKUPS: {{ enable_backups | default(true, true) }}
  {{ backup_location | ternary('', '#') }}DISCOURSE_BACKUP_LOCATION: "{{ backup_location | default('', true) }}"
  {{ maximum_backups | ternary('', '#') }}DISCOURSE_MAXIMUM_BACKUPS: {{ maximum_backups | default(5, true) }}
  {{ backup_frequency | ternary('', '#') }}DISCOURSE_BACKUP_FREQUENCY: {{ backup_frequency | default(7, true) }}
  {{ s3_backup_bucket | ternary('', '#') }}DISCOURSE_S3_BACKUP_BUCKET: "{{ s3_backup_bucket | default('', true) }}"

  ## Connectivity to the databases
  DISCOURSE_DB_SOCKET: ''
  #DISCOURSE_DB_USERNAME: discourse
  #DISCOURSE_DB_PORT: 5432
  DISCOURSE_DB_PASSWORD: '{{ db_pass }}'
  DISCOURSE_DB_HOST: {{ db_host }}
  DISCOURSE_DB_REPLICA_HOST: {{ db_replica_host }}
  DISCOURSE_REDIS_HOST: {{ redis_host }}
  #DISCOURSE_REDIS_PORT: 6379
  DISCOURSE_REDIS_SLAVE_HOST: {{ redis_slave_host }}

volumes:
  - volume:
      host: {{ host_shared_volume | default('/var/discourse/shared/web-only', true) }}
      guest: /shared
  - volume:
      host: {{ host_log_volume | default('/var/discourse/shared/web-only/log/var-log', true) }}
      guest: /var/log

## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          #- git clone https://github.com/discourse/discourse-solved.git

## Remember, this is YAML syntax - you can only have one block with a name
run:
  - exec: echo "Beginning of custom commands"

  ## If you want to configure password login for root, uncomment and change:
  ## Use only one of the following lines:
  #- exec: /usr/sbin/usermod -p 'PASSWORD_HASH' root
  #- exec: /usr/sbin/usermod -p "$(mkpasswd -m sha-256 'RAW_PASSWORD')" root

  ## If you want to authorized additional users, uncomment and change:
  #- exec: ssh-import-id username
  #- exec: ssh-import-id anotherusername

  - exec: echo "End of custom commands"
  - exec: awk -F\# '{print $1;}' ~/.ssh/authorized_keys | awk 'BEGIN { print "Authorized SSH keys for this container:"; } NF>=2 {print $NF;}'
