- name: "{{ cloud_prepare_title }} - nodes tasks (outer)"
  include_tasks: "node.yml"
  vars:
    cloud_prepare_node_info: "{{ cloud_prepare_item }}"
    cloud_prepare_node_name: >-
      {{ cloud_prepare_node_info.name | default(cloud_prepare_node_info) }}
    cloud_prepare_node_key: >-
      {{
        cloud_prepare_node_info.key |
        default(cloud_prepare_node_info.name) |
        default(cloud_prepare_node_info)
      }}
    cloud_prepare_node_title: >-
      {{ cloud_prepare_title }} - node [{{ cloud_prepare_node_name }}{{
        (cloud_prepare_node_name != cloud_prepare_node_key)
        | ternary(' (' + cloud_prepare_node_key + ')', '')
      }}]
    cloud_prepare_node_tmp_dir: >-
      {{ env_ctx_dir }}/cloud/node/{{ cloud_prepare_node_name }}
    cloud_prepare_node_local: >-
      {{ cloud_prepare_node_info.local | default(false, true) }}
    cloud_prepare_env_vars_relative_file_name: "cloud.prepare.vars_full.yml"
    cloud_prepare_local_data_dir_inside: >-
      {{
        (ansible_connection == 'local')
        | ternary(env_local_data_dir | default(''), '')
      }}
  loop: "{{ cloud_prepare_node_list }}"
  loop_control:
    loop_var: cloud_prepare_item
    label: "{{ cloud_prepare_node_name }}"
  when: >-
    ((ansible_connection == 'local') or (cloud_prepare_node_name == (instance_type | default(''))))
    and
    (((env_node | default('')) == '') or (env_node == cloud_prepare_node_name))
    and
    (
      ((ansible_connection == 'local') and (cloud_prepare_node_local | bool))
      or
      ((ansible_connection != 'local') and not (cloud_prepare_node_local | bool))
    )
  tags: ["no_print_skipped"]
