### Create / Update the repository ###

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_pod_inner_repo"
  set_fact:
    cloud_prepare_pod_inner_repo: >-
      {{ env.repos[cloud_prepare_pod.repo] }}
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - pod - repo (outer)"
  include_tasks: "tasks/util/repo.yml"
  vars:
    repo_title: "{{ cloud_prepare_inner_title }} - pod - repo"
    repo_main: "{{ cloud_prepare_pod_inner_repo }}"
    repo_ssh_src_dir: "{{ env_dir }}"
    repo_secrets_dir: "{{ cloud_prepare_secrets_repos_dir }}/{{ cloud_prepare_pod.repo }}"
    repo_default_dir: "{{ cloud_prepare_repo_location }}"
    repo_dev_base_dir: "{{ env_dev_repos_dir }}"
    repo_dev_path: "{{ env_path_map[cloud_prepare_pod.repo] | default('') }}"
    repo_dev: "{{ env_dev and (cloud_prepare_node_local | bool) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_repo_dir"
  set_fact:
    cloud_prepare_repo_dir: "{{ repo_dir }}"
    cloud_prepare_git_result: "{{ repo_git_result }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_local_repo_dir"
  set_fact:
    cloud_prepare_local_repo_dir: "{{ cloud_prepare_local_pod_default_repo_dir }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_local_repo_dir (local)"
  set_fact:
    cloud_prepare_local_repo_dir: "{{ cloud_prepare_repo_dir }}"
  when: cloud_prepare_node_local | bool
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_git_commit"
  set_fact:
    cloud_prepare_git_commit: "{{ cloud_prepare_git_result.after }}"
  tags: ["no_print"]

### Create the environment pod repositories in the env folders (when defined) ###

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_env_repos_commits"
  set_fact:
    cloud_prepare_env_repos_commits: []
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }}"
  include_tasks: "env_repos.yml"
  vars:
    cloud_prepare_pod_inner_env_repo_name: "{{ cloud_prepare_pod_inner_item.repo }}"
    cloud_prepare_pod_inner_env_repo: >-
      {{ env.repos[cloud_prepare_pod_inner_item.repo] }}
  loop: "{{ cloud_prepare_pod.env_repos | default([]) }}"
  loop_control:
    loop_var: cloud_prepare_pod_inner_item
    label: "{{ cloud_prepare_pod_inner_item.repo }}"
  tags: ["no_print"]

### Generate the environment pod context variables ###

- name: "{{ cloud_prepare_inner_title }} - generate credentials params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ cloud_prepare_inner_title }} - generate credentials params"
    params_mixer_main_params: {}
    params_mixer_group_params_names: "{{ cloud_prepare_pod.credentials | default({}) }}"
    params_mixer_shared_params_names: []
    params_mixer_shared_group_params_name: ""
    params_mixer_shared_group_params_names_dict: {}
    params_mixer_shared_params_names_dict: {}
    params_mixer_group_params_dict: "{{ env.credentials | default({}) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_credentials"
  set_fact:
    cloud_prepare_inner_credentials: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate pod params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ cloud_prepare_inner_title }} - generate pod params"
    params_mixer_main_params: "{{ cloud_prepare_pod.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_pod.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_pod.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_pod.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ env.pod_shared_group_params | default({}) | default({}) }}"
    params_mixer_shared_params_names_dict: "{{ env.pod_shared_params | default({}) | default({}) }}"
    params_mixer_group_params_dict: "{{ env.pod_group_params | default({}) | default({}) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_params"
  set_fact:
    cloud_prepare_inner_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate node params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ cloud_prepare_inner_title }} - generate node params"
    params_mixer_main_params: "{{ cloud_prepare_node.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_node.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_node.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_node.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ env.node_shared_group_params | default({}) | default({}) }}"
    params_mixer_shared_params_names_dict: "{{ env.node_shared_params | default({}) | default({}) }}"
    params_mixer_group_params_dict: "{{ env.node_group_params | default({}) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }}"
  set_fact:
    cloud_prepare_inner_node_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate node ctx params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ cloud_prepare_inner_title }} - generate node ctx params"
    params_mixer_main_params: "{{ cloud_prepare_node_info.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_node_info.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_node_info.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_node_info.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: "{{ env.node_shared_group_params | default({}) | default({}) }}"
    params_mixer_shared_params_names_dict: "{{ env.node_shared_params | default({}) | default({}) }}"
    params_mixer_group_params_dict: "{{ env.node_group_params | default({}) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_node_ctx_params"
  set_fact:
    cloud_prepare_inner_node_ctx_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_node_params"
  set_fact:
    cloud_prepare_inner_node_params: >-
      {{ cloud_prepare_inner_node_params | combine(cloud_prepare_inner_node_ctx_params) }}
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - generate pod params with node pod override params (outer)"
  include_tasks: "tasks/util/params_mixer.yml"
  vars:
    params_mixer_title: "{{ cloud_prepare_inner_title }} - generate pod params with node pod override params"
    params_mixer_main_params: "{{ cloud_prepare_pod_info.params | default({}) }}"
    params_mixer_group_params_names: "{{ cloud_prepare_pod_info.group_params | default({}) }}"
    params_mixer_shared_params_names: "{{ cloud_prepare_pod_info.shared_params | default([]) }}"
    params_mixer_shared_group_params_name: "{{ cloud_prepare_pod_info.shared_group_params | default('') }}"
    params_mixer_shared_group_params_names_dict: >-
      {{ env.pod_shared_group_params | default({}) | default({}) }}
    params_mixer_shared_params_names_dict: "{{ env.pod_shared_params | default({}) | default({}) }}"
    params_mixer_group_params_dict: "{{ env.pod_group_params | default({}) | default({}) }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_node_pod_params"
  set_fact:
    cloud_prepare_inner_node_pod_params: "{{ params_mixer_params }}"
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_params"
  set_fact:
    cloud_prepare_inner_params: >-
      {{ cloud_prepare_inner_params | combine(cloud_prepare_inner_node_pod_params) }}
  tags: ["no_print"]

- block:
    - name: "{{ cloud_prepare_inner_title }} - generate pod params with ctx pod override params (outer)"
      include_tasks: "tasks/util/params_mixer.yml"
      vars:
        params_mixer_title: "{{ cloud_prepare_inner_title }} - generate pod params with ctx pod override params"
        params_mixer_main_params: "{{ cloud_prepare_node_info_pod_params.params | default({}) }}"
        params_mixer_group_params_names: "{{ cloud_prepare_node_info_pod_params.group_params | default({}) }}"
        params_mixer_shared_params_names: "{{ cloud_prepare_node_info_pod_params.shared_params | default([]) }}"
        params_mixer_shared_group_params_name: "{{ cloud_prepare_node_info_pod_params.shared_group_params | default('') }}"
        params_mixer_shared_group_params_names_dict: >-
          {{ env.pod_shared_group_params | default({}) | default({}) }}
        params_mixer_shared_params_names_dict: "{{ env.pod_shared_params | default({}) | default({}) }}"
        params_mixer_group_params_dict: "{{ env.pod_group_params | default({}) | default({}) }}"
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_ctx_params"
      set_fact:
        cloud_prepare_inner_ctx_params: "{{ params_mixer_params }}"
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }} - cloud_prepare_inner_ctx_params"
      set_fact:
        cloud_prepare_inner_params: >-
          {{ cloud_prepare_inner_params | combine(cloud_prepare_inner_ctx_params) }}
      tags: ["no_print"]

  when: (cloud_prepare_node_info_pod_params | dict2items | length) > 0
  tags: ["no_print_skipped"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_pod_data_dir"
  set_fact:
    cloud_prepare_pod_data_dir: "{{ cloud_prepare_remote_pod_data_dir }}"
    cloud_prepare_pod_extra_repos_dir: ""
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_base_dir_rel"
  set_fact:
    cloud_prepare_base_dir_rel: >-
      {{ env_dev_repos_dir | relpath(cloud_prepare_repo_dir) }}
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_pod_data_dir (local)"
  set_fact:
    cloud_prepare_pod_data_dir: >-
      {{ cloud_prepare_base_dir_rel + '/data/' + cloud_prepare_pod_identifier }}
    cloud_prepare_pod_extra_repos_dir: >-
      {{ env_dev_extra_repos_dir | relpath(cloud_prepare_repo_dir) }}
  when: cloud_prepare_node_local | bool
  tags: ["no_print"]

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_params_pod"
  set_fact:
    cloud_prepare_params_pod:
      identifier: "{{ cloud_prepare_pod_identifier }}"
      name: "{{ cloud_prepare_pod_name }}"
      pod: "{{ cloud_prepare_pod }}"
      git_commit: "{{ cloud_prepare_git_commit }}"
      env_repos_commits: "{{ cloud_prepare_env_repos_commits }}"
      repo_location: "{{ cloud_prepare_repo_dir }}"
      base_dir_rel: "{{ cloud_prepare_base_dir_rel }}"
      data_dir: "{{ cloud_prepare_pod_data_dir }}"
      extra_repos_dir: "{{ cloud_prepare_pod_extra_repos_dir }}"
  tags: ["no_print"]

### Generate a file with the environment variables and state (for idempotence) ###

- name: "{{ cloud_prepare_inner_title }} - cloud_prepare_vars_full"
  set_fact:
    cloud_prepare_vars_full:
      env_name: "{{ env.name }}"
      ctx_name: "{{ env_ctx_name }}"
      main: "{{ cloud_prepare_inner_params }}"
      pod: "{{ cloud_prepare_params_pod }}"
      credentials: "{{ cloud_prepare_inner_credentials }}"
      dependencies: "{{ cloud_prepare_dependencies }}"
      dependencies_node_ip_dict: "{{ cloud_prepare_dependencies_ip_dict }}"
      dependencies_node_ips_dict: "{{ cloud_prepare_dependencies_ips_dict }}"
  tags: ["no_print"]

- block:
    - name: "{{ cloud_prepare_inner_title }} - create the temporary file to verify if there was a change"
      become: "{{ cloud_prepare_pod.root }}"
      copy:
        content: "{{ cloud_prepare_vars_full | to_nice_yaml }}"
        dest: "{{ cloud_prepare_backup_file_tmp }}"
        owner: "{{ cloud_prepare_owner }}"
        group: "{{ cloud_prepare_group }}"
        mode: "{{ (cloud_prepare_node_local | bool) | ternary(0666, 0640) }}"
      tags: ["no_print_skipped"]

    - name: "{{ cloud_prepare_inner_title }} - get the difference of the 2 files (old and current)"
      become: "{{ cloud_prepare_pod.root }}"
      command: "diff {{ cloud_prepare_backup_file_tmp }} {{ cloud_prepare_backup_file }}"
      register: cloud_prepare_diff
      failed_when: cloud_prepare_diff.rc > 1
      changed_when: cloud_prepare_diff.rc == 1
      tags: ["no_print_skipped"]

  when: not (cloud_prepare_node_local | bool)
  tags: ["no_print_skipped"]

### Continue the preparation only when changed from the previous ###

- block:
    ### Copy the specified pod env files and templates ###

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_files is defined in the pod as well as in the node
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod.env_files is defined) and
        (cloud_prepare_pod_info.env_files is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_files is defined in the pod as well as in the context
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod.env_files is defined) and
        (cloud_prepare_node_info_pod_params.env_files is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_files is defined in the node as well as in the context
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod_info.env_files is defined) and
        (cloud_prepare_node_info_pod_params.env_files is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_templates is defined in the pod as well as in the node
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod.env_templates is defined) and
        (cloud_prepare_pod_info.env_templates is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_templates is defined in the pod as well as in the context
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod.env_templates is defined) and
        (cloud_prepare_node_info_pod_params.env_templates is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      fail:
        msg: >-
          env_templates is defined in the node as well as in the context
          (it should be in 1 only)
      when: >-
        (cloud_prepare_pod_info.env_templates is defined) and
        (cloud_prepare_node_info_pod_params.env_templates is defined)
      tags: ["no_print"]

    - name: "{{ cloud_prepare_inner_title }}"
      include_tasks: "transfer.yml"
      vars:
        cloud_prepare_transfer_title: "{{ cloud_prepare_inner_title }} - pod env"
        cloud_prepare_transfer_src_env_files: >-
          {{
          cloud_prepare_node_info_pod_params.env_files
          | default(cloud_prepare_pod_info.env_files)
          | default(cloud_prepare_pod.env_files)
          | default([])
          }}
        cloud_prepare_transfer_src_env_templates: >-
          {{
          cloud_prepare_node_info_pod_params.env_templates
          | default(cloud_prepare_pod_info.env_templates)
          | default(cloud_prepare_pod.env_templates)
          | default([])
          }}
      tags: ["no_print"]

    ### Generate the environment pod expanded variables ###

    - name: "{{ cloud_prepare_inner_title }}"
      set_fact:
        cloud_prepare_vars_volumes: []
        cloud_prepare_vars_files: []
        cloud_prepare_vars_templates: []
        cloud_prepare_vars_env_files: []
        cloud_prepare_vars_env_templates: []
        cloud_prepare_dir_list: []
      tags: ["no_print"]

    - block:
        - name: "{{ cloud_prepare_inner_title }}"
          set_fact:
            cloud_prepare_inner_vars_ctxs: "{{ [cloud_prepare_vars_ctx] }}"
            cloud_prepare_inner_vars_idx: 0
            cloud_prepare_inner_vars_ctxs_completed: []
          vars:
            cloud_prepare_vars_ctx:
              name: "{{ cloud_prepare_pod.ctx | default('') }}"
              params: "{{ cloud_prepare_vars_full }}"
          tags: ["no_print"]

        - name: "{{ cloud_prepare_inner_title }} - include_tasks - vars_ctx.yml"
          include_tasks: "vars_ctx.yml"
          tags: ["no_print"]

      when: (cloud_prepare_pod.ctx | default('')) != ''
      tags: ["no_print_skipped"]

    - name: "{{ cloud_prepare_inner_title }}"
      include_tasks: "transfer.yml"
      vars:
        cloud_prepare_transfer_title: "{{ cloud_prepare_inner_title }} - ctx"
        cloud_prepare_transfer_src_volumes: "{{ cloud_prepare_vars_volumes | default([]) }}"
        cloud_prepare_transfer_src_dir_list: "{{ cloud_prepare_dir_list | default([]) }}"
        cloud_prepare_transfer_src_repo_files: "{{ cloud_prepare_vars_files | default([]) }}"
        cloud_prepare_transfer_src_env_files: "{{ cloud_prepare_vars_env_files | default([]) }}"
        cloud_prepare_transfer_src_repo_templates: "{{ cloud_prepare_vars_templates | default([]) }}"
        cloud_prepare_transfer_src_env_templates: "{{ (cloud_prepare_vars_env_templates | default([])) }}"
      tags: ["no_print"]

  when: (cloud_prepare_diff.changed | default(true) | bool) or (cloud_prepare_node_local | bool)
  tags: ["no_print_skipped"]

- name: "{{ cloud_prepare_inner_title }} - debug - inner"
  debug:
    msg: "variables unchanged"
  when: (not (cloud_prepare_diff.changed | default(true) | bool)) and (not (cloud_prepare_node_local | bool))
  tags: ["no_print_skipped"]
