### Validation ###

- name: "{{ compose_prepare_title }} - verify the pod environment variables"
  fail:
    msg: "[Error] Specify the environment repo variable: pod[{{ compose_prepare_item }}]"
  when: ((compose_prepare_pod[compose_prepare_item] | default('')) == '')
  loop:
  - "repo"
  - "repo_version"
  - "ctx_dir"
  - "vars_dir"
  loop_control:
    loop_var: compose_prepare_item

- name: "{{ compose_prepare_title }} - verify the context environment variables"
  fail:
    msg: "[Error] Specify the variable '{{ compose_prepare_item }}' of all contexts"
  when: ((compose_prepare_context[compose_prepare_item] | default('')) == '')
  loop:
  - "group"
  - "name"
  - "file"
  loop_control:
    loop_var: compose_prepare_item

- name: "{{ compose_prepare_title }} - verify if the temporary dir is specified"
  fail:
    msg: "The parameter compose_prepare_local_tmp_dir must be specified"
  when: ((compose_prepare_local_tmp_dir | default('')) == '')

- name: "{{ compose_prepare_title }} - set_fact - base directory"
  set_fact:
    compose_prepare_base_dir: "/var/main/{{ compose_prepare_context.name }}"

- name: "{{ compose_prepare_title }} - set_fact - locations"
  set_fact:
    compose_prepare_data_dir: "{{ compose_prepare_base_dir }}/data"
    compose_prepare_ctx_dir: "{{ compose_prepare_pod.ctx_dir }}"
    compose_prepare_vars_dir: "{{ compose_prepare_pod.vars_dir }}"
    compose_prepare_owner: "{{ compose_prepare_host_user }}"
    compose_prepare_group: "{{ compose_prepare_host_group }}"
    compose_prepare_backup_file: >-
      {{ compose_prepare_base_dir }}/{{ compose_prepare_file_env_vars_relative }}
    compose_prepare_backup_file_tmp: >-
      {{ compose_prepare_base_dir }}/{{ compose_prepare_file_env_vars_relative }}.tmp
    
### Prepare the directories ###

- name: "{{ compose_prepare_title }} - create the local directories"
  file:
    path: "{{ compose_prepare_item }}"
    state: directory
    mode: 0700
  loop:
  - "{{ compose_prepare_local_tmp_dir }}"
  - "{{ compose_prepare_local_tmp_dir }}/templates"
  loop_control:
    loop_var: compose_prepare_item
  delegate_to: localhost

- name: "{{ compose_prepare_title }} - create the remote directories"
  become: "{{ compose_prepare_docker_become }}"
  file:
    path: "{{ compose_prepare_item | dirname }}"
    state: directory
    mode: 0700
  loop:
  - "{{ compose_prepare_backup_file }}"
  - "{{ compose_prepare_backup_file_tmp }}"
  loop_control:
    loop_var: compose_prepare_item
    label: "{{ compose_prepare_item | dirname }}"

- name: >-
    {{ compose_prepare_title }} - create the file to verify if there was a change, 
    if it was not created before
  become: "{{ compose_prepare_docker_become }}"
  copy: 
    force: no
    content: ""
    dest: "{{ compose_prepare_backup_file }}"
    owner: "{{ compose_prepare_owner }}"
    group: "{{ compose_prepare_group }}"
    mode: 0600

### Ensure docker is running and update the docker-compose executable ###

- name: "{{ compose_prepare_title }} - ensure docker is running"
  become: "{{ compose_prepare_docker_become }}"
  service: 
    name: docker
    state: started

- name: "{{ compose_prepare_title }} - copy the docker compose executable file"
  become: "{{ compose_prepare_docker_become }}"
  copy: 
    src: "roles/compose_prepare/files/docker-compose.sh"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

### Prepare the temporary directory (to catch errors before updating the real one) ###

- name: "{{ compose_prepare_title }} - prepare the temporary directory"
  include_tasks: "prepare.yml"
  vars:
    compose_prepare_repo_location: >-
      {{ compose_prepare_base_dir }}/tmp/pod-tmp-{{ compose_prepare_context.name }}
  
### Prepare the real directory ###

- name: "{{ compose_prepare_title }} - get the difference of the 2 files (old and current)"
  become: "{{ compose_prepare_docker_become }}"
  command: "diff {{ compose_prepare_backup_file_tmp }} {{ compose_prepare_backup_file }}"
  register: compose_prepare_diff
  failed_when: compose_prepare_diff.rc > 1
  changed_when: compose_prepare_diff.rc == 1

- block:

  - name: "{{ compose_prepare_title }} - prepare the real directory"
    include_tasks: "prepare.yml"
    vars:
      compose_prepare_repo_location: >-
        {{ compose_prepare_base_dir }}/pod-{{ compose_prepare_context.name }}

  - name: >-
      {{ compose_prepare_title }} - 
      update the file to verify if there was a change (for newer runs)
    become: "{{ compose_prepare_docker_become }}"
    copy: 
      remote_src: yes
      src: "{{ compose_prepare_backup_file_tmp }}"
      dest: "{{ compose_prepare_backup_file }}"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: 0600
    tags: ["print_action"]

  when: compose_prepare_diff.changed

- name: "{{ compose_prepare_title }} - debug - outer"
  debug: 
    msg: "variables unchanged"
  when: not compose_prepare_diff.changed
  tags: ["print_action"]