### Validation ###

- name: "{{ compose_prepare_title }} - verify the pod environment variables"
  fail:
    msg: "[Error] Specify the environment repo variable: pod[{{ compose_prepare_item }}]"
  when: ((compose_prepare_pod[compose_prepare_item] | default('')) == '')
  loop:
  - "repo"
  - "repo_version"
  - "ctx_dir"
  - "vars_dir"
  loop_control:
    loop_var: compose_prepare_item

- name: "{{ compose_prepare_title }} - verify the context environment variables"
  fail:
    msg: "[Error] Specify the variable '{{ compose_prepare_item }}' of all contexts"
  when: ((compose_prepare_context[compose_prepare_item] | default('')) == '')
  loop:
  - "group"
  - "name"
  - "file"
  loop_control:
    loop_var: compose_prepare_item

- name: "{{ compose_prepare_title }} - verify if the temporary dir is specified"
  fail:
    msg: "The parameter compose_prepare_local_tmp_dir must be specified"
  when: ((compose_prepare_local_tmp_dir | default('')) == '')

### Prepare the directories and repository ###

- name: "{{ compose_prepare_title }} - set_fact - base directory"
  set_fact:
    compose_prepare_base_dir: "/var/main/{{ compose_prepare_context.name }}"

- name: "{{ compose_prepare_title }} - set_fact - locations"
  set_fact:
    compose_prepare_repo_location: "{{ compose_prepare_base_dir }}/pod"
    compose_prepare_data_dir: "{{ compose_prepare_base_dir }}/data"
    compose_prepare_repo_location_tmp: "{{ compose_prepare_base_dir }}/tmp/pod-tmp"
    compose_prepare_env_location_backup: "{{ compose_prepare_base_dir }}/tmp/env"
    compose_prepare_ctx_dir: "{{ compose_prepare_pod.ctx_dir }}"
    compose_prepare_vars_dir: "{{ compose_prepare_pod.vars_dir }}"

- name: "{{ compose_prepare_title }} - ensure docker is running"
  become: "{{ compose_prepare_docker_become }}"
  service: 
    name: docker
    state: started

- name: "{{ compose_prepare_title }} - copy the docker compose executable file"
  become: "{{ compose_prepare_docker_become }}"
  copy: 
    src: "roles/compose_prepare/files/docker-compose.sh"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755

- name: "{{ compose_prepare_title }} - create the local directories"
  file:
    path: "{{ compose_prepare_item }}"
    state: directory
    mode: 0700
  loop:
  - "{{ compose_prepare_local_tmp_dir }}"
  - "{{ compose_prepare_local_tmp_dir }}/templates"
  loop_control:
    loop_var: compose_prepare_item
  delegate_to: localhost

- name: "{{ compose_prepare_title }} - create the remote directories"
  become: "{{ compose_prepare_docker_become }}"
  file:
    path: "{{ compose_prepare_item }}"
    state: directory
    mode: 0700
  loop:
  - "{{ compose_prepare_repo_location }}"
  - "{{ compose_prepare_repo_location_tmp }}"
  - "{{ compose_prepare_env_location_backup }}"
  loop_control:
    loop_var: compose_prepare_item

- name: "{{ compose_prepare_title }} - update the temporary repo directory"
  become: "{{ compose_prepare_docker_become }}"
  git:
    repo: "{{ compose_prepare_pod.repo }}"
    version: "{{ compose_prepare_pod.repo_version }}"
    dest: "{{ compose_prepare_repo_location_tmp }}"
    update: yes
    force: yes
  register: compose_prepare_git_result
  tags: ["print_action"]

- name: "{{ compose_prepare_title }} - set_fact - vars"
  set_fact:
    compose_prepare_git_commit: "{{ compose_prepare_git_result.after }}"

### Generate the environment pod context variables ###

- name: "{{ compose_prepare_title }} - populate vars from templates (debug)"
  debug: 
    msg: "populate vars from templates"
  tags: ["print_action"]

- name: "{{ compose_prepare_title }} - set_fact - vars"
  set_fact:
    compose_prepare_ctx_tpl_src_remote: >-
      {{ compose_prepare_repo_location }}/{{
      }}{{ compose_prepare_ctx_dir }}/{{
      }}{{ compose_prepare_context.file }}
    compose_prepare_ctx_tpl_src: >-
      {{ compose_prepare_local_tmp_dir }}/compose_prepare_ctx.tpl.yml"
    compose_prepare_ctx_tpl_dest: >-
      {{ compose_prepare_local_tmp_dir }}/compose_prepare_ctx.yml"

- name: >-
    {{ compose_prepare_title }} - 
    create the local directories for the context template
  file:
    path: "{{ compose_prepare_ctx_tpl_src | dirname }}"
    state: directory
    mode: 0600
  delegate_to: localhost

- name: "{{ compose_prepare_title }} - fetch the context template from a single remote host"
  become: "{{ compose_prepare_docker_become }}"
  run_once: true
  fetch:
    src: "{{ compose_prepare_ctx_tpl_src_remote }}"
    dest: "{{ compose_prepare_ctx_tpl_src }}"
    flat: yes
    fail_on_missing: yes
  
- name: "{{ compose_prepare_title }} - get the context variables from templates"
  template: 
    src: "{{ compose_prepare_ctx_tpl_src }}"
    dest: "{{ compose_prepare_ctx_tpl_dest }}"
    mode: 0600
  vars:
    params: "{{ compose_prepare_params }}"
    params_aux:
      pod: "{{ compose_prepare_pod }}"
      git_commit: "{{ compose_prepare_git_result.after }}"
      repo_name: "{{ compose_prepare_repo_name }}"
      data_dir: "{{ compose_prepare_data_dir }}"
  delegate_to: localhost

- name: >-
    {{ compose_prepare_title }} - 
    load ctx environment vars ({{ compose_prepare_context.name }})
  include_vars:
    file: "{{ compose_prepare_ctx_tpl_dest }}"
    name: compose_prepare_ctx_outer_params
  delegate_to: localhost

### Generate the environment pod expanded variables ###

- name: "{{ compose_prepare_title }} - set_fact - vars"
  set_fact:
    compose_prepare_vars_volumes: []
    compose_prepare_vars_files: []
    compose_prepare_vars_templates: []
    compose_prepare_vars_env_files: []

- name: "{{ compose_prepare_title }} - set_fact - compose_prepare_ctx_params"
  set_fact:
    compose_prepare_ctx_params: "{{ compose_prepare_ctx_outer_params.params }}"

- name: "{{ compose_prepare_title }} - populate vars from templates (outer)"
  include_tasks: "vars.yml"
  loop: "{{ compose_prepare_ctx_params }}"
  loop_control:
    loop_var: compose_prepare_item
    label: "{{ compose_prepare_item.name }}"

### Generate a file with all the environment pod expanded variables ###

- name: "{{ compose_prepare_title }} - set_fact - vars_full"
  set_fact:
    compose_prepare_vars_full:
      volumes: "{{ compose_prepare_vars_volumes }}"
      files: "{{ compose_prepare_vars_files }}"
      templates: "{{ compose_prepare_vars_templates }}"
      env_files: "{{ compose_prepare_vars_env_files }}"

- name: >-
    {{ compose_prepare_title }} - create the file to verify if there was a change, 
    if it was not created before
  become: "{{ compose_prepare_docker_become }}"
  copy: 
    force: no
    content: ""
    dest: "{{ compose_prepare_env_location_backup }}/compose_prepare_vars_full.yml"
    owner: "{{ compose_prepare_owner }}"
    group: "{{ compose_prepare_group }}"
    mode: 0600

- name: "{{ compose_prepare_title }} - create the temporary file to verify if there was a change"
  become: "{{ compose_prepare_docker_become }}"
  copy: 
    content: "{{ compose_prepare_vars_full | to_nice_yaml }}"
    dest: "{{ compose_prepare_env_location_backup }}/compose_prepare_tmp_vars_full.yml"
    owner: "{{ compose_prepare_owner }}"
    group: "{{ compose_prepare_group }}"
    mode: 0600

- name: "{{ compose_prepare_title }} - get the difference of the 2 files (old and current)"
  become: "{{ compose_prepare_docker_become }}"
  command: >-
    diff 
    {{ compose_prepare_env_location_backup }}/compose_prepare_tmp_vars_full.yml 
    {{ compose_prepare_env_location_backup }}/compose_prepare_vars_full.yml
  register: compose_prepare_diff
  failed_when: compose_prepare_diff.rc > 1
  changed_when: compose_prepare_diff.rc == 1

### Use the environment pod expanded variables to generate the pod files when changed ###

- block:

  - name: "{{ compose_prepare_title }} - set_fact - compose_prepare_tpl_list - empty"
    set_fact:
      compose_prepare_tpl_list: []

  - name: "{{ compose_prepare_title }} - set_fact - compose_prepare_tpl_list - fill"
    set_fact:
      compose_prepare_tpl_list: >-
        {{ 
        compose_prepare_tpl_list
        + [{ 
        'remote_src': compose_prepare_item_src_full, 
        'src': compose_prepare_item_src_local_full,
        'dest': compose_prepare_item_dest_full, 
        'mode': compose_prepare_item.mode | default('', true), 
        'params': compose_prepare_item_params
        }] 
        }}
    vars: 
      compose_prepare_item_remote_src_full: >-
        {{ compose_prepare_repo_location }}/templates/{{ compose_prepare_item.src }}
      compose_prepare_item_src_local_full: >-
        {{ compose_prepare_local_tmp_dir }}/templates/{{ compose_prepare_item.src }}
      compose_prepare_item_dest_full: >-
        {{ compose_prepare_repo_location }}/{{ 
        ((compose_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + (compose_prepare_item.dest | default(compose_prepare_item.src)) 
        }}
      compose_prepare_item_params: "{{ compose_prepare_item.params | default({}) }}"
    loop: "{{ compose_prepare_vars_templates | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest | default(compose_prepare_item.src) }}"

  - name: "{{ compose_prepare_title }} - create the volume directories"
    become: "{{ compose_prepare_docker_become }}"
    file:
      state: directory
      path: "{{ compose_prepare_item.path }}"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: "{{ compose_prepare_item.mode }}"
    loop: "{{ compose_prepare_vars_volumes | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.path }}"

  - name: "{{ compose_prepare_title }} - copy the files to the specified locations"
    become: "{{ compose_prepare_docker_become }}"
    copy:
      src: "{{ compose_prepare_item_src_full }}"
      dest: "{{ compose_prepare_item_dest_full }}"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: 0600
    vars: 
      compose_prepare_item_src_full: >-
        {{ compose_prepare_repo_location }}/files/{{ compose_prepare_item.src }}
      compose_prepare_item_dest_full: >-
        {{ compose_prepare_repo_location }}/{{ 
        ((compose_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + (compose_prepare_item.dest | default(compose_prepare_item.src)) 
        }}
    loop: "{{ compose_prepare_vars_files | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest | default(compose_prepare_item.src) }}"
    tags: ["print_action"]

  - name: >-
      {{ compose_prepare_title }} - 
      create the local directories for the repository templates
    file:
      path: "{{ compose_prepare_item.src | dirname }}"
      state: directory
      mode: 0700
    loop: "{{ compose_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest | dirname }}"
    delegate_to: localhost

  - name: "{{ compose_prepare_title }} - create directories for the repository templates"
    become: "{{ compose_prepare_docker_become }}"
    file:
      path: "{{ compose_prepare_item.dest | dirname }}"
      state: directory
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: 0700
    loop: "{{ compose_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest | dirname }}"

  - name: "{{ compose_prepare_title }} - fetch the vars templates from a single remote host"
    become: "{{ compose_prepare_docker_become }}"
    run_once: true
    fetch:
      src: "{{ compose_prepare_item.remote_src }}"
      dest: "{{ compose_prepare_item.src }}"
      flat: yes
      fail_on_missing: yes
    loop: "{{ compose_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest }}"
    tags: ["print_action"]
      
  - name: "{{ compose_prepare_title }} - transfer the templates to the specified locations"
    become: "{{ compose_prepare_docker_become }}"
    template: 
      src: "{{ compose_prepare_item.src }}"
      dest: "{{ compose_prepare_item.dest }}"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: "{{ compose_prepare_item.mode | default('0600', true) }}"
    vars:
      params: "{{ compose_prepare_item.params }}"
    loop: "{{ compose_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest }}"
    tags: ["print_action"]

  - name: "{{ compose_prepare_title }} - copy the environment files to the specified locations"
    become: "{{ compose_prepare_docker_become }}"
    copy:
      src: "{{ compose_prepare_item_src_full }}"
      dest: "{{ compose_prepare_item_dest_full }}"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: "{{ compose_prepare_item.mode | default('0600', true) }}"
    vars: 
      compose_prepare_item_src_full: >-
        {{ compose_prepare_local_env_dir }}/{{ compose_prepare_item.src }}
      compose_prepare_item_dest_full: >-
        {{ compose_prepare_repo_location }}/{{ 
        ((compose_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + compose_prepare_item.dest
        }}
    loop: "{{ compose_prepare_vars_env_files | default([]) }}"
    loop_control:
      loop_var: compose_prepare_item
      label: "{{ compose_prepare_item.dest }}"
    tags: ["print_action"]

  - name: >-
      {{ compose_prepare_title }} - 
      create the file to verify if there was a change (for newer runs)
    become: "{{ compose_prepare_docker_become }}"
    copy: 
      remote_src: yes
      src: "{{ compose_prepare_env_location_backup }}/compose_prepare_tmp_vars_full.yml"
      dest: "{{ compose_prepare_env_location_backup }}/compose_prepare_vars_full.yml"
      owner: "{{ compose_prepare_owner }}"
      group: "{{ compose_prepare_group }}"
      mode: 0600
    tags: ["print_action"]

  when: compose_prepare_diff.changed

- name: "{{ compose_prepare_title }} - debug"
  debug: 
    msg: "variables unchanged"
  when: not compose_prepare_diff.changed
  tags: ["print_action"]





- block:

  - set_fact:
      compose_prepare_docker_compose_cmd: "docker-compose -f {{ compose_prepare_docker_compose_file }}"

  - name: "{{ compose_prepare_title }} - prepare the temporary images (pull and build)"
    become: "{{ compose_prepare_docker_become }}"
    command: "{{ compose_prepare_item }}"
    args:
      chdir: "{{ compose_prepare_repo_location_tmp }}/"
    loop:
    - "{{ compose_prepare_docker_compose_cmd }} pull"
    - "{{ compose_prepare_docker_compose_cmd }} build --pull"
    loop_control:
      loop_var: compose_prepare_item
    tags: ["print_action"]

  - name: "{{ compose_prepare_title }} - update the repo directory"
    become: "{{ compose_prepare_docker_become }}"
    git:
      repo: "{{ compose_prepare_pod_repo }}"
      version: "{{ compose_prepare_pod_repo_version }}"
      dest: "{{ compose_prepare_repo_location }}"
      update: yes
    tags: ["print_action"]

  - name: "{{ compose_prepare_title }} - copy the env file"
    become: "{{ compose_prepare_docker_become }}"
    copy: 
      remote_src: yes
      src: "{{ compose_prepare_repo_location_tmp }}/.env"
      dest: "{{ compose_prepare_repo_location }}/.env"
      mode: 0600

  - name: "{{ compose_prepare_title }} - prepare the images (build)"
    become: "{{ compose_prepare_docker_become }}"
    command: "{{ compose_prepare_docker_compose_cmd }} build"
    args:
      chdir: "{{ compose_prepare_repo_location }}/"
    tags: ["print_action"]
    
  - name: "{{ compose_prepare_title }} - backup the env file"
    become: "{{ compose_prepare_docker_become }}"
    copy: 
      remote_src: yes
      src: "{{ compose_prepare_repo_location }}/.env"
      dest: "{{ compose_prepare_env_location_backup }}/.env"
      mode: 0600

  when: "compose_prepare_diff.changed" 