- name: "{{ cloud_dns_title }} - cloudflare dns"
  cloudflare_dns:
    zone: "{{ cloud_dns_zone | default(omit, true) }}"
    proxied: no
    solo: "{{ (cloud_dns_state == 'present') | ternary(true, false) }}"
    type: "{{ cloud_dns_record_type }}"
    record: "{{ cloud_dns_record | default(omit, true) }}"
    value: "{{ cloud_dns_value | default(omit, true) }}"
    account_email: "{{ cloud_dns_credentials.email }}"
    account_api_token: "{{ cloud_dns_credentials.token }}"
    state: "{{ cloud_dns_state }}"
  tags: ["print_action"]
