- set_fact:
    main_vars_cloud_shutdown: "{{ env.cloud_shutdown | default(0) }}"

- set_fact:
    main_vars_dns:
      cloudflare:
        task: "cloudflare_dns"
        zone: "{{ env.dns_zone | default('') }}"
        credentials:
          account_email: "{{ env.dns_cloudflare_email | default('') }}"
          account_api_token: "{{ env.dns_cloudflare_token | default('') }}"
        main_record: "{{ env.dns_record | default('') }}"
        static:
        - title: "DNS A records"
          type: "A"
          list: "{{ env.dns_a_list | default([]) }}"
        - title: "DNS CNAME records"
          type: "CNAME"
          list: "{{ env.dns_cname_list | default([]) }}"

- set_fact:
    main_vars_container_vars_default: "{{ (env.container_vars | default({})).default | default({}) }}"
    main_vars_container_vars_default_build: "{{ (env.container_vars | default({})).default_build | default({}) }}"
    main_vars_container_vars_default_run: "{{ (env.container_vars | default({})).default_run | default({}) }}"
    main_vars_container_vars_app_build: "{{ (env.container_vars | default({})).app_build | default({}) }}"
    main_vars_container_vars_app_run: "{{ (env.container_vars | default({})).app_run | default({}) }}"
    main_vars_container_vars_web_build: "{{ (env.container_vars | default({})).web_build | default({}) }}"
    main_vars_container_vars_web_run: "{{ (env.container_vars | default({})).web_run | default({}) }}"
    main_vars_container_vars_redis_master_run: "{{ (env.container_vars | default({})).redis_master_run | default({}) }}"
    main_vars_container_vars_db_master_run: "{{ (env.container_vars | default({})).db_master_run | default({}) }}"

- set_fact:
    main_vars_containers: 
      app_build: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_build) | combine(main_vars_container_vars_app_build) }}"
      app_run: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_run) | combine(main_vars_container_vars_app_run) }}"
      web_build: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_build) | combine(main_vars_container_vars_web_build) }}"
      web_run: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_run) | combine(main_vars_container_vars_web_run) }}"
      redis_master_run: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_run) | combine(main_vars_container_vars_redis_master_run) }}"
      db_master_run: "{{ main_vars_container_vars_default | combine(main_vars_container_vars_default_run) | combine(main_vars_container_vars_db_master_run) }}"

- set_fact:
    main_vars_cloud_aux:
      digital_ocean:
        tags:
        - "main"
        - "auto"
        - "dmz"
        - "web"
        - "redis"
        - "postgres"
        - "tmp"
        firewalls:
        - name: "auto"
          tags: ["auto"]
          inbound_rules:
          - ports: "22"
            sources:
              tags: ["main"]
          outbound_rules:
          - protocol: "tcp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "udp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "icmp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
        - name: "dmz"
          tags: ["dmz"]
          inbound_rules:
          - ports: "80"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]
          - ports: "443"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]
        - name: "web"
          tags: ["web"]
          inbound_rules:
          - ports: "80"
            sources:
              tags: ["dmz"]
          - ports: "443"
            sources:
              tags: ["dmz"]
        - name: "redis"
          tags: ["redis"]
          inbound_rules:
          - ports: "6379"
            sources:
              tags: ["web"]
        - name: "postgres"
          tags: ["postgres"]
          inbound_rules:
          - ports: "5432"
            sources:
              tags: ["web"]
      
      docker:
        image_owner: "{{ env.cloud_docker_image_owner | default('') }}"
        image_name: "{{ env.cloud_docker_image_name | default('') }}"
        credentials: 
          registry: "{{ env.cloud_docker_registry | default(None) }}"
          username: "{{ env.cloud_docker_username | default('') }}"
          password: "{{ env.cloud_docker_password | default('') }}"
          reauthorize: "{{ env.cloud_docker_reauthorize | default(false) | bool }}"

- set_fact:
    main_vars_cloud:
      digital_ocean:
        bootstrap:
          tmp:
            role: "main_do"
            vars:
              main_do_instance_type: "tmp"
              main_do_region: "{{ env.cloud_region | default('nyc1') }}"
              main_do_title: "Bootstrap Instance"
              main_do_hosts_file: "{{ inventory_file }}"
              main_do_api_token: "{{ env.cloud_api_token }}"
              main_do_host_user: "{{ env.cloud_host_user }}"
              main_do_host_pass: "{{ env.cloud_host_pass }}"
              main_do_ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
              main_do_all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
              main_do_all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
              main_do_tags: 
              - "auto"
              - "tmp"
              main_do_instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
              main_do_instance_max: 1
              main_do_instance_group: "discourse_bootstrap"
              main_do_instance_name: "discourse-bootstrap"
              main_do_instance_tmp: "{{ true | bool }}"
              containers:
              - name: "app-build"
                action: "bootstrap"
                vars: "{{ main_vars_containers.app_build }}"
                push: "{{ true | bool }}"
                push_credentials: "{{ main_vars_cloud_aux.docker.credentials }}"
                push_owner: "{{ main_vars_cloud_aux.docker.image_owner }}"
                push_name: "{{ main_vars_cloud_aux.docker.image_name }}"
                push_tag: "app-{{ (env.cloud_docker_image_version | default({})).app | default('') }}"
            extra:
              dmz: "{{ false | bool }}"
              load_balance: "{{ false | bool }}"

        layer1:
          app:
            role: "main_do"
            vars:
              main_do_instance_type: "app"
              main_do_region: "{{ env.cloud_region | default('nyc1') }}"
              main_do_title: "App Instance"
              main_do_hosts_file: "{{ inventory_file }}"
              main_do_api_token: "{{ env.cloud_api_token }}"
              main_do_host_user: "{{ env.cloud_host_user }}"
              main_do_host_pass: "{{ env.cloud_host_pass }}"
              main_do_ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
              main_do_all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
              main_do_all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
              main_do_tags: 
              - "auto"
              - "dmz"
              main_do_instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
              main_do_instance_max: 1
              main_do_instance_group: "discourse_app"
              main_do_instance_name: "discourse-app"
              main_do_instance_tmp: "{{ false | bool }}"
              containers:
              - name: "app-build"
                skip: "{{ (main_vars_containers.app_run.base_image | default('')) != '' }}"
                action: "bootstrap"
                vars: "{{ main_vars_containers.app_build }}"
              - name: "app-run"
                vars: "{{ main_vars_containers.app_run }}"
            extra:
              dmz: "{{ true | bool }}"
              load_balance: "{{ false | bool }}"

        layer2:
          db_master:
            role: "main_do"
            vars:
              main_do_instance_type: "db_master"
              main_do_region: "{{ env.cloud_region | default('nyc1') }}"
              main_do_title: "DB Instance"
              main_do_hosts_file: "{{ inventory_file }}"
              main_do_api_token: "{{ env.cloud_api_token }}"
              main_do_host_user: "{{ env.cloud_host_user }}"
              main_do_host_pass: "{{ env.cloud_host_pass }}"
              main_do_ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
              main_do_all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
              main_do_all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
              main_do_tags: 
              - "auto"
              - "postgres"
              main_do_instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
              main_do_instance_max: 1
              main_do_instance_group: "discourse_db_master"
              main_do_instance_name: "discourse-db-master"
              main_do_instance_tmp: "{{ false | bool }}"
              containers:
              - name: "db"
                vars: "{{ main_vars_containers.db_master_run }}"
            extra:
              dmz: "{{ false | bool }}"
              load_balance: "{{ false | bool }}"

          redis_master:
            role: "main_do"
            vars:
              main_do_instance_type: "redis_master"
              main_do_region: "{{ env.cloud_region | default('nyc1') }}"
              main_do_title: "Redis Instance"
              main_do_hosts_file: "{{ inventory_file }}"
              main_do_api_token: "{{ env.cloud_api_token }}"
              main_do_host_user: "{{ env.cloud_host_user }}"
              main_do_host_pass: "{{ env.cloud_host_pass }}"
              main_do_ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
              main_do_all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
              main_do_all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
              main_do_tags: 
              - "auto"
              - "redis"
              main_do_instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
              main_do_instance_max: 1
              main_do_instance_group: "discourse_redis_master"
              main_do_instance_name: "discourse-redis-master"
              main_do_instance_tmp: "{{ false | bool }}"
              containers:
              - name: "redis"
                vars: "{{ main_vars_containers.redis_master_run }}"
            extra:
              dmz: "{{ false | bool }}"
              load_balance: "{{ false | bool }}"

          web:
            role: "main_do"
            vars:
              main_do_instance_type: "web"
              main_do_region: "{{ env.cloud_region | default('nyc1') }}"
              main_do_title: "Web Instance"
              main_do_hosts_file: "{{ inventory_file }}"
              main_do_api_token: "{{ env.cloud_api_token }}"
              main_do_host_user: "{{ env.cloud_host_user }}"
              main_do_host_pass: "{{ env.cloud_host_pass }}"
              main_do_ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
              main_do_all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
              main_do_all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
              main_do_tags: 
              - "auto"
              - "web"
              - "dmz"
              main_do_instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
              main_do_instance_max: 1
              main_do_instance_group: "discourse_web"
              main_do_instance_name: "discourse-web"
              main_do_instance_tmp: "{{ false | bool }}"
              containers:
              - name: "web_only"
                dynamic_host_vars:
                - name: "db_host"
                  group: "discourse_db_master"
                  count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                - name: "redis_host"
                  group: "discourse_redis_master"
                  count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                vars: "{{ main_vars_containers.web_run }}"
            extra:
              dmz: "{{ true | bool }}"
              load_balance: "{{ false | bool }}"

- name: main discourse vars
  set_fact:
    main_vars:
      cloud: "{{ main_vars_cloud[env.cloud_type][env.cloud_layer] }}"
      dns: "{{ main_vars_dns[env.dns_type | default('')] | default({}) }}"
