- name: Load cloud vars
  include_vars:
    file: "files/discourse/cloud.yml"
    name: main_vars_cloud

- set_fact:
    main_vars:
      cloud: "{{ main_vars_cloud.cloud[env.cloud_type][env.cloud_layer] }}"
      dns: "{{ main_vars_cloud.cloud_dns[env.dns_type] }}"

- debug:
    var: main_vars