- name: Load environment vars
  include_vars:
    file: "{{ main_do_env_file }}"
    name: env

- name: verify if platform match the one from the env variable
  fail:
    file: "{{ env.platform }}"
  name: (env.platform is not defined) or (env.platform != main_vars_platform)

- name: Load environment vars
  include_tasks:  "{{ env.platform }}.yml"
  