- name: load environment vars
  include_vars:
    file: "{{ main_vars_env_file }}"
    name: env

- name: verify if type match the one from the env variable
  fail:
    msg: "type is not defined in the environment vars"
  when: env.type is not defined

- name: verify if type match the one from the env variable
  fail:
    msg: "{{ main_vars_type }} should be {{ env.type }}"
  when: env.type != main_vars_type

- include_tasks:  "{{ env.type }}.yml"
  when: env.type != 'local'
  