- set_fact:
    main_vars_cloud_shutdown: "{{ env.cloud_shutdown | default(0) }}"
    main_vars_cloud_user_data_file: "roles/main_cloud/templates/ubuntu-18.04.j2.sh"
    main_vars_env_name: "{{ env.name | ternary(env.name + '-', '') }}"
    main_vars_instance_groups_to_destroy: >-
      {{ env.cloud_instance_groups_to_destroy | default([]) }}
    main_vars_buckets_to_destroy: "{{ env.cloud_buckets_to_destroy | default([]) }}"
    main_vars_ipv6: "{{ env.cloud_ipv6 | default('no') }}"

- set_fact:
    main_vars_dns:
      cloudflare:
        task: "cloudflare_dns"
        zone: "{{ env.dns_zone | default('') }}"
        credentials:
          account_email: "{{ env.dns_cloudflare_email | default('') }}"
          account_api_token: "{{ env.dns_cloudflare_token | default('') }}"
        main_record: "{{ env.dns_record | default('') }}"
        static:
        - title: "DNS A records"
          type: "A"
          list: "{{ env.dns_a_list | default([]) }}"
        - title: "DNS CNAME records"
          type: "CNAME"
          list: "{{ env.dns_cname_list | default([]) }}"

- set_fact:
    main_vars_cloud_aux:
      digital_ocean:
        tags:
        - "main"
        - "auto"
        - "dmz"
        - "web"
        - "redis"
        - "mysql"
        firewalls:
        - name: "auto"
          tags: ["auto"]
          inbound_rules:
          - ports: "22"
            sources:
              tags: ["main"]
          outbound_rules:
          - protocol: "tcp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "udp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
          - protocol: "icmp"
            ports: "1-65535"
            destinations:
              addresses: ["0.0.0.0/0", "::/0"]
        - name: "dmz"
          tags: ["dmz"]
          inbound_rules:
          - ports: "80"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]
          - ports: "443"
            sources:
              addresses: ["0.0.0.0/0", "::/0"]
        - name: "web"
          tags: ["web"]
          inbound_rules:
          - ports: "80"
            sources:
              tags: ["dmz"]
          - ports: "443"
            sources:
              tags: ["dmz"]
        - name: "redis"
          tags: ["redis"]
          inbound_rules:
          - ports: "6379"
            sources:
              tags: ["web"]
        - name: "mysql"
          tags: ["mysql"]
          inbound_rules:
          - ports: "3306"
            sources:
              tags: ["web"]

- set_fact:
    main_vars_cloud:
      digital_ocean:      
        layer1:
          app:
            role: "digital_ocean"
            vars:
              cloud:
                instance_type: "app"
                region: "{{ env.cloud_region | default('nyc1') }}"
                title: "App Instance"
                hosts_file: "{{ inventory_file }}"
                api_token: "{{ env.cloud_api_token }}"
                host_user: "{{ env.cloud_host_user }}"
                host_pass: "{{ env.cloud_host_pass }}"
                ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
                all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
                all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
                tags: 
                - "auto"
                - "dmz"
                instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                instance_max: 1
                instance_group: "app"
                instance_name: "{{ main_vars_env_name }}discourse-app"
                instance_tmp: false
                ipv6: "{{ main_vars_ipv6 }}"
                user_data_file: "{{ main_vars_cloud_user_data_file }}"
            extra:
              dmz: true
              load_balance: false

        layer2:
          db_master:
            role: "digital_ocean"
            vars:
              cloud:
                instance_type: "db_master"
                region: "{{ env.cloud_region | default('nyc1') }}"
                title: "DB Instance"
                hosts_file: "{{ inventory_file }}"
                api_token: "{{ env.cloud_api_token }}"
                host_user: "{{ env.cloud_host_user }}"
                host_pass: "{{ env.cloud_host_pass }}"
                ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
                all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
                all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
                tags: 
                - "auto"
                - "mysql"
                instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                instance_max: 1
                instance_group: "db_master"
                instance_name: "{{ main_vars_env_name }}discourse-db-master"
                instance_tmp: false
                ipv6: "{{ main_vars_ipv6 }}"
                user_data_file: "{{ main_vars_cloud_user_data_file }}"
            extra:
              dmz: false
              load_balance: false

          redis_master:
            role: "digital_ocean"
            vars:
              cloud:
                instance_type: "redis_master"
                region: "{{ env.cloud_region | default('nyc1') }}"
                title: "Redis Instance"
                hosts_file: "{{ inventory_file }}"
                api_token: "{{ env.cloud_api_token }}"
                host_user: "{{ env.cloud_host_user }}"
                host_pass: "{{ env.cloud_host_pass }}"
                ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
                all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
                all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
                tags: 
                - "auto"
                - "redis"
                instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                instance_max: 1
                instance_group: "redis_master"
                instance_name: "{{ main_vars_env_name }}discourse-redis-master"
                instance_tmp: false
                ipv6: "{{ main_vars_ipv6 }}"
                user_data_file: "{{ main_vars_cloud_user_data_file }}"
            extra:
              dmz: false
              load_balance: false

          web:
            role: "digital_ocean"
            vars:
              cloud:
                instance_type: "web"
                region: "{{ env.cloud_region | default('nyc1') }}"
                title: "Web Instance"
                hosts_file: "{{ inventory_file }}"
                api_token: "{{ env.cloud_api_token }}"
                host_user: "{{ env.cloud_host_user }}"
                host_pass: "{{ env.cloud_host_pass }}"
                ssh_public_keys: "{{ env.cloud_host_ssh_public_keys }}"
                all_tags: "{{ main_vars_cloud_aux.digital_ocean.tags }}"
                all_firewalls: "{{ main_vars_cloud_aux.digital_ocean.firewalls }}"
                tags: 
                - "auto"
                - "web"
                - "dmz"
                instance_count: "{{ (main_vars_cloud_shutdown == 1) | ternary(0, 1) }}"
                instance_max: 1
                instance_group: "web"
                instance_name: "{{ main_vars_env_name }}discourse-web"
                instance_tmp: false
                ipv6: "{{ main_vars_ipv6 }}"
                user_data_file: "{{ main_vars_cloud_user_data_file }}"
            extra:
              dmz: true
              load_balance: false

- set_fact:
    main_vars_prepare:
      env:
        docker_compose_file: "{{ env.docker_compose_file }}"
        perl_version: "{{ env.perl_version | default('', true) }}"
        nginx_version: "{{ env.nginx_version | default('', true) }}"
        wp_version: "{{ env.wp_version | default('', true) }}"
        pma_version: "{{ env.pma_version | default('', true) }}"
        mysql_image: "{{ env.mysql_image | default('', true) }}"
        mysql_version: "{{ env.mysql_version | default('', true) }}"
        db_host: "{{ env.db_host | default('', true) }}"
        db_port: "{{ env.db_port | default('', true) }}"
        wp_db_user: "{{ env.wp_db_user | default('', true) }}"
        wp_db_pass: "{{ env.wp_db_pass | default('', true) }}"
        mysql_root_pass: "{{ env.mysql_root_pass | default('', true) }}"

- name: main discourse vars
  set_fact:
    main_vars:
      cloud: "{{ main_vars_cloud[env.cloud_type][env.cloud_layer] }}"
      dns: "{{ main_vars_dns[env.dns_type | default('')] | default({}) }}"
      prepare: "{{ main_vars_prepare }}"
      destroy: 
        instance_groups: "{{ main_vars_instance_groups_to_destroy | list }}"
        buckets: "{{ main_vars_buckets_to_destroy | list }}"
