- name: "{{ compose_run_title }} - set_fact"
  set_fact:
    compose_run_repo_location: >-
      {{ compose_run_base_dir }}/pod-{{ compose_run_context.name }}
    compose_run_backup_file_src: >-
      {{ compose_run_base_dir }}/{{ compose_run_file_env_vars_relative_src }}
    compose_run_backup_file_dest: >-
      {{ compose_run_base_dir }}/{{ compose_run_file_env_vars_relative_dest }}

- name: "{{ compose_run_title }} - create the backup directories"
  become: "{{ compose_run_docker_become }}"
  file:
    path: "{{ compose_run_item | dirname }}"
    state: directory
    owner: "{{ compose_run_host_user }}"
    group: "{{ compose_run_host_group }}"
    mode: 0751
  loop:
  - "{{ compose_run_backup_file_src }}"
  - "{{ compose_run_backup_file_dest }}"
  loop_control:
    loop_var: compose_run_item
    label: "{{ compose_run_item | dirname }}"
      
- name: >-
    {{ compose_run_title }} - create empty env file in backup directory
    if there is no file there
  become: "{{ compose_run_docker_become }}"
  copy: 
    force: no
    content: ""
    dest: "{{ compose_run_backup_file_dest }}"
    owner: "{{ compose_run_host_user }}"
    group: "{{ compose_run_host_group }}"
    mode: 0640

- name: "{{ compose_run_title }} - get the difference of the 2 env files (old and current)"
  become: "{{ compose_run_docker_become }}"
  command: "diff {{ compose_run_backup_file_src }} {{ compose_run_backup_file_dest }}"
  register: compose_run_diff
  failed_when: compose_run_diff.rc > 1
  changed_when: compose_run_diff.rc == 1

- block:

  - name: "{{ compose_run_title }} - run the setup script"
    become: "{{ compose_run_docker_become }}"
    command: "{{ compose_run_context.cmd }}"
    args:
      chdir: "{{ compose_run_repo_location }}/"
    when: (compose_run_context.cmd | default('')) != ''
    tags: ["print_action"]

  - name: "{{ compose_run_title }} - run the images"
    become: "{{ compose_run_docker_become }}"
    command: "docker-compose up -d --remove-orphans"
    args:
      chdir: "{{ compose_run_repo_location }}/"
    tags: ["print_action"]
    
  - name: >-
      {{ compose_run_title }} - 
      backup the env context vars file 
      (to avoid running when the variables haven't changed)
    become: "{{ compose_run_docker_become }}"
    copy: 
      remote_src: yes
      src: "{{ compose_run_backup_file_src }}"
      dest: "{{ compose_run_backup_file_dest }}"
      owner: "{{ compose_run_host_user }}"
      group: "{{ compose_run_host_group }}"
      mode: 0640

  when: "compose_run_diff.changed" 

- name: "{{ compose_run_title }} - debug"
  debug: 
    msg: "variables unchanged"
  when: not compose_run_diff.changed
  tags: ["print_action"]


- name: "{{ compose_run_title }} - environment run cmd"
  include_role: 
    name: long_run
  vars:
    long_run_title: "{{ compose_run_title }} - environment run cmd"
    long_run_become: "{{ compose_run_docker_become }}"
    long_run_output_path: "{{ compose_run_base_dir }}/data/log"
    long_run_output_file: "env-run.log"
    long_run_path: "{{ compose_run_repo_location }}"
    long_run_cmd: "{{ compose_run_env_cmd }}"
  when: (compose_run_env_cmd | default('')) != ''
  tags: ["print_action"]