- name: "{{ local_prepare_title }} - verify if docker compose file is defined"
  fail:
    msg: "[Error] Specify the environment repo variable: docker_compose_file"
  when: (local_prepare_docker_compose_file is not defined) or (local_prepare_docker_compose_file == '')

- name: "{{ local_prepare_title }} - create the repo directory {{ local_prepare_repo_location }}"
  file:
    path: "{{ local_prepare_repo_location }}"
    state: directory
    mode: 0700

- name: "{{ local_prepare_title }} - update the temporary repo directory"
  git:
    repo: "{{ local_prepare_docker_repo }}"
    version: "{{ local_prepare_docker_repo_version }}"
    dest: "{{ local_prepare_repo_location }}"
    update: no
  register: local_prepare_git_result
  tags: ["print_action"]

- set_fact:
    local_prepare_git_commit: "{{ local_prepare_git_result.after }}"

- name: "{{ local_prepare_title }} - transfer the env template file"
  template: 
    src: "{{ local_prepare_repo_location }}/templates/.env"
    dest: "{{ local_prepare_repo_location }}/.env"
    mode: 0600
  vars:
    compose_prepare_docker_repo: "{{ local_prepare_docker_repo }}"
    compose_prepare_docker_repo_version: "{{ local_prepare_docker_repo_version }}"
    compose_prepare_docker_compose_file: "{{ local_prepare_docker_compose_file }}"
    compose_prepare_git_commit: "{{ local_prepare_git_commit }}"
    compose_prepare_env: "{{ local_prepare_env }}"
    