- name: "{{ local_prepare_title }} - verify if the 'name' environment variable is defined"
  fail:
    msg: "[Error] Specify the environment variable: 'name' (will be the repo name)"
  when: (local_prepare_repo_name is not defined) or (local_prepare_repo_name == '')

- name: "{{ local_prepare_title }} - verify if the 'vars_template_dir' environment variable is defined"
  fail:
    msg: "[Error] Specify the directory of the template with variables: 'vars_template_dir'"
  when: ((local_prepare_vars_template_dir | default('')) == '')

- name: "{{ local_prepare_title }} - set_fact - local_prepare_repo_location"
  set_fact:
    local_prepare_repo_location: "/main/dev/{{ local_prepare_repo_name }}"

- name: "{{ local_prepare_title }} - create the repo directory {{ local_prepare_repo_location }}"
  file:
    path: "{{ local_prepare_repo_location }}"
    state: directory
    mode: 0700

- name: "{{ local_prepare_title }} - update the repo directory"
  git:
    repo: "{{ local_prepare_docker_repo }}"
    version: "{{ local_prepare_docker_repo_version }}"
    dest: "{{ local_prepare_repo_location }}"
    update: no
  register: local_prepare_git_result
  tags: ["print_action"]

- name: "{{ local_prepare_title }} - get template file with variables from the repo directory"
  template: 
    src: "{{ local_prepare_repo_location }}/{{ local_prepare_vars_template_dir }}/app.yml"
    dest: "{{ local_prepare_tmp_dir }}/local_prepare_vars.yml"
    mode: 0600
  vars:
    params: "{{ local_prepare_env_params }}"
    params_aux:
      docker_repo: "{{ local_prepare_docker_repo }}"
      docker_repo_version: "{{ local_prepare_docker_repo_version }}"
      git_commit: "{{ local_prepare_git_result.after }}"
  tags: ["print_action"]

- name: load environment vars
  include_vars:
    file: "{{ local_prepare_tmp_dir }}/local_prepare_vars.yml"
    name: local_prepare_vars

- name: "{{ local_prepare_title }} - get owner of file"
  stat:
    path: "{{ local_prepare_repo_location }}/.gitignore"
  register: local_prepare_stat

- name: "{{ local_prepare_title }} - set_fact"
  set_fact:
    local_prepare_owner: "{{ local_prepare_stat.stat.uid }}"
    local_prepare_group: "{{ local_prepare_stat.stat.gid }}"

- name: "{{ local_prepare_title }} - create the repo directory {{ local_prepare_repo_location }}/env"
  file:
    path: "{{ local_prepare_repo_location }}/env"
    state: directory
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0700

- name: "{{ local_prepare_title }} - create the volume directories"
  file:
    state: directory
    path: "{{ local_prepare_item.path }}"
    mode: "{{ local_prepare_item.mode }}"
  loop: "{{ local_prepare_vars.volumes | default([]) }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.path }}"

- name: "{{ local_prepare_title }} - set_fact - local_prepare_tpl_list - empty"
  set_fact:
    local_prepare_tpl_list: []

- name: "{{ local_prepare_title }} - set_fact - local_prepare_tpl_list - fill"
  set_fact:
    local_prepare_tpl_list: >-
      {{ 
      local_prepare_tpl_list
      + [{ 
      'src': local_prepare_item_src, 
      'dest': local_prepare_item_dest, 
      'params': local_prepare_item_params
      }] 
      }}
  vars: 
    local_prepare_item_src: "{{ local_prepare_repo_location }}/templates/{{ local_prepare_item.src }}"
    local_prepare_item_dest: >-
      {{ local_prepare_repo_location }}/{{ 
      ((local_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
      + (local_prepare_item.dest | default(local_prepare_item.src)) 
      }}
    local_prepare_item_params: "{{ local_prepare_item.params | default({}) }}"
  loop: "{{ local_prepare_vars.templates | default([]) }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.dest | default(local_prepare_item.src) }}"

- name: "{{ local_prepare_title }} - create directories for the repository templates"
  file:
    path: "{{ local_prepare_item.dest | dirname }}"
    state: directory
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0700
  loop: "{{ local_prepare_tpl_list | default([]) }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.dest | dirname }}"

- name: "{{ local_prepare_title }} - transfer the repository template files"
  template: 
    src: "{{ local_prepare_item.src }}"
    dest: "{{ local_prepare_item.dest }}"
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0600
  vars:
    params: "{{ local_prepare_item.params }}"
  loop: "{{ local_prepare_tpl_list | default([]) }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.dest }}"
  tags: ["print_action"]
