### Validation ###

- name: "{{ local_prepare_title }} - verify if the 'pod.ctx_dir' environment variable is defined"
  fail:
    msg: "[Error] Specify the directory of the templates with variables: 'pod.ctx_dir'"
  when: ((local_prepare_ctx_dir | default('')) == '')

- name: "{{ local_prepare_title }} - verify if the 'pod.vars_dir' environment variable is defined"
  fail:
    msg: "[Error] Specify the directory of the templates with variables: 'pod.vars_dir'"
  when: ((local_prepare_vars_dir | default('')) == '')

- name: >-
    {{ local_prepare_title }} - verify if there's at least 
    1 template file with variables defined for the local pod
  fail:
    msg: "[Error] There must be at least 1 template file with variables defined for the local pod"
  when: ((local_prepare_params | length) == 0)  

### Prepare the directories and repository ###

- name: "{{ local_prepare_title }} - set_fact - local_prepare_repo_location"
  set_fact:
    local_prepare_repo_location: "{{ local_prepare_pod.dir }}"

- name: "{{ local_prepare_title }} - create the repo directory {{ local_prepare_repo_location }}"
  file:
    path: "{{ local_prepare_repo_location }}"
    state: directory
    mode: 0751

- name: "{{ local_prepare_title }} - update the repo directory"
  git:
    repo: "{{ local_prepare_pod.repo }}"
    version: "{{ local_prepare_pod.repo_version }}"
    dest: "{{ local_prepare_repo_location }}"
    update: no
  register: local_prepare_git_result
  tags: ["print_action"]

- name: "{{ local_prepare_title }} - update the repo directories of the apps"
  git:
    repo: "{{ local_prepare_item.repo }}"
    version: "{{ local_prepare_item.repo_version }}"
    dest: "{{ local_prepare_item.dir }}"
    update: no
  loop: "{{ local_prepare_apps_info }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.name }}"
  tags: ["print_action"]

- name: "{{ local_prepare_title }} - get owner of file"
  stat:
    path: "{{ local_prepare_repo_location }}/.gitignore"
  register: local_prepare_stat

- name: "{{ local_prepare_title }} - set_fact - owner"
  set_fact:
    local_prepare_owner: "{{ local_prepare_stat.stat.uid | string }}"
    local_prepare_group: "{{ local_prepare_stat.stat.gid | string }}"

- name: "{{ local_prepare_title }} - create the repo env directories"
  file:
    state: directory
    path: "{{ local_prepare_repo_location }}/{{ local_prepare_item }}"
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0751
  loop:
  - "env"
  - "env/tmp"
  loop_control:
    loop_var: local_prepare_item

### Generate the environment pod context variables ###

- name: "{{ local_prepare_title }} - populate vars from templates (debug)"
  debug: 
    msg: "populate vars from templates"
  tags: ["print_action"]

- name: "{{ local_prepare_title }} - set_fact - owner"
  set_fact:
    local_prepare_app_dict: {}

- name: "{{ local_prepare_title }} - set_fact - local_prepare_app_dict"
  set_fact:
    local_prepare_app_dict: >-
      {{ local_prepare_app_dict
      | combine( 
      { local_prepare_item.name: {
      'repo': local_prepare_item.repo,
      'repo_version': local_prepare_item.repo_version,
      'dir_rel': local_prepare_item.dir_rel,
      'dir': local_prepare_item.dir
      }
      } ) }}
  loop: "{{ local_prepare_apps_info | default([]) }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.name }}"

- name: "{{ compose_prepare_title }} - set_fact - vars"
  set_fact:
    local_prepare_ctx_tpl_src: >-
      {{ local_prepare_repo_location }}/{{
      }}{{ local_prepare_ctx_dir }}/{{
      }}{{ local_prepare_subtype }}.local.yml"
    local_prepare_ctx_tpl_dest: >-
      {{ local_prepare_tmp_dir }}/{{
      }}local_prepare_ctx_{{ local_prepare_subtype }}.local.yml"
  
- name: "{{ local_prepare_title }} - get the context variables from templates"
  template: 
    src: "{{ local_prepare_ctx_tpl_src }}"
    dest: "{{ local_prepare_ctx_tpl_dest }}"
    mode: 0640
  vars:
    params: "{{ local_prepare_params }}"
    params_aux:
      pod: "{{ local_prepare_pod }}"
      app: "{{ local_prepare_app_dict }}"
      git_commit: "{{ local_prepare_git_result.after }}"
      repo_name: "{{ local_prepare_repo_name }}"
      data_dir: "{{ local_prepare_data_dir_outside }}/{{ local_prepare_repo_name }}"

- name: "{{ local_prepare_title }} - load ctx environment vars ({{ local_prepare_subtype }}.local)"
  include_vars:
    file: "{{ local_prepare_ctx_tpl_dest }}"
    name: local_prepare_ctx_outer_params

### Generate the environment pod expanded variables ###

- name: "{{ local_prepare_title }} - set_fact - vars"
  set_fact:
    local_prepare_vars_volumes: []
    local_prepare_vars_files: []
    local_prepare_vars_templates: []
    local_prepare_vars_env_files: []

- name: "{{ local_prepare_title }} - set_fact - local_prepare_ctx_params"
  set_fact:
    local_prepare_ctx_params: "{{ local_prepare_ctx_outer_params.params }}"

- name: "{{ local_prepare_title }} - populate vars from templates (outer)"
  include_tasks: "vars.yml"
  loop: "{{ local_prepare_ctx_params }}"
  loop_control:
    loop_var: local_prepare_item
    label: "{{ local_prepare_item.name }}"

### Generate a file with all the environment pod expanded variables ###

- name: "{{ local_prepare_title }} - set_fact - vars_full"
  set_fact:
    local_prepare_vars_full:
      volumes: "{{ local_prepare_vars_volumes }}"
      files: "{{ local_prepare_vars_files }}"
      templates: "{{ local_prepare_vars_templates }}"
      env_files: "{{ local_prepare_vars_env_files }}"

- name: >-
    {{ local_prepare_title }} - create the file to verify if there was a change, 
    if it was not created before
  copy: 
    force: no
    content: ""
    dest: "{{ local_prepare_repo_location }}/env/tmp/local_prepare_vars_full.yml"
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0640

- name: "{{ local_prepare_title }} - create the temporary file to verify if there was a change"
  copy: 
    content: "{{ local_prepare_vars_full | to_nice_yaml }}"
    dest: "{{ local_prepare_repo_location }}/env/tmp/local_prepare_tmp_vars_full.yml"
    owner: "{{ local_prepare_owner }}"
    group: "{{ local_prepare_group }}"
    mode: 0640

- name: "{{ local_prepare_title }} - get the difference of the 2 files (old and current)"
  command: >-
    diff 
    {{ local_prepare_repo_location }}/env/tmp/local_prepare_tmp_vars_full.yml 
    {{ local_prepare_repo_location }}/env/tmp/local_prepare_vars_full.yml
  register: local_prepare_diff
  failed_when: local_prepare_diff.rc > 1
  changed_when: local_prepare_diff.rc == 1

### Use the environment pod expanded variables to generate the pod files when changed ###

- block:

  - name: "{{ local_prepare_title }} - set_fact - local_prepare_tpl_list - empty"
    set_fact:
      local_prepare_tpl_list: []

  - name: "{{ local_prepare_title }} - set_fact - local_prepare_tpl_list - fill"
    set_fact:
      local_prepare_tpl_list: >-
        {{ 
        local_prepare_tpl_list
        + [{ 
        'src': local_prepare_item_src_full, 
        'dest': local_prepare_item_dest_full, 
        'mode': local_prepare_item.mode | default('', true), 
        'params': local_prepare_item_params
        }] 
        }}
    vars: 
      local_prepare_item_src_full: >-
        {{ local_prepare_repo_location }}/templates/{{ local_prepare_item.src }}
      local_prepare_item_dest_full: >-
        {{ local_prepare_repo_location }}/{{ 
        ((local_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + (local_prepare_item.dest | default(local_prepare_item.src)) 
        }}
      local_prepare_item_params: "{{ local_prepare_item.params | default({}) }}"
    loop: "{{ local_prepare_vars_templates | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.dest | default(local_prepare_item.src) }}"

  - name: "{{ local_prepare_title }} - create directories for the repository templates"
    file:
      path: "{{ local_prepare_item.dest | dirname }}"
      state: directory
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: 0751
    loop: "{{ local_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.dest | dirname }}"

  - name: "{{ local_prepare_title }} - create the volume directories"
    file:
      state: directory
      path: "{{ local_prepare_item.path }}"
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: "{{ local_prepare_item.mode }}"
    loop: "{{ local_prepare_vars_volumes | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.path }}"

  - name: "{{ local_prepare_title }} - copy the files to the specified locations"
    copy:
      src: "{{ local_prepare_item_src_full }}"
      dest: "{{ local_prepare_item_dest_full }}"
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: 0640
    vars: 
      local_prepare_item_src_full: >-
        {{ local_prepare_repo_location }}/files/{{ local_prepare_item.src }}
      local_prepare_item_dest_full: >-
        {{ local_prepare_repo_location }}/{{ 
        ((local_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + (local_prepare_item.dest | default(local_prepare_item.src)) 
        }}
    loop: "{{ local_prepare_vars_files | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.dest | default(local_prepare_item.src) }}"
    tags: ["print_action"]

  - name: "{{ local_prepare_title }} - transfer the templates to the specified locations"
    template: 
      src: "{{ local_prepare_item.src }}"
      dest: "{{ local_prepare_item.dest }}"
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: "{{ local_prepare_item.mode | default('0640', true) }}"
    vars:
      params: "{{ local_prepare_item.params }}"
    loop: "{{ local_prepare_tpl_list | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.dest }}"
    tags: ["print_action"]

  - name: "{{ local_prepare_title }} - copy the environment files to the specified locations"
    copy:
      src: "{{ local_prepare_item_src_full }}"
      dest: "{{ local_prepare_item_dest_full }}"
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: "{{ local_prepare_item.mode | default('0640', true) }}"
    vars: 
      local_prepare_item_src_full: "{{ local_prepare_env_dir }}/{{ local_prepare_item.src }}"
      local_prepare_item_dest_full: >-
        {{ local_prepare_repo_location }}/{{ 
        ((local_prepare_item.root | default(false) | bool) | ternary('', 'env/')) 
        + local_prepare_item.dest
        }}
    loop: "{{ local_prepare_vars_env_files | default([]) }}"
    loop_control:
      loop_var: local_prepare_item
      label: "{{ local_prepare_item.dest }}"
    tags: ["print_action"]

  - name: "{{ local_prepare_title }} - create the file to verify if there was a change (for newer runs)"
    copy: 
      remote_src: yes
      src: "{{ local_prepare_repo_location }}/env/tmp/local_prepare_tmp_vars_full.yml"
      dest: "{{ local_prepare_repo_location }}/env/tmp/local_prepare_vars_full.yml"
      owner: "{{ local_prepare_owner }}"
      group: "{{ local_prepare_group }}"
      mode: 0640
    tags: ["print_action"]

  when: local_prepare_diff.changed or True

- name: "{{ local_prepare_title }} - debug"
  debug: 
    msg: "variables unchanged"
  when: not local_prepare_diff.changed
  tags: ["print_action"]