- name: "{{ local_prepare_title }} - populate vars from templates ({{ local_prepare_item.name }})"
  template: 
    src: >-
      {{ local_prepare_repo_location }}/{{ local_prepare_vars_dir }}/{{ local_prepare_item.name }}.yml
    dest: "{{ local_prepare_tmp_dir }}/local_prepare_vars_{{ local_prepare_item.name }}.yml"
    mode: 0600
  vars:
    params: "{{ local_prepare_item.params }}"
    params_aux:
      docker_repo: "{{ local_prepare_docker_repo }}"
      docker_repo_version: "{{ local_prepare_docker_repo_version }}"
      git_commit: "{{ local_prepare_git_result.after }}"
      data_dir: "{{ local_prepare_data_dir_outside }}/{{ local_prepare_repo_name }}"

- name: "{{ local_prepare_title }} - load environment vars ({{ local_prepare_item.name }})"
  include_vars:
    file: "{{ local_prepare_tmp_dir }}/local_prepare_vars_{{ local_prepare_item.name }}.yml"
    name: local_prepare_inner_vars

- name: "{{ local_prepare_title }} - set_fact ({{ local_prepare_item.name }})"
  set_fact:
    local_prepare_vars_volumes: >-
      {{ local_prepare_vars_volumes + (local_prepare_inner_vars.volumes | default([])) }}
    local_prepare_vars_files: >-
      {{ local_prepare_vars_files + (local_prepare_inner_vars.files | default([])) }}
    local_prepare_vars_templates: >-
      {{ local_prepare_vars_templates + (local_prepare_inner_vars.templates | default([])) }}
    local_prepare_vars_env_files: >-
      {{ local_prepare_vars_env_files + (local_prepare_inner_vars.env_files | default([])) }}