- name: "{{ cloud_dns_title }} - {{ cloud_dns.type }} record"
  fail:
    msg: "{{ cloud_dns_title }} - dns zone not defined"
  when: (cloud_dns_zone | default('')) == ''

- set_fact:
    cloud_dns_task: "ext/{{ cloud_dns.type }}.main.dns.yml"
  tags: ["no_print"]

- set_fact:
    cloud_dns_task: "{{ cloud_dns_env_ctx_params.custom_tasks[cloud_dns.type] }}"
  when: cloud_dns.custom_task | default(false) | bool
  tags: ["no_print"]

- name: "{{ cloud_dns_title }} - dns - {{ cloud_dns.type }}"
  include_tasks: "{{ cloud_dns_task }}"
  tags: ["no_print"]